<?php

$aLangContent = array(
    '_Membership_current' => 'Current',
    '_Membership_name' => 'Name',
    '_Membership_name_err_empty' => 'You need to select a membership levels',
    '_Membership_days' => 'Duration',
    '_Membership_days_info' => 'in days (leave empty for lifetime)',
    '_Membership_starts' => 'Starts immediately',
	'_Membership_save' => 'Save',
    '_Membership_save_msg_saved' => 'Membership level was updated successfully.',
    '_Membership_save_err_saved' => 'Cannot update membership level. Please report.',
    '_EMAIL_CONF_SUCCEEDED' => 'Congratulations! Your e-mail confirmation succeeded.<br /><br />Your profile has been successfully created, but it is awaiting review to be activated. Thank you for your patience.',
    '__Aland Islands' => 'Aland Islands',
    '__Saint Barthelemy' => 'Saint Barthelemy',
    '__Isle of Man' => 'Isle of Man',
    '__Saint Martin (French part)' => 'Saint Martin (French part)',
    '_Mailbox title empty' => 'Please enter a title',
    '_Mailbox recipient empty' => 'Please enter a recipient\'s nickname',
    '_Mailbox description empty' => 'Please enter a description',
    '_USER_CONF_SUCCEEDED' => 'Congratulations! Your account has been successfully confirmed.<br /><br />Your profile has been successfully created, but it is awaiting review to be activated. Thank you for your patience.',
    '_FieldDesc_Country_Join' => 'Select the country where you live ',
    '_FieldDesc_City_Join' => 'Specify the city where you live ',
    '_adm_mmi_mobile_pages' => 'Mobile Pages',
    '_adm_box_cpt_mlevel_edit' => 'Edit',
    '_adm_txt_mlevels_system' => 'System Levels',
    '_adm_txt_mlevels_custom' => 'Custom Levels',
    '_adm_txt_mlevels_edit' => 'Edit',
    '_adm_txt_mlevels_actions' => 'Actions',
    '_adm_txt_mlevels_order' => 'Order',
    '_adm_txt_mlevels_order_err' => 'You need to enter order for membership level. It should be more then zero.',
    '_edit_profile_membership' => 'Edit profile membership',
    '_sys_adm_installed' => 'Installed',
    '_sys_adm_available' => 'Available',
    '_adm_admtools_Audit' => 'Audit',
    '_sys_profile_private_text' => 'Information availability is limited by privacy settings.',
    '_sys_profile_private_text_title' => 'Limited Visibility',
    '_sys_mobile_status' => 'Status',
    '_sys_mobile_mail' => 'Messages',
    '_sys_mobile_friends' => 'Friends',
    '_sys_mobile_info' => 'Info',
    '_sys_mobile_search' => 'Search',
    '_sys_mobile_profile_info' => 'Profile Info',
    '_sys_mobile_profile_contact' => 'Contact',
    '_sys_mobile_profile_friends' => 'Friends',
    '_adm_mobile_builder_title' => 'Mobile Pages Builder',
    '_adm_mobile_builder_cont_active' => 'Active Items',
    '_adm_mobile_builder_cont_inactive' => 'Inactive Items',
    '_adm_mobile_page_homepage' => 'Homepage',
    '_adm_mobile_page_profile' => 'Profile',    
);

?>
