<?php
/**
 * ENGLISH language file: please UTF-8 encoding only, so use UTF-8 compliant editor only
 ****************************************************************************************/

$GLOBALS['L'] = array (
    'Forums Index' => 'Forums Index',
    'Forums' => 'Forums',
    'Forum' => 'Forum',
    'Topics' => 'Topics',
    'Topic' => 'Topic',
    'Orca Forum' => ':: Forum',
    'Logged in as' => 'Logged in as',
    'Manage Forum' => 'Manage Forum',
    'Reported Posts' => 'Reported Posts',
    'Logout' => 'Logout',
    'My Flags' => 'My Subscriptions',
    'Flag' => 'Subscribe',
    'Unflag' => 'Unsubscribe',
    'My Topics' => 'My Topics',
    'Login' => 'Login',
    'Search' => 'Search',
    'Copyright' => 'Copyrights Reserved',
    'New Group' => 'New Group',
    'New Topic' => 'New Topic',
    'Post Reply' => 'Reply',
    'Lock' => 'Lock',
    'Unlock' => 'Unlock',
    'Stick' => 'Stick',
    'Unstick' => 'Unstick',
    'Author' => 'Author',
    'Message' => 'Message',
    'posts:' => 'posts:',
    'Delete' => 'Delete',
    'Edit' => 'Edit',
    'Quote' => 'Quote',
    'post is hidden' => 'post is hidden',
    'hide post' => 'hide post',
    'show post' => 'show post',
    'Points:' => 'Likes:',
    'Vote' => 'Vote',
    'Access denied' => 'Access denied. You must have special permissions to access this area or you are not logged in.',
    'New topic created' => 'New topic has been created',
    'return to forum index' => 'return to forum index',
    'Edit group' => 'Edit group',
    'New group' => 'New group',
    'Cancel' => 'Cancel',
    'Submit' => 'Submit',
    'New forum' => 'New forum',
    'Forum title:' => 'Forum title:',
    'Forum description:' => 'Forum description:',
    'Forum type:' => 'Forum type:',
    'public' => 'public',
    'private' => 'private',
    'Latest Reply' => 'Latest Reply',
    'Latest Post' => 'Latest Post',
    'Posts' => 'Posts',
    'Pages:' => 'Pages:',
    'Join' => 'Join',
    'Forums Spy' => 'Latest Posts <span>(a real-time view of activity)</span>',
    'said in' => 'said in',
    'Topic subject:' => 'Topic subject:',
    'Topic subject Error' => 'Please enter from 5 to 50 symbols',
    'Topic forum Error' => 'Please select forum to post topic in',
    'Select Forum' => 'Select Forum',
    'Sticky' => 'Sticky',
    'Topic text:' => 'Topic text:',
    'Topic text Error' => 'Please enter from 5 to 128000 symbols',
    'Post Reply:' => 'Post Reply:',
    'Special Member' => 'Special Member',
    'Standard Member' => 'Standard Member',
    'Member Info' => 'Member Info',
    'Joined:' => 'Joined:',
    'Last Online:' => 'Last Online:',
    'Posts:' => 'Posts:',
    'Last Post:' => 'Last Post:',
    'never' => 'never',
    'Find all posts by' => 'Find all posts by',
    'New Search' => 'New Search',
    'Search Results For:' => 'Search Results For:',
    'There are no search results.' => 'There are no search results.',
    'Please try search again.' => 'Please <a href="javascript:void(0);" onclick="return f.showSearch()" >try again</a>.',
    'Date' => 'Date',
    'Search The Forum' => 'Search The Forum',
    'Search for:' => 'Search for:',
    'Where to Search:' => 'Where to Search:',
    'Topic Titles' => 'Topic Titles',
    'Messages' => 'Messages',
    'Forum:' => 'Forum:',
    'Whole Forum' => 'Whole Forum',
    'Author:' => 'Author:',
    'Display:' => 'Display:',

    'Site is unavailable' => 'Sorry, something went wrong and the site is unavailable now, please try again later.',
    'Join Login Username Error' => 'Username must be from 4 to 12 characters',
    'Join Email Error' => 'Email must be valid',
    'Username must be uniq' => 'Username must be uniq',
    'Login Password Error' => 'Password must be valid',
    'Email must be uniq' => 'Email must be uniq',
    'Database error' => 'Database error',
    'Send mail failed' => 'Send mail failed',
    'password or login is incorrect' => 'password or login is incorrect',
    'Cookies must be enabled to process login' => 'Cookies must be enabled to process login',

    'Username' => 'Username',
    'Password' => 'Password',
    'Email' => 'Email',
    'Wrong search type' => 'Wrong search type',
    'Topics you participate in' => 'Topics you participate in',
    'Flagged topics' => 'Topics subscriptions',
    'Topics you have flagged' => 'Topics you have subscribed for',
    '%s\'s forum posts' => '%s\'s forum posts',
    'Forum Posts' => 'Forum Posts',
    'Minute Ago' => 'm ago',
    'Minutes Ago' => 'm ago',
    'Hour Ago' => 'h ago',
    'Hours Ago' => 'h ago',
    'Day Ago' => 'd ago',
    'Days Ago' => 'd ago',
    'Mail Subj Registration' => 'Forum Registration Details',
    'Mail Body Registration' => "
<p>Dear {username},</p>

<p>
Your username: {username} <br />
Your password: {pwd} <br />
Site URL: {site_url} <br />
</p>

<p>
Thank you for joining.
</p>
<p>
Best Regards, Forum.
</p>
",
    'xml serialization failed' => 'xml serialization failed',
    'please upgrade your browser' => 'please upgrade your browser',
    'XML read failed:' => 'XML read failed:',
    'There was a problem retrieving the XML data:' => 'There was a problem retrieving the XML data:',
    'httpxml object creation failed' => 'httpxml object creation failed',

    'LOADING LOGIN FORM' => 'LOADING LOGIN FORM',
    'LOADING JOIN FORM' => 'LOADING JOIN FORM',
    'SEARCHING' => 'SEARCHING',
    'LOADING FORUMS' => 'LOADING FORUMS',
    'LOADING FORUM TOPICS' => 'LOADING FORUM TOPICS',
    'LOADING FORUM INDEX' => 'LOADING FORUM INDEX',
    'LOADING PROFILE PAGE' => 'LOADING PROFILE PAGE',
    'LOADING TOPIC POSTS' => 'LOADING TOPIC POSTS',
    'LOADING POST TOPIC PAGE' => 'LOADING POST TOPIC PAGE',
    'LOADING' => 'LOADING',
    'LOADING SEARCH PAGE' => 'LOADING SEARCH PAGE',
    'LOADING POST REPLY PAGE' => 'LOADING POST REPLY PAGE',
    'SENDING MESSAGE' => 'SENDING MESSAGE',
    'POST IS LOADING' => 'POST IS LOADING',

    'Thank you! You Joined! Your login and password have been sent to your email.' => 'Thank you! You Joined! Your login and password have been sent to your email.',
    'Join failed' => 'Join failed',
    'Login failed' => 'Login failed',
    'orca_main div is not defined' => 'orca_main div is not defined',
    'please name orca_main content container' => 'please name orca_main content container',
    'category id is not defined' => 'category id is not defined',
    'please set category ids' => 'please set category ids',
    'Please login to view topics you participate in' => 'Please login to view topics you participate in',
    'Please login to view flagged topics' => 'Please login to view topics subscriptions',
    'Are you sure ?' => 'Are you sure ?',
    'Post was successfully deleted' => 'Post was successfully deleted',
    'Topic and post were successfully deleted' => 'Topic and post were successfully deleted',
    'Post was successfully edited' => 'Post was successfully edited',
    'Message body empty' => 'Message body empty',
    'Valid chars:' => 'Valid chars:',
    'Topic has been successfully added to your flagged topics' => 'You have successfully subscribed to the topic',
    'Topic has been successfully removed from your flagged topics' => 'Topic has been successfully removed from your topics subscriptions',
    'Please login to flag topics' => 'Please login to subscribe to the topic',
    'Post has been reported' => 'Post has been reported',
    'Report error' => 'Report error',
    'add this to title' => ' :: Forum ',
    'Are you sure to delete category with all forums, topics and post?' => 'Are you sure to delete category with all forums, topics and post?',
    'Category has been successfully deleted' => 'Category has been successfully deleted',
    'Can not delete category' => 'Can not delete category',
    'Are you sure to delete forum with topics and posts' => 'Are you sure to delete forum with topics and posts',
    'Forum has been successfully deleted' => 'Forum has been deleted',
    'Can not delete forum' => 'Can not delete forum',
    'Group has been successfully modified' => 'Group has been modified',
    'New group has been successfully added' => 'New group has been added',
    'Can not modify group' => 'Can not modify group',
    'Can not add new group' => 'Can not add new group',
    'Forum has been successfully modified' => 'Forum has been modified',
    'New forum has been successfully added' => 'New forum has been added',
    'Can not modify forum' => 'Can not modify forum',
    'Can not add new forum' => 'Can not add new forum',
    'Topic has been successfully locked' => 'Topic has been locked',
    'Topic has been successfully unlocked' => 'Topic has been unlocked',
    'Topic has been successfully sticked' => 'Topic is sticky now',
    'Topic has been successfully un-sticked' => 'Topic has been un-sticked',
    'Only admin can lock/unlock topics' => 'Only admin can lock/unlock topics',
    'new group' => 'new group',
    'edit' => 'edit',
    'delete' => 'delete',
    'new forum' => 'new forum',
    'permalink' => 'permalink',
    'report this post' => 'report this post',
    'Compile Langs' => 'Compile Languages',
    'Compile Lang:' => 'Compile Language:',
    'Language files compilation have been failed' => 'Language files compilation have been failed. Please check folders permissions.',
    'Language files have been successfully compiled' => 'Language files have been successfully compiled',
    'Permalink' => '#',
    'RSS feed' => 'RSS',
    'RSS Feed' => 'RSS',
    'No topics' => 'There are no topics in this forum',
    '# forums' => '# forums',
    '# topics' => '# topics',
    '# posts' => '# posts',
    '# posts num' => '#',
    '# points' => '# likes',
    'last update: #' => 'last update: #',
    'last reply by # %' => 'last: # %',
    'last reply by #' => 'last reply by #',
    'created by # %' => 'first: # %',
    'Report' => 'Report',
    'Forum order:' => 'Forum order:',
    'Group name:' => 'Group name:',
    'Group order:' => 'Group order:',
    'Expand group by default:' => 'Expand group by default:',
    'Clear report' => 'Clear report',
    'Topic has been successfully hidden' => 'Topic has been hidden',
    'Topic has been successfully un-hidden' => 'Topic has been un-hidden',
    'Hidden Topics' => 'Hidden Topics',
    'Hidden Posts' => 'Hidden Posts',
    'Move topic form' => 'Move topic form',
    'Move Topic' => 'Move Topic',
    'Unhide Topic' => 'Unhide Topic',
    'Hide Topic' => 'Hide Topic',
    'Delete Topic' => 'Delete Topic',
    'Forum to move topic to:' => 'Forum to move topic to:',
    'After moving go to:' => 'After moving go to:',
    'Stay here' => 'Stay here',
    'Forum where topic is moved' => 'Forum where topic is moved',
    'Allowed edit post period is elapsed' => 'Allowed period for post editing has finished',
    'Allowed edit post period is # seconds' => 'Allowed edit post period is # seconds',
    'Recent Topics' => 'Recent Topics',
    'No posts' => 'There are no posts here so far',
    'Attach one more file' => 'Attach one more file',
    'Attachments:' => 'Attachments:',
    'Some or all files upload failed' => 'Some or all files upload failed',
    '# downloads' => '# downloads',
    '# views' => '# views',
    'Hide' => 'Hide',
    'Unhide' => 'Unhide',
    'Change Signature' => 'Change Signature',
    'Signature text Error' => 'Maximum is 100 characters',
    'Updated Topics' => 'Updated Topics',
    'Like' => 'Like',
    'Bury' => 'Bury',
    'Edit forum' => 'Edit forum',
    'continue_topic_suffix - %d' => ' - part %d',
    'continue_topic_last %s' => '<div class="forum_robot_msg bx-def-font">%s &#8594;</div>',
    'continue_topic_first %s' => '<div class="forum_robot_msg bx-def-font">&#8592; %s</div>',
    'insert to post' => 'insert to post',
);

?>
