<?php
/**
 * RUSSIAN language file: please UTF-8 encoding only, so use UTF-8 compliant editor only
 ****************************************************************************************/

$GLOBALS['L'] = array (
    'Forums Index' => 'Форумы Указатель',
    'Forums' => 'Форумы',
    'Forum' => 'Форум',
    'Topics' => 'Сообщения',
    'Topic' => 'Сообщение',
    'Orca Forum' => ':: Форум',
    'Logged in as' => 'Вошел как',
    'Manage Forum' => 'Форум Управление',
    'Reported Posts' => 'Сообщения, отмеченные жалобами',
    'Logout' => 'Выйти',
    'My Flags' => 'Мои Подписки',
    'Flag' => 'Подписаться',
    'Unflag' => 'Отписаться',
    'My Topics' => 'Мои темы',
    'Login' => 'Войти',
    'Search' => 'Поиск',
    'Copyright' => 'Права защищены',
    'New Group' => 'Новая Группа',
    'New Topic' => 'Новая тема',
    'Post Reply' => 'Ответить',
    'Lock' => 'Блокировать',
    'Unlock' => 'Разблокировать',
    'Stick' => 'Прикрепить',
    'Unstick' => 'Открепить',
    'Author' => 'Автор',
    'Message' => 'Сообщение',
    'posts:' => 'сообщения:',
    'Delete' => 'Удалить',
    'Edit' => 'Редактировать',
    'Quote' => 'Цитировать',
    'post is hidden' => 'сообщение спрятано',
    'hide post' => 'спрятать сообщение',
    'show post' => 'показать сообщение',
    'Points:' => 'Понравилось:',
    'Vote' => 'Голосовать',
    'Access denied' => 'Доступ запрещен. Вы должны иметь специальные разрешения на доступ к этой области, или вы не вошли в аккаунт.',
    'New topic created' => 'Новая тема была создана',
    'return to forum index' => 'назад к указателю форума',
    'Edit group' => 'Редактировать группу',
    'New group' => 'Новая группа',
    'Cancel' => 'Отменить',
    'Submit' => 'Послать',
    'New forum' => 'Новый форум',
    'Forum title:' => 'Название форума:',
    'Forum description:' => 'Описание форума:',
    'Forum type:' => 'Тип форума:',
    'public' => 'публичный',
    'private' => 'приватный',
    'Latest Reply' => 'Последний ответ',
    'Latest Post' => 'Последнее сообщение',
    'Posts' => 'Сообщения',
    'Pages:' => 'Страницы:',
    'Join' => 'Регистрация',
    'Forums Spy' => 'Форумы Следить <span>(просматривать события в реальном времени)</span>',
    'said in' => 'сказал в',
    'Topic subject:' => 'Название темы:',
    'Topic subject Error' => 'Пожалуйста, введите от 5 до 50 символов',
    'Topic forum Error' => 'Пожалуйста, выберите форум для размещения темы',
    'Select Forum' => 'Выбрать Форум',
    'Sticky' => 'Прикрепленные',
    'Topic text:' => 'Текст темы:',
    'Topic text Error' => 'Пожалуйста, введите от 5 до 128000 символов',
    'Post Reply:' => 'Ответ на сообщение:',
    'Special Member' => 'Особый пользователь',
    'Standard Member' => 'Обычный пользователь',
    'Member Info' => 'Информация о пользователе',
    'Joined:' => 'Зарегистрирован:',
    'Last Online:' => 'Последние в сети:',
    'Posts:' => 'Сообщения:',
    'Last Post:' => 'Последнее сообщение:',
    'never' => 'никогда',
    'Find all posts by' => 'Найти все сообщения по',
    'New Search' => 'Новый поиск',
    'Search Results For:' => 'Резудьтаты поиска для:',
    'There are no search results.' => 'Результатов нет.',
    'Please try search again.' => 'Пожалуйста, <a href="javascript:void(0);" onclick="return f.showSearch()" >попробуйте снова</a>.',
    'Date' => 'Дата',
    'Search The Forum' => 'Поиск по форуму',
    'Search for:' => 'Что искать:',
    'Where to Search:' => 'Где искать:',
    'Topic Titles' => 'Названия тем',
    'Messages' => 'Сообщения',
    'Forum:' => 'Форум:',
    'Whole Forum' => 'Весь Форум',
    'Author:' => 'Автор:',
    'Display:' => 'Отобразить:',

    'Site is unavailable' => 'Извините, что-то пошло не так, и сайт стал недоступен. Пожалуйста, повторите попытку позже.',
    'Join Login Username Error' => 'Имя пользователя должно быть от 4 до 12 символов',
    'Join Email Error' => 'Электронный адрес должен быть действительным',
    'Username must be uniq' => 'Имя пользователя должно быть уникальным',
    'Login Password Error' => 'Пароль должен соответствовать требованиям',
    'Email must be uniq' => 'Электронный адрес должен быть уникальным',
    'Database error' => 'Ошибка базы данных',
    'Send mail failed' => 'Не удалось послать письмо',
    'password or login is incorrect' => 'неправильный пароль или имя',
    'Cookies must be enabled to process login' => 'Куки должны быть включены',

    'Username' => 'Имя пользователя',
    'Password' => 'Пароль',
    'Email' => 'Имейл',
    'Wrong search type' => 'Неверный тип поиска',
    'Topics you participate in' => 'Темы, в которых Вы участвуете',
    'Flagged topics' => 'Отмеченные темы',
    'Topics you have flagged' => 'Темы, отмеченные Вами',
    '%s\'s forum posts' => '%s сообщения',
    'Forum Posts' => 'Cообщения',
    'Minute Ago' => 'Минуту назад',
    'Minutes Ago' => 'Минут назад',
    'Hour Ago' => 'Час назад',
    'Hours Ago' => 'Часов назад',
    'Day Ago' => 'День назад',
    'Days Ago' => 'Дней назад',
    'Mail Subj Registration' => 'Детали регистрации форума',
    'Mail Body Registration' => "
<p>Дорогой {username},</p>

<p>
Ваше имя пользователя: {username} <br />
Ваш пароль: {pwd} <br />
Адрес сайта: {site_url} <br />
</p>

<p>
Спасибо за регистрацию.
</p>
<p>
Всего доброго, Форум.
</p>
",
    'xml serialization failed' => 'xml-сериализация не удалась',
    'please upgrade your browser' => 'пожалуйста, обновите браузер',
    'XML read failed:' => 'Не удалось прочитать XML:',
    'There was a problem retrieving the XML data:' => 'Произошла ошибка при приёме XML-данных:',
    'httpxml object creation failed' => 'не удалось создать httpxml-объект',

    'LOADING LOGIN FORM' => 'ЗАГРУЖАЕТСЯ ФОРМУ ДЛЯ ВХОДА',
    'LOADING JOIN FORM' => 'ЗАГРУЖАЕТСЯ ФОРМУ ДЛЯ РЕГИСТРАЦИИ',
    'SEARCHING' => 'ПОИСК',
    'LOADING FORUMS' => 'ЗАГРУЖАЮТСЯ ФОРУМЫ',
    'LOADING FORUM TOPICS' => 'ЗАГРУЖАЮТСЯ ТЕМЫ',
    'LOADING FORUM INDEX' => 'ЗАГРУЖАЕТСЯ УКАЗАТЕЛЬ',
    'LOADING PROFILE PAGE' => 'ЗАГРУЖАЕТСЯ ПРОФИЛЬ',
    'LOADING TOPIC POSTS' => 'ЗАГРУЖАЮТСЯ СООБЩЕНИЯ',
    'LOADING POST TOPIC PAGE' => 'ЗАГРУЖАЮТСЯ ПОСЛЕДНИЕ СООБЩЕНИЯ',
    'LOADING' => 'ЗАГРУЗКА',
    'LOADING SEARCH PAGE' => 'ЗАГРУЖАЕТСЯ ФОРМА ПОИСКА',
    'LOADING POST REPLY PAGE' => 'ЗАГРУЖАЕТСЯ СТРАНИЦА ОТВЕТОВ',
    'SENDING MESSAGE' => 'ПОСЫЛКА СООБЩЕНИЯ',
    'POST IS LOADING' => 'СООБЩЕНИЕ ЗАГРУЖАЕТСЯ',

    'Thank you! You Joined! Your login and password have been sent to your email.' => 'Спасибо! Вы зарегистрированы! Ваши имя пользователя и пароль были отправлены по электронной почте.',
    'Join failed' => 'Регистрация не удалась',
    'Login failed' => 'Ошибка входа',
    'orca_main div is not defined' => 'элемент orca_main не определен',
    'please name orca_main content container' => 'пожалуйста, озаглавьте контейнер содержимого orca_main',
    'category id is not defined' => 'идентификатор категории не определен',
    'please set category ids' => 'пожалуйста, установите идентификаторы категории',
    'Please login to view topics you participate in' => 'Пожалуйста, войдите, чтобы просмотреть темы, в которых Вы участвуете',
    'Please login to view flagged topics' => 'Пожалуйста, войдите, чтобы просмотреть отмеченные темы',
    'Are you sure ?' => 'Вы уверены?',
    'Post was successfully deleted' => 'Сообщение было успешно удалено',
    'Topic and post were successfully deleted' => 'Тема и сообщение были успешно удалены',
    'Post was successfully edited' => 'Сообщение было успешно изменено',
    'Message body empty' => 'Текст сообщения пустой',
    'Valid chars:' => 'Разрешенные символы:',
    'Topic has been successfully added to your flagged topics' => 'Вы успешно подписались на тему',
    'Topic has been successfully removed from your flagged topics' => 'Тема была успешно удалена из вашей подписки',
    'Please login to flag topics' => 'Пожалуйста, войдите, чтобы подписаться на тему',
    'Post has been reported' => 'Сообщение было отмечено жалобой',
    'Report error' => 'Ошибка жалобы',
    'add this to title' => ' :: Форум ',
    'Are you sure to delete category with all forums, topics and post?' => 'Вы действительно хотите удалить категорию со всеми форумами, темами и сообщениями?',
    'Category has been successfully deleted' => 'Категория была успешно удалена',
    'Can not delete category' => 'Невозможно удалить категорию',
    'Are you sure to delete forum with topics and posts' => 'Вы действительно хотите удалить форум с темами и сообщениями',
    'Forum has been successfully deleted' => 'Форум был удален',
    'Can not delete forum' => 'Невозможно удалить форум',
    'Group has been successfully modified' => 'Группа была изменена',
    'New group has been successfully added' => 'Новая группа была добавлена',
    'Can not modify group' => 'Невозможно изменить группу',
    'Can not add new group' => 'Не удалось добавить новую группу',
    'Forum has been successfully modified' => 'Форум был изменен',
    'New forum has been successfully added' => 'Новый форум был добавлен',
    'Can not modify forum' => 'Невозможно изменить форум',
    'Can not add new forum' => 'Невозможно добавить новый форум',
    'Topic has been successfully locked' => 'Тема была заблокирована',
    'Topic has been successfully unlocked' => 'Тема была разблокирована',
    'Topic has been successfully sticked' => 'Тема была прикреплена',
    'Topic has been successfully un-sticked' => 'Тема была откреплена',
    'Only admin can lock/unlock topics' => 'Только администратор может (раз)блокировать темы',
    'new group' => 'новая группа',
    'edit' => 'редактировать',
    'delete' => 'удалить',
    'new forum' => 'новый форум',
    'permalink' => 'постоянная ссылка',
    'report this post' => 'пожаловаться на сообщение',
    'Compile Langs' => 'Компилировать языки',
    'Compile Lang:' => 'Компилировать язык:',
    'Language files compilation have been failed' => 'Компиляции языковых файлов удалась. Пожалуйста, проверьте разрешения папок.',
    'Language files have been successfully compiled' => 'Языковые файлы были успешно скомпилированы',
    'Permalink' => 'Постоянная ссылка',
    'RSS feed' => 'RSS-канал',
    'RSS Feed' => 'RSS-канал',
    'No topics' => 'В этом форуме нет тем',
    '# forums' => '# форумов',
    '# topics' => '# топиков',
    '# posts' => '# сообщений',
    '# posts num' => '#',
    '# points' => '# людям понравилось',
    'last update: #' => 'последнее изменение: #',
    'last reply by # %' => 'последний ответ от # %',
    'last reply by #' => 'последний ответ от #',
    'created by # %' => 'создано # %',
    'Report' => 'Пожаловаться',
    'Forum order:' => 'Порядок форума:',
    'Group name:' => 'Название группы:',
    'Group order:' => 'Порядок группы:',
    'Expand group by default:' => 'Развернуть группу по умолчанию:',
    'Clear report' => 'Очистить жалобу',
    'Topic has been successfully hidden' => 'Тема была спрятана',
    'Topic has been successfully un-hidden' => 'Тема была показана',
    'Hidden Topics' => 'Спрятанные темы',
    'Hidden Posts' => 'Спрятанные сообщения',
    'Move topic form' => 'Переместить тему из',
    'Move Topic' => 'Переместить тему',
    'Unhide Topic' => 'Показать тему',
    'Hide Topic' => 'Спрятать тему',
    'Delete Topic' => 'Удалить тему',
    'Forum to move topic to:' => 'Переместить тему в форум:',
    'After moving go to:' => 'После перемещения перейти к:',
    'Stay here' => 'Остаться тут',
    'Forum where topic is moved' => 'Форум, куда была перемещена тема',
    'Allowed edit post period is elapsed' => 'Завершен период, в течение которого возможно отредактировать сообщение',
    'Allowed edit post period is # seconds' => 'Период, в течение которого возможно отредактировать сообщение: # секунд',
    'Recent Topics' => 'Последние темы',
    'No posts' => 'Здесь ещё нет сообщений',
    'Attach one more file' => 'Прикрепить еще один файл',
    'Attachments:' => 'Прикрепления:',
    'Some or all files upload failed' => 'Не удалось загрузить один или более файлов',
    '# downloads' => '# завгрузок',
    '# views' => '# просмотров',
    'Hide' => 'Спрятать',
    'Unhide' => 'Показать',
    'Change Signature' => 'Изменить подпись',
    'Signature text Error' => 'Максимально 100 символов',
    'Updated Topics' => 'Обновленные темы',
    'Like' => 'Нравится',
    'Bury' => 'Отстой',
    'Edit forum' => 'Редактировать топик',
    'continue_topic_suffix - %d' => ' - часть %d',
    'continue_topic_last %s' => '<div class="forum_robot_msg bx-def-font">%s &#8594;</div>',
    'continue_topic_first %s' => '<div class="forum_robot_msg bx-def-font">&#8592; %s</div>',
    'insert to post' => 'вставить в сообщение',
);
