<?php

/**
 * Copyright (c) BoonEx Pty Limited - http://www.boonex.com/
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$sLangCategory = 'BooneEx Blogs';

$aLangContent = array(
    '_sys_module_blogs' => 'Блоги',
    '_bx_blog_added_spy' => '<a href="{profile_link}">{profile_nick}</a> добавил новое сообщение <a href="{post_url}">{post_caption}</a>',
    '_bx_blog_rated_spy' => '<a href="{profile_link}">{profile_nick}</a> оценил сообщение <a href="{post_url}">{post_caption}</a>',
    '_bx_blog_commented_spy' => '<a href="{profile_link}">{profile_nick}</a> прокомментировал сообщение <a href="{post_url}">{post_caption}</a>',
    '_bx_blog_Categories' => 'Категории',
    '_bx_blog_Posts' => 'Сообщения',
    '_bx_blog_post' => 'Сообщения блога',
    '_bx_blog_post_view' => 'Посмотреть сообщение',
    '_bx_blog_post_info' => 'Информация о сообщении',
    '_bx_blog_All_Posts' => 'Все сообщения',
    '_bx_blog_Popular_Posts' => 'Популярные сообщения',
    '_bx_blog_Featured_Posts' => 'Избранные сообщения',
    '_bx_blog_Calendar' => 'Календарь сообщений блога',
    '_bx_blog_Blogs_Home' => 'Главная',
    '_bx_blog_msg_access_denied' => 'Доступ запрещен',
    '_bx_blog_pending_approval' => 'Ожидающие решения',
    '_bx_blog_blog_posts' => 'сообщения блога',
    '_bx_blog_stat_adm_stats' => 'ожидающие сообщения блога',
    '_bx_blog_Latest_posts' => 'Последние сообщения',
    '_bx_blog_Top_blog' => 'Самые популярные блоги',
    '_bx_blog_Back_to_Blog' => 'Назад в блог',
    '_bx_blog_single' => 'сообщения блога',
    '_bx_blog_plural' => 'сообщения блога',
    '_bx_blog_caption_browse_by_day' => 'Обзор сообщений блога по дням: ',
    '_bx_blog_Comments_is_disabled' => 'Комментарии отключены',
    '_bx_blog_privacy_comment' => 'Комментарии доступны',
    '_bx_blog_privacy_rate' => 'Голосование доступно',
    '_bx_blog_privacy_view' => 'Просмотр доступен',
    '_bx_blog_Administration' => 'Администрация',
    '_bx_blog_Manage' => 'Управление',
	'_bx_blog_Manage_main' => 'Главная',
    '_bx_blog_admin_box_desc' => 'У Вас {0} <a href="{1}">сообщений в блоге</a>. <a href="{2}">Нажмите здесь</a>, чтобы добавить ещё.',
    '_bx_blog_My_blog' => 'Мой блог',
    '_bx_blog_Members_blog' => 'Блог {0}',
    '_bx_blog_No_blogs_available' => 'Нет доступных блогов',
    '_bx_blog_All_Blogs' => 'Все блоги',
    '_bx_blog_Top_Blogs' => 'Лучшие блоги',
    '_bx_blog_Please_create_blog' => 'Пожалуйста, введите название Вашего блога, прежде чем начать им пользоваться. Вы должны это сделать только один раз.',
    '_bx_blog_description' => 'Коротко опишите свой блог (т.е. \'Мои ежедневные размышления\' или \'Забавные вещицы от Буббы\')',
    '_bx_blog_create_blog_form_error' => 'Описание блога должно быть от 3 до 255 символов длиной',
    '_bx_blog_Post_succ_updated' => 'Сообщение блога успешно обновлено',
    '_bx_blog_Post_fail_updated' => 'Не удалось обновить сообщение блога',
    '_bx_blog_Blogs' => 'Блоги',
    '_bx_blog_Blog' => 'Блог',
    '_bx_blog_My_posts' => 'Мои сообщения',
    '_bx_blog_RSS' => 'RSS',
    '_bx_blog_Edit_blog' => 'Изменить',
    '_bx_blog_Delete_blog' => 'Удалить',
    '_bx_blog_Edit_post' => 'Редактировать сообщение',
    '_bx_blog_Caption_error' => 'пожалуйста, укажите название сообщения (от 3 до 255 символов)',
    '_bx_blog_Text_error' => 'пожалуйста, напишите текст сообщения (от 3 до 65535 символов)',
    '_bx_blog_sbs_comments' => 'Новые комментарии к блогу',
    '_bx_blog_Top_Posts' => 'Лучшие сообщения',
    '_bx_blog_Add' => 'Добавить',
    '_bx_blog_wall_added_new' => 'добавлены новые',
	'_bx_blog_wall_added_new_title' => '{0} добавлены новые {1}',
    '_bx_blog_wall_added_new_items' => 'добавил {0} новое сообщение в блог',
	'_bx_blog_wall_added_new_title_items' => '{0} добавил {1} новое сообщение в блог',
    '_bx_blog_wall_added_new_comment' => 'прокомментировал',
	'_bx_blog_wall_added_new_title_comment' => '{0} прокомментировал {1}',
    '_bx_blog_wall_object' => 'сообщения в блоге',
    '_bx_blog_chart' => 'Сообщения в блоге',
    '_bx_blog_stat' => 'Блог-постов',
	'_wall_reposted_bx_blogs_create' => 'зарепостил блог пост',
	'_wall_reposted_title_bx_blogs_create' => '{0} зарепостил блог пост',
	'_wall_reposted_bx_blogs_comment_add' => 'зарепостил комментарий к блог посту',
	'_wall_reposted_title_bx_blogs_comment_add' => '{0} зарепостил комментарий к блог посту',
    '_sbs_txt_title_bx_blogs' => 'Блоги',
    '_mma_blog_view' => 'Блоги: просматривать',
    '_mma_blog_post_view' => 'Блоги: просматривать сообщения',
    '_mma_blogs_browse' => 'Блоги: обзор',
    '_mma_blogs_posts_browse' => 'Блоги: обзор сообщений',
    '_mma_blog_post_search' => 'Блоги: искать сообщения',
    '_mma_blog_post_add' => 'Блоги: добавлять сообщения',
    '_mma_blog_posts_edit_any_post' => 'Блоги: редактировать любое сообщение',
    '_mma_blog_posts_delete_any_post' => 'Блоги: удалять любое сообщение',
    '_mma_blog_posts_approving' => 'Блоги: одобрять сообщения',
    '_mma_blog_posts_comments_delete_and_edit' => 'Блоги: удалять и редактировать комментарии',
);
