<?php

$aLangContent = array(

  // ================ ADDED KEYS ==================

  '_payment_2co_cpt' => '2Checkout',
  '_payment_2co_dsc' => '2Checkout payment provider',
  '_payment_bcpt_cart_common' => 'Members\' Carts',
  '_payment_bcpt_cart_featured' => 'Site Cart',
  '_payment_bcpt_cart_history' => 'Cart History',
  '_payment_bcpt_details' => 'Payment Details',
  '_payment_bcpt_join' => 'Join',
  '_payment_bcpt_payment_result' => 'Payment Result',
  '_payment_bcpt_pending_orders' => 'Pending Orders',
  '_payment_bcpt_processed_orders' => 'Processed Orders',
  '_payment_bcpt_settings' => 'Payment Settings',
  '_payment_bp_active_cpt' => 'Active',
  '_payment_bp_active_dsc' => 'Activate(Deactivate) provider',
  '_payment_bp_api_key_cpt' => 'API Key',
  '_payment_bp_api_key_dsc' => 'Your merchant BitPay API Access key',
  '_payment_bp_cpt' => 'BitPay',
  '_payment_bp_dsc' => 'BitPay payment provider',
  '_payment_bp_err_already_processed' => 'This payment has already processed.',
  '_payment_bp_err_incorrect_data' => 'Incorrect order data.',
  '_payment_bp_err_no_confirmation_given' => 'Payment is waiting for full confirmation from the Bitcoin network.',
  '_payment_bp_err_no_data_given' => 'No data given.',
  '_payment_bp_err_no_vendor_given' => 'Unknown vendor.',
  '_payment_bp_err_posdata_exceed_limit' => 'The value of posData exceeds limit. Contact with administrator.',
  '_payment_bp_err_wrong_amount' => 'Wrong payment amount.',
  '_payment_bp_full_notifications_cpt' => 'Enable full notifications',
  '_payment_bp_full_notifications_dsc' => 'When enabled notifications will be sent on every status change, otherwise when an invoice is confirmed only.',
  '_payment_bp_msg_checkout_finished' => 'A payment has been confirmed. Once the transaction is fully confirmed on the Bitcoin network, the payment will be processed automatically here. Then the purchased product(s) will be displayed in shopping cart history.<br /><b>Note.</b> If it doesn\'t happen for some reason, you need to contact with product\'s vendor and provide him with your payment\'s details. He\'ll be able to process payment manually if the payment was received.',
  '_payment_bp_notification_email_cpt' => 'Notification Email',
  '_payment_bp_notification_email_dsc' => 'Email where invoice update notifications will be sent. Leave empty to disable.',
  '_payment_bp_transaction_speed_cpt' => 'Transaction speed',
  '_payment_bp_transaction_speed_dsc' => 'Determines when an invoice is confirmed',
  '_payment_bp_transaction_speed_high' => 'High',
  '_payment_bp_transaction_speed_low' => 'Low',
  '_payment_bp_transaction_speed_medium' => 'Medium',
  '_payment_err_already_processed' => 'This payment has been already processed.',
  '_payment_err_not_allowed' => 'Action is not allowed',
  '_payment_err_not_processed' => 'This payment was not processed.',
  '_payment_fcpt_client' => 'Client',
  '_payment_fcpt_module' => 'Items from',
  '_payment_fcpt_order' => 'Order',
  '_payment_ocpt_select' => 'Select one',
  '_payment_pcpt_admin' => 'Payment',
  '_payment_pcpt_cart_history' => 'Cart History',
  '_payment_pcpt_details' => 'Payment Details',
  '_payment_pcpt_join' => 'Join',
  '_payment_pcpt_payment_result' => 'Payment Result',
  '_payment_pcpt_view_cart' => 'Shopping cart',
  '_payment_pcpt_view_orders' => 'Order Administration',
  '_payment_pp_cpt' => 'PayPal',
  '_payment_pp_dsc' => 'PayPal payment provider',
  '_payment_txt_add_to_cart' => 'Add to Cart',
  '_payment_txt_buyer_name_mask' => '{0} {1}',
  '_payment_txt_cart_2checkout' => '2Checkout',
  '_payment_txt_cart_bitpay' => 'BitPay',
  '_payment_txt_cart_paypal' => 'PayPal',
  '_payment_wcpt_manual_order' => 'Manual Order',
  '_payment_wcpt_order_info' => 'Order Info',

  // ================ DELETED KEYS ==================

  /*
  '_payment_2co_payment_method_al' => 'Acculynk PIN-debit(AL)',
  '_payment_2co_payment_method_ck' => 'Check(CK)',
  '_payment_add_to_cart' => 'Add to Cart',
  '_payment_bcaption_cart_common' => 'Members\' Carts',
  '_payment_bcaption_cart_featured' => 'Site Cart',
  '_payment_bcaption_cart_history' => 'Cart History',
  '_payment_bcaption_details' => 'Payment Details',
  '_payment_bcaption_payment_result' => 'Payment Result',
  '_payment_bcaption_pending_orders' => 'Pending Orders',
  '_payment_bcaption_processed_orders' => 'Processed Orders',
  '_payment_bcaption_settings' => 'Payment Settings',
  '_payment_err_self_purchase' => 'Cannot sell to yourself',
  '_payment_fldcaption_client' => 'Client',
  '_payment_fldcaption_module' => 'Items from',
  '_payment_fldcaption_order' => 'Order',
  '_payment_ocaption_select' => 'Select one',
  '_payment_pcaption_admin' => 'Payment',
  '_payment_pcaption_cart_history' => 'Cart History',
  '_payment_pcaption_details' => 'Payment Details',
  '_payment_pcaption_payment_result' => 'Payment Result',
  '_payment_pcaption_view_cart' => 'Shopping cart',
  '_payment_pcaption_view_orders' => 'Order Administration',
  '_payment_tbar_item_caption' => 'Shopping Cart',
  '_payment_tbar_item_description' => 'Shopping Cart',
  '_payment_tmenu_cart' => 'Cart',
  '_payment_tmenu_payments' => 'Payments',
  '_payment_txt_empty' => 'empty',
  '_payment_wcaption_manual_order' => 'Manual Order',
  '_payment_wcaption_order_info' => 'Order Info',
  */

);
