<?php
/**
 * Copyright (c) BoonEx Pty Limited - http://www.boonex.com/
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
    '_sys_module_profile_customize' => 'Настройка профиля',
    '_bx_profile_customize' => 'Настройка профиля',
    '_bx_profile_customize_page_themes' => 'Темы',
    '_bx_profile_customize_page_background' => 'Фон',
    '_bx_profile_customize_page_font' => 'Шрифты',
    '_bx_profile_customize_page_border' => 'Границы',
    '_bx_profile_customize_page_themes_my' => 'Мои темы',
    '_bx_profile_customize_page_themes_shared' => 'Общие темы',
    '_bx_profile_customize_page_import' => 'Импорт',
    '_bx_profile_customize_theme' => 'Тема',
    '_bx_profile_customize_btn_save' => 'Сохранить',
    '_bx_profile_customize_btn_add' => 'Добавить',
    '_bx_profile_customize_btn_preview' => 'Предварительный просмотр',
    '_bx_profile_customize_btn_reset' => 'Сбросить',
    '_bx_profile_customize_btn_reset_all' => 'Сбросить страницу',
    '_bx_profile_customize_btn_publish' => 'Публикация',
    '_bx_profile_customize_btn_close' => 'Закрыть',
    '_bx_profile_customize_btn_delete' => 'Удалить',
    '_bx_profile_customize_btn_export' => 'Экспорт',
    '_bx_profile_customize_btn_import' => 'Импорт',

    '_bx_profile_customize_color' => 'Цвет',
    '_bx_profile_customize_use_image' => 'Использовать изображение',
    '_bx_profile_customize_image' => 'Изображение',
    '_bx_profile_customize_repeat' => 'Повторить',
    '_bx_profile_customize_position' => 'Позиция',
    '_bx_profile_customize_size' => 'Размер',
    '_bx_profile_customize_name' => 'Название',
    '_bx_profile_customize_style' => 'Стиль',
    '_bx_profile_customize_no' => 'Нет',
    '_bx_profile_customize_repeat_x' => 'Повторить по X',
    '_bx_profile_customize_repeat_y' => 'Повторить по Y',
    '_bx_profile_customize_none' => 'Ничего',
    '_bx_profile_customize_top_left' => 'По верхнему и левому краю',
    '_bx_profile_customize_top_center' => 'По верхнему краю и центру',
    '_bx_profile_customize_top_right' => 'По верхнему и правому краю',
    '_bx_profile_customize_center_left' => 'По центру и левому краю',
    '_bx_profile_customize_center' => 'По центру',
    '_bx_profile_customize_center_right' => 'По центру и правому краю',
    '_bx_profile_customize_bottom_left' => 'По нижнему и левому краю',
    '_bx_profile_customize_bottom_center' => 'По нижнему краю и центру',
    '_bx_profile_customize_bottom_right' => 'По нижнему и правому краю',
    '_bx_profile_customize_default' => 'По умолчанию',
    '_bx_profile_customize_normal' => 'Обычный',
    '_bx_profile_customize_bold' => 'Жирный',
    '_bx_profile_customize_italic' => 'Наклонный',
    '_bx_profile_customize_dotted' => 'Пунктирное',
    '_bx_profile_customize_dashed' => 'Штриховое',
    '_bx_profile_customize_solid' => 'Подчеркивание',
    '_bx_profile_customize_double' => 'Двойное',
    '_bx_profile_customize_groove' => 'Groove',
    '_bx_profile_customize_ridge' => 'Волнистое',
    '_bx_profile_customize_inset' => 'Вдавлено',
    '_bx_profile_customize_outset' => 'Выступ',
    '_bx_profile_customize_select_target' => 'Выбрать',
    '_bx_profile_customize_border_full' => 'Полный',
    '_bx_profile_customize_border_top' => 'Сверху',
    '_bx_profile_customize_border_right' => 'Справа',
    '_bx_profile_customize_border_bottom' => 'Снизу',
    '_bx_profile_customize_border_left' => 'Слева',
    '_bx_profile_customize_border_left_right' => 'Справа и сверху',
    '_bx_profile_customize_border_top_bottom' => 'Сверху и снизу',
    '_bx_profile_customize_border_top_right' => 'Сверху и справа',
    '_bx_profile_customize_border_right_bottom' => 'Справа и снизу',
    '_bx_profile_customize_border_bottom_left' => 'Снизу и слева',
    '_bx_profile_customize_border_left_top' => 'Слева и сверху',
    '_bx_profile_customize_caption' => 'Заголовок',
    '_bx_profile_customize_css_name' => 'Имя CSS',
    '_bx_profile_customize_type' => 'Тип',

    '_bx_profile_customize_publish' => 'Публикация новой темы',
    '_bx_profile_customize_name_theme' => 'Название',
    '_bx_profile_customize_thumbnail' => 'Миниатюра (64x64)',
    '_bx_profile_customize_destination' => 'Назначение',
    '_bx_profile_customize_err_add_theme' => 'Ошибка при создании новой темы.',
    '_bx_profile_customize_err_already_exist' => 'Тема с названием "%s" уже существует',
    '_bx_profile_customize_complete' => 'Новая тема создана успешно!',
    '_bx_profile_customize_import_complete' => 'Новая тема импортированы успешно!',
    '_bx_profile_customize_delete_complete' => 'Тема успешно удалена',
    '_bx_profile_customize_edit' => 'Редактировать',
    '_bx_profile_customize_form_edit' => 'Изменить запись',
    '_bx_profile_customize_form_add' => 'Добавить запись',
    '_bx_profile_customize_units' => 'Записи',
    '_bx_profile_customize_other_image' => 'Другое изображение',
    '_bx_profile_customize_err_conf_php' => 'Файл "%s" не найден',
    '_bx_profile_customize_err_theme_parameters' => 'Ошибка в параметрах темы',
    '_bx_profile_customize_err_delete_theme' => 'Ошибка удаления темы',
    '_bx_profile_customize_err_format' => 'Неверный формат файла',

    '_bx_profile_customize_administration' => 'Настройка профиля',
    '_bx_profile_customize_form_field_err' => 'Неверное значение',

    '_bx_profile_customize_js_reset' => 'Сбросить?',
    '_bx_profile_customize_js_err_theme_name' => 'Пожалуйста, заполните название темы',
    '_bx_profile_customize_js_err_choose_theme' => 'Выберите любую тему',
    '_bx_profile_customize_js_delete_theme' => 'Удалить тему?',
    '_bx_profile_customize_js_reset_page' => 'Сбросить страницу?',
);
