<?php
/**
 * Copyright (c) BoonEx Pty Limited - http://www.boonex.com/
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
  '_sys_module_poll' => 'Poll',
  '_bx_poll' => 'Poll',
  '_bx_poll_PH' => 'Members Polls',
  '_bx_poll_access_denied' => 'Access denied',
  '_bx_poll_actions' => 'Actions',
  '_bx_poll_active' => 'Active poll',
  '_bx_poll_add' => 'Add Poll',
  '_bx_poll_added' => '<a href="{profile_link}">{profile_nick}</a> added a new poll <a href="{poll_url}">{poll_caption}</a>',
  '_bx_poll_administration' => 'Administration',
  '_bx_poll_all' => 'All Polls',
  '_bx_poll_allow_comment' => 'Choose the group where members are able to comment on your polls',
  '_bx_poll_allow_view' => 'Choose members allowed to view this poll',
  '_bx_poll_allow_vote' => 'Choose members allowed to vote on your polls',
  '_bx_poll_answer' => 'Answer',
  '_bx_poll_answer_length_required' => 'the answers must be from {0} to {1} characters in length, and you must answer more than one question',
  '_bx_poll_answered' => '<a href="{recipient_p_link}">{recipient_p_nick}\'s</a> <a href="{poll_link}">poll</a> was answered by <a href="{profile_link}">{profile_nick}</a>',
  '_bx_poll_approve' => 'Approve',
  '_bx_poll_approved' => 'Approved',
  '_bx_poll_browse_by_day' => 'Browse polls by day',
  '_bx_poll_browse_category' => 'Browse polls by category',
  '_bx_poll_browse_tag' => 'Browse polls by tag',
  '_bx_poll_by' => 'By',
  '_bx_poll_calendar' => 'Calendar',
  '_bx_poll_categories' => 'Categories',
  '_bx_poll_close' => 'Close',
  '_bx_poll_commented' => '<a href="{recipient_p_link}">{recipient_p_nick}\'s</a> <a href="{poll_link}">poll</a> was commented on by <a href="{profile_link}">{profile_nick}</a>',
  '_bx_poll_comments' => 'Comments',
  '_bx_poll_create' => 'Create poll',
  '_bx_poll_created' => 'Poll was created',
  '_bx_poll_delete' => 'Delete',
  '_bx_poll_disapprove' => 'Disapprove',
  '_bx_poll_edit' => 'Edit',
  '_bx_poll_edit_poll' => 'Edit poll',
  '_bx_poll_featured' => 'Featured',
  '_bx_poll_featured_polls' => 'Featured',
  '_bx_poll_generate' => 'Create',
  '_bx_poll_have_not_approval' => 'You have {0} unapproved polls',
  '_bx_poll_home' => 'Polls Home',
  '_bx_poll_item_not_found' => 'Poll not found',
  '_bx_poll_keyword' => 'poll,opinion,diagram',
  '_bx_poll_latest' => 'Latest polls',
  '_bx_poll_latest_public' => 'Latest public polls',
  '_bx_poll_loading' => 'loading',
  '_bx_poll_main' => 'Main',
  '_bx_poll_make_it' => 'make it',
  '_bx_poll_manage' => 'Manage',
  '_bx_poll_manage_poll' => 'Manage poll',
  '_bx_poll_max_reached' => 'Maximum number of allowed polls reached',
  '_bx_poll_moderation' => 'Polls Post Moderation',
  '_bx_poll_module' => 'Polls',
  '_bx_poll_my' => 'My Polls',
  '_bx_poll_not_available' => 'Poll not available',
  '_bx_poll_owner' => 'Information',
  '_bx_poll_pending' => 'Pending approval',
  '_bx_poll_pending_poll' => 'View pending',
  '_bx_poll_popular' => 'Popular',
  '_bx_poll_popular_polls' => 'Popular polls',
  '_bx_poll_privacy_comment_error' => 'The recipient\'s privacy settings don\'t allow you to leave comments',
  '_bx_poll_privacy_vote_error' => 'The recipient\'s privacy settings don\'t allow you to vote',
  '_bx_poll_private' => 'Private poll',
  '_bx_poll_question' => 'Question',
  '_bx_poll_question_length_required' => 'question length must be from {0} to {1} characters',
  '_bx_poll_rated' => '<a href="{recipient_p_link}">{recipient_p_nick}\'s</a> <a href="{poll_link}">poll</a> was rated by <a href="{profile_link}">{profile_nick}</a>',
  '_bx_poll_result' => 'Result',
  '_bx_poll_save' => 'Save',
  '_bx_poll_sbs_comment' => 'New Poll Comments',
  '_bx_poll_search' => 'Search',
  '_bx_poll_select_all' => 'Select all',
  '_bx_poll_settings' => 'Settings',
  '_bx_poll_specify_least' => 'You should specify at least one member',
  '_bx_poll_tags' => 'Tags',
  '_bx_poll_tags_premoderation' => 'Polls',
  '_bx_poll_tags_separeted' => 'Enter a few words delimited by commas or semicolon',
  '_bx_poll_unapproved' => 'Unapproved',
  '_bx_poll_unfeatured' => 'Unfeatured',
  '_bx_poll_view' => 'Poll: {0}',
  '_bx_poll_view_category' => 'View by category',
  '_bx_poll_view_tag' => 'View by tag',
  '_bx_poll_votings' => 'Votes',
  '_bx_poll_wall_added_new' => 'added new',
  '_bx_poll_wall_added_new_title' => '{0} added new {1}',
  '_bx_poll_wall_added_new_comment' => 'commented on a',
  '_bx_poll_wall_added_new_title_comment' => '{0} commented on a {1}',
  '_bx_poll_wall_object' => 'poll',
  '_bx_poll_was_deleted' => 'Poll successfully deleted',
  '_bx_poll_was_edited' => 'Poll successfully edited',
  '_bx_polls' => 'Polls',
  '_bx_polls_adm_stats' => 'Pending Polls',
  '_bx_polls_profile' => 'Profile\'s polls',
  '_bx_polls_public' => 'Public polls',
  '_mma_create_polls' => 'create polls',
  '_wall_reposted_bx_poll_add' => 'reposted a poll',
  '_wall_reposted_title_bx_poll_add' => '{0} reposted a poll',
  '_wall_reposted_bx_poll_comment_add' => 'reposted a poll comment',
  '_wall_reposted_title_bx_poll_comment_add' => '{0} reposted a poll comment',
  '_sbs_txt_title_bx_poll' => 'Poll',
);
