<?php
/**
 * Copyright (c) BoonEx Pty Limited - http://www.boonex.com/
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
  '_sys_module_feedback' => 'Feedback',

  '_feedback' => 'Feedback',
  '_feedback_actions_delete' => 'Delete',
  '_feedback_admin_menu_sitem' => 'Feedback',
  '_feedback_bcaption_all_tags' => 'All Tags',
  '_feedback_bcaption_index' => 'Feedback',
  '_feedback_bcaption_post' => 'Post Feedback',
  '_feedback_bcaption_settings' => 'Settings',
  '_feedback_bcaption_tag' => 'Tag: {0}',
  '_feedback_bcaption_tags' => 'Tags',
  '_feedback_bcaption_view_action' => 'Actions',
  '_feedback_bcaption_view_admin' => 'Feedback',
  '_feedback_bcaption_view_all' => 'Feedback',
  '_feedback_bcaption_view_comment' => 'Comments',
  '_feedback_bcaption_view_main' => 'Feedback',
  '_feedback_bcaption_view_my' => 'My Feedback',
  '_feedback_bcaption_view_vote' => 'Rating',
  '_feedback_chart' => 'Feedback',
  '_feedback_lcaption_approve' => 'Approve',
  '_feedback_lcaption_delete' => 'Delete',
  '_feedback_lcaption_edit' => 'Edit',
  '_feedback_lcaption_post' => 'Post my feedback',
  '_feedback_lcaption_reject' => 'Reject',
  '_feedback_lcaption_search_object' => 'Feedback',
  '_feedback_lcaption_tags_object' => 'Feedback',
  '_feedback_msg_failed_delete' => 'Cannot delete feedback. Check if you have the necessary permissions to do it.',
  '_feedback_msg_no_results' => 'Empty',
  '_feedback_msg_success_delete' => 'Feedback was deleted successfully.',
  '_feedback_pcaption_admin' => 'Feedback',
  '_feedback_pcaption_all' => 'Feedback',
  '_feedback_pcaption_post' => 'Feedback',
  '_feedback_pcaption_tag' => 'Tag: {0}',
  '_feedback_pcaption_tags' => 'Tags',
  '_feedback_psaction_comment' => 'Comment',
  '_feedback_psaction_vote' => 'Vote',
  '_feedback_sbs_commentPost' => '{0} (New Feedback Comments)',
  '_feedback_sbs_main' => '{0}',
  '_feedback_sitemap' => 'Feedback',
  '_feedback_ss' => 'Feedback Posts',
  '_feedback_ss_adm_stats' => 'Pending Feedback Posts',
  '_feedback_status_0' => 'approved',
  '_feedback_status_1' => 'approval',
  '_feedback_status_2' => 'rejected',
  '_feedback_top_menu_item' => 'Feedback',
  '_feedback_top_menu_sitem' => 'Feedback',
  '_sbs_txt_title_bx_feedback' => 'Feedback',
  '_mma_Feedback_Delete' => 'feedback delete',
);
