<?php
/**
 * Copyright (c) BoonEx Pty Limited - http://www.boonex.com/
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
  '_sys_module_feedback' => 'Отзывы',

  '_feedback' => 'Отзывы',
  '_feedback_actions_delete' => 'Удалить',
  '_feedback_admin_menu_sitem' => 'Отзывы',
  '_feedback_bcaption_all_tags' => 'Все теги',
  '_feedback_bcaption_index' => 'Отзывы',
  '_feedback_bcaption_post' => 'Оставить отзыв',
  '_feedback_bcaption_settings' => 'Настройки',
  '_feedback_bcaption_tag' => 'Тег: {0}',
  '_feedback_bcaption_tags' => 'Теги',
  '_feedback_bcaption_view_action' => 'Действия',
  '_feedback_bcaption_view_admin' => 'Отзывы',
  '_feedback_bcaption_view_all' => 'Отзывы',
  '_feedback_bcaption_view_comment' => 'Комментарии',
  '_feedback_bcaption_view_main' => 'Отзывы',
  '_feedback_bcaption_view_my' => 'Мои отзывы',
  '_feedback_bcaption_view_vote' => 'Рейтинг',
  '_feedback_chart' => 'Отзывы',
  '_feedback_lcaption_approve' => 'Одобрить',
  '_feedback_lcaption_delete' => 'Удалить',
  '_feedback_lcaption_edit' => 'Изменить',
  '_feedback_lcaption_post' => 'Оставить отзыв',
  '_feedback_lcaption_reject' => 'Отклонить',
  '_feedback_lcaption_search_object' => 'Отзывы',
  '_feedback_lcaption_tags_object' => 'Отзывы',
  '_feedback_msg_failed_delete' => 'Невозможно удалить отзыв. Проверьте, если у вас есть необходимые разрешения на это.',
  '_feedback_msg_no_results' => 'Пусто',
  '_feedback_msg_success_delete' => 'Отзыв был успешно удалён.',
  '_feedback_pcaption_admin' => 'Отзывы',
  '_feedback_pcaption_all' => 'Отзывы',
  '_feedback_pcaption_post' => 'Отзыв',
  '_feedback_pcaption_tag' => 'Тег: {0}',
  '_feedback_pcaption_tags' => 'Теги',
  '_feedback_psaction_comment' => 'Комментарии доступны',
  '_feedback_psaction_vote' => 'Голосование доступно',
  '_feedback_sbs_commentPost' => '{0} (Новых комментариев к отзыву)',
  '_feedback_sbs_main' => '{0}',
  '_feedback_sitemap' => 'Отзывы',
  '_feedback_ss' => 'Отзывов',
  '_feedback_ss_adm_stats' => 'Ожидающие отзывы',
  '_feedback_status_0' => 'одобрен',
  '_feedback_status_1' => 'ожидает',
  '_feedback_status_2' => 'отклонён',
  '_feedback_top_menu_item' => 'Отзывы',
  '_feedback_top_menu_sitem' => 'Отзывы',
  '_sbs_txt_title_bx_feedback' => 'Отзывы',
  '_mma_Feedback_Delete' => 'Отзывы: удалять',
);
