<?php

$aLangContent = array(

  // ================ CHANGED KEYS ==================

  '_bx_photos_action_feature' => 'В избранное',
  '_bx_photos_action_share' => 'Поделиться',
  '_bx_photos_action_unfeature' => 'Не избранное',
  '_bx_photos_add' => 'Добавить фото',
  '_bx_photos_add_objects' => 'Добавить фото',
  '_bx_photos_adm_stats' => 'Ожидающие фото',
  '_bx_photos_admin_feature' => 'В избранное',
  '_bx_photos_admin_unfeature' => 'Не избранное',
  '_bx_photos_album_add_objects' => 'Добавить фото',
  '_bx_photos_album_disapproved' => 'Отклоненное',
  '_bx_photos_album_manage_objects' => 'Управление фото',
  '_bx_photos_album_manage_objects_disapproved' => 'отклоненное',
  '_bx_photos_album_manage_objects_pending' => 'ожидающее',
  '_bx_photos_album_objects' => 'фото в этом альбоме',
  '_bx_photos_album_photos_rest' => 'Фото из этого альбома',
  '_bx_photos_album_view' => 'Просмотр доступен',
  '_bx_photos_albums_disapproved' => 'Мои отклоненные альбомы',
  '_bx_photos_albums_my' => 'Мои альбомы',
  '_bx_photos_alert_commented' => '{0} прокомментировал Ваше фото',
  '_bx_photos_all' => 'Все фото',
  '_bx_photos_approved' => 'Активное',
  '_bx_photos_bcaption_all' => 'Все фото',
  '_bx_photos_browse_by_album' => 'Просмотр фото из альбома "{0}"',
  '_bx_photos_browse_by_category' => 'Просмотр фото по категории "{0}"',
  '_bx_photos_browse_by_owner' => 'Просмотр фото от {0}',
  '_bx_photos_browse_by_tag' => 'Просмотр фото по тегу "{0}"',
  '_bx_photos_count_info' => 'У Вас {0} <a href="{1}">фото</a> в этом альбоме.',
  '_bx_photos_count_status_info' => 'У Вас {0} <a href="{1}">{2} фото</a> в этом альбоме.',
  '_bx_photos_couple_photo_block' => 'Парные фото',
  '_bx_photos_delete' => 'Фото было удалено',
  '_bx_photos_disapproved' => 'Отклоненное',
  '_bx_photos_distribute' => 'Условия распространения фото',
  '_bx_photos_favorited' => 'Понравившиеся фото',
  '_bx_photos_featured' => 'Избранные фото',
  '_bx_photos_file_not_found' => 'Фото не найдено',
  '_bx_photos_i_have_the_right_to_distribute' => 'У меня есть право выкладывать это фото',
  '_bx_photos_latest' => 'Последние фото от этого пользователя',
  '_bx_photos_latest_file' => 'Последние избранные фото',
  '_bx_photos_menu_profile' => 'Фото',
  '_bx_photos_my' => 'Мои фото',
  '_bx_photos_pending' => 'Ожидающее',
  '_bx_photos_photo_album_block' => 'Фото',
  '_bx_photos_photo_block' => 'Фото',
  '_bx_photos_photo_switcher_block' => 'Переключатель фото',
  '_bx_photos_plural' => 'фото',
  '_bx_photos_profile_album_name' => 'фото',
  '_bx_photos_public' => 'Фото',
  '_bx_photos_related' => 'Похожие фото',
  '_bx_photos_single' => 'фото',
  '_bx_photos_spy_added' => '<a href="{profile_link}">{profile_nick}</a> добавил новое фото <a href="{entry_url}">{entry_caption}</a>',
  '_bx_photos_spy_comment_posted' => '<a href="{recipient_p_link}">{recipient_p_nick}</a> <a href="{entry_url}">фото</a> было прокомментировано <a href="{profile_link}">{profile_nick}</a>',
  '_bx_photos_spy_rated' => '<a href="{recipient_p_link}">{recipient_p_nick}</a> <a href="{entry_url}">фото</a> было оценено <a href="{profile_link}">{profile_nick}</a>',
  '_bx_photos_top' => 'Лучшие фото',
  '_bx_photos_upload' => 'Фото',
  '_bx_photos_upload_instance' => 'Загрузить фото',
  '_bx_photos_view' => 'Просмотр фото',
  '_bx_photos_wall_added_new_items' => 'добавил {0} новых фото в альбом',
  '_bx_photos_wall_object' => 'фото',
  '_bx_photos_wall_photo_private' => 'закрытое фото',

);
