<?php
/**
 * Copyright (c) BoonEx Pty Limited - http://www.boonex.com/
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
    '_sys_module_site_customize' => 'Site Customizer',
    '_bx_sctr' => 'Site Customizer',
	'_bx_sctr_mmenu_item_description' => 'Customize site layout',
    '_bx_sctr_page_themes' => 'Themes',
    '_bx_sctr_page_background' => 'Background',
    '_bx_sctr_page_font' => 'Fonts',
    '_bx_sctr_page_border' => 'Borders',
    '_bx_sctr_page_themes_my' => 'My themes',
    '_bx_sctr_page_themes_shared' => 'Shared themes',
    '_bx_sctr_page_import' => 'Import',
    '_bx_sctr_theme' => 'Theme',
    '_bx_sctr_btn_save' => 'Save',
    '_bx_sctr_btn_add' => 'Add',
    '_bx_sctr_btn_preview' => 'Preview',
    '_bx_sctr_btn_reset' => 'Reset',
    '_bx_sctr_btn_reset_all' => 'Default',
    '_bx_sctr_btn_publish' => 'Publish',
    '_bx_sctr_btn_close' => 'Close',
    '_bx_sctr_btn_delete' => 'Delete',
    '_bx_sctr_btn_export' => 'Export',
    '_bx_sctr_btn_import' => 'Import',

    '_bx_sctr_color' => 'Color',
    '_bx_sctr_use_image' => 'Use image',
    '_bx_sctr_image' => 'Image',
    '_bx_sctr_repeat' => 'Repeat',
    '_bx_sctr_position' => 'Position',
    '_bx_sctr_size' => 'Size',
    '_bx_sctr_name' => 'Name',
    '_bx_sctr_style' => 'Style',
    '_bx_sctr_no' => 'No',
    '_bx_sctr_repeat_x' => 'Repeat X',
    '_bx_sctr_repeat_y' => 'Repeat Y',
    '_bx_sctr_none' => 'None',
    '_bx_sctr_top_left' => 'Top Left',
    '_bx_sctr_top_center' => 'Top Center',
    '_bx_sctr_top_right' => 'Top Right',
    '_bx_sctr_center_left' => 'Center Left',
    '_bx_sctr_center' => 'Center',
    '_bx_sctr_center_right' => 'Center Right',
    '_bx_sctr_bottom_left' => 'Bottom Left',
    '_bx_sctr_bottom_center' => 'Bottom Center',
    '_bx_sctr_bottom_right' => 'Bottom Right',
    '_bx_sctr_default' => 'Default',
    '_bx_sctr_normal' => 'Normal',
    '_bx_sctr_bold' => 'Bold',
    '_bx_sctr_italic' => 'Italic',
    '_bx_sctr_dotted' => 'Dotted',
    '_bx_sctr_dashed' => 'Dashed',
    '_bx_sctr_solid' => 'Solid',
    '_bx_sctr_double' => 'Double',
    '_bx_sctr_groove' => 'Groove',
    '_bx_sctr_ridge' => 'Ridge',
    '_bx_sctr_inset' => 'Inset',
    '_bx_sctr_outset' => 'Outset',
    '_bx_sctr_select_target' => 'Select',
    '_bx_sctr_border_full' => 'Full',
    '_bx_sctr_border_top' => 'Top',
    '_bx_sctr_border_right' => 'Right',
    '_bx_sctr_border_bottom' => 'Bottom',
    '_bx_sctr_border_left' => 'Left',
    '_bx_sctr_border_left_right' => 'Left right',
    '_bx_sctr_border_top_bottom' => 'Top bottom',
    '_bx_sctr_border_top_right' => 'Top right',
    '_bx_sctr_border_right_bottom' => 'Right bottom',
    '_bx_sctr_border_bottom_left' => 'Bottom left',
    '_bx_sctr_border_left_top' => 'Left top',
    '_bx_sctr_caption' => 'Caption',
    '_bx_sctr_css_name' => 'Name of css',
    '_bx_sctr_type' => 'Type',

    '_bx_sctr_publish' => 'Publish new theme',
    '_bx_sctr_name_theme' => 'Name',
    '_bx_sctr_thumbnail' => 'Thumbnail(64x64)',
    '_bx_sctr_err_add_theme' => 'Error creating new theme.',
    '_bx_sctr_err_already_exist' => 'A theme with name "%s" already exists',
    '_bx_sctr_complete' => 'New theme created successfully!',
    '_bx_sctr_import_complete' => 'New theme imported successfully!',
    '_bx_sctr_delete_complete' => 'Theme successfully deleted',
    '_bx_sctr_edit' => 'Edit',
    '_bx_sctr_form_edit' => 'Edit Entry',
    '_bx_sctr_form_add' => 'Add Entry',
    '_bx_sctr_units' => 'Entries',
    '_bx_sctr_other_image' => 'Other image',
    '_bx_sctr_err_conf_php' => 'File "%s" not found',
    '_bx_sctr_err_theme_parameters' => 'Error theme parameters',
    '_bx_sctr_err_delete_theme' => 'Error delete theme',
    '_bx_sctr_err_format' => 'Invalid file format',

    '_bx_sctr_administration' => 'Site Customizer',
    '_bx_sctr_form_field_err' => 'Incorrect value',

    '_bx_sctr_js_reset' => 'Reset preview?',
    '_bx_sctr_js_err_theme_name' => 'Please fill in name of theme',
    '_bx_sctr_js_err_choose_theme' => 'Choose any theme',
    '_bx_sctr_js_delete_theme' => 'Delete theme?',
    '_bx_sctr_js_reset_page' => 'Do you want to reset to default?',
);
