<?php
/**
 * Copyright (c) BoonEx Pty Limited - http://www.boonex.com/
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
  '_sys_module_articles' => 'Articles',

  '_articles' => 'Articles',
  '_articles_actions_delete' => 'Delete',
  '_articles_admin_menu_sitem' => 'Articles',
  '_articles_archive_top_menu_sitem' => 'Articles Archive',
  '_articles_bcaption_all' => 'Articles',
  '_articles_bcaption_all_tags' => 'All Tags',
  '_articles_bcaption_archive' => 'Articles Archive',
  '_articles_bcaption_calendar' => 'Calendar',
  '_articles_bcaption_calendar_browse' => 'Browse articles by day',
  '_articles_bcaption_categories' => 'Categories',
  '_articles_bcaption_category' => 'Category: {0}',
  '_articles_bcaption_featured' => 'Featured Articles',
  '_articles_bcaption_latest' => 'Latest Articles',
  '_articles_bcaption_member' => 'Latest Articles',
  '_articles_bcaption_popular' => 'Popular Articles',
  '_articles_bcaption_post' => 'Post Article',
  '_articles_bcaption_settings' => 'Settings',
  '_articles_bcaption_tag' => 'Tag: {0}',
  '_articles_bcaption_tags' => 'Tags',
  '_articles_bcaption_top_rated' => 'Top Rated Articles',
  '_articles_bcaption_view_action' => 'Actions',
  '_articles_bcaption_view_comment' => 'Comments',
  '_articles_bcaption_view_info' => 'Info',
  '_articles_bcaption_view_main' => 'Article',
  '_articles_bcaption_view_vote' => 'Rating',
  '_articles_calendar_top_menu_sitem' => 'Calendar',
  '_articles_categories_top_menu_sitem' => 'Categories',
  '_articles_chart' => 'Articles',
  '_articles_entry_plural' => 'articles',
  '_articles_entry_single' => 'article',
  '_articles_featured' => 'featured',
  '_articles_featured_top_menu_sitem' => 'Featured',
  '_articles_get_rss' => 'RSS',
  '_articles_home_top_menu_sitem' => 'Articles Home',
  '_articles_lcaption_categories' => 'Articles',
  '_articles_lcaption_delete' => 'Delete',
  '_articles_lcaption_edit' => 'Edit',
  '_articles_lcaption_featured' => 'Featured',
  '_articles_lcaption_publish' => 'Publish',
  '_articles_lcaption_search_object' => 'Articles',
  '_articles_lcaption_tags' => 'Articles',
  '_articles_lcaption_unfeatured' => 'Unfeatured',
  '_articles_lcaption_unpublish' => 'Unpublish',
  '_articles_msg_failed_delete' => 'Cannot delete the article. Check if you have a permission to do it.',
  '_articles_msg_no_results' => 'Empty',
  '_articles_msg_success_delete' => 'Article has been deleted.',
  '_articles_pcaption_admin' => 'Articles',
  '_articles_pcaption_archive' => 'Articles Archive',
  '_articles_pcaption_calendar' => 'Calendar',
  '_articles_pcaption_categories' => 'Categories',
  '_articles_pcaption_category' => 'Category: {0}',
  '_articles_pcaption_featured' => 'Featured Articles',
  '_articles_pcaption_home' => 'Articles Home',
  '_articles_pcaption_popular' => 'Popular Articles',
  '_articles_pcaption_tag' => 'Tag: {0}',
  '_articles_pcaption_tags' => 'Tags',
  '_articles_pcaption_top_rated' => 'Top Rated Articles',
  '_articles_popular_top_menu_sitem' => 'Popular',
  '_articles_rss_caption' => 'Articles',
  '_articles_sbs_commentPost' => '{0} (New Article Comments)',
  '_articles_sbs_main' => '{0}',
  '_articles_search_top_menu_sitem' => 'Search',
  '_articles_sitemap' => 'Articles',
  '_articles_ss' => 'Articles',
  '_articles_ss_adm_stats' => 'Pending Articles',
  '_articles_status_0' => 'active',
  '_articles_status_1' => 'inactive',
  '_articles_status_2' => 'pending',
  '_articles_tags_top_menu_sitem' => 'Tags',
  '_articles_top_menu_item' => 'Articles',
  '_articles_top_top_menu_sitem' => 'Top Rated',
  '_articles_view_top_menu_sitem' => 'Articles',
  '_sbs_txt_title_bx_articles' => 'Articles',
  '_mma_Articles_Delete' => 'articles delete',
);
