<?php
/**
 * Copyright (c) BoonEx Pty Limited - http://www.boonex.com/
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
  '_sys_module_articles' => 'Статьи',

  '_articles' => 'Статьи',
  '_articles_actions_delete' => 'Удалить',
  '_articles_admin_menu_sitem' => 'Статьи',
  '_articles_archive_top_menu_sitem' => 'Архив',
  '_articles_bcaption_all' => 'Статьи',
  '_articles_bcaption_all_tags' => 'Все теги',
  '_articles_bcaption_archive' => 'Архив статей',
  '_articles_bcaption_calendar' => 'Календарь',
  '_articles_bcaption_calendar_browse' => 'Обзор статей по дням',
  '_articles_bcaption_categories' => 'Категории',
  '_articles_bcaption_category' => 'Категория: {0}',
  '_articles_bcaption_featured' => 'Избранные статьи',
  '_articles_bcaption_latest' => 'Последние статьи',
  '_articles_bcaption_member' => 'Последние статьи',
  '_articles_bcaption_popular' => 'Популярные статьи',
  '_articles_bcaption_post' => 'Создание статьи',
  '_articles_bcaption_settings' => 'Настройки',
  '_articles_bcaption_tag' => 'Тег: {0}',
  '_articles_bcaption_tags' => 'Теги',
  '_articles_bcaption_top_rated' => 'Лучшие статьи',
  '_articles_bcaption_view_action' => 'Действия',
  '_articles_bcaption_view_comment' => 'Комментарии',
  '_articles_bcaption_view_info' => 'Информация',
  '_articles_bcaption_view_main' => 'Статья',
  '_articles_bcaption_view_vote' => 'Рейтинг',
  '_articles_calendar_top_menu_sitem' => 'Календарь',
  '_articles_categories_top_menu_sitem' => 'Категории',
  '_articles_chart' => 'Статьи',
  '_articles_entry_plural' => 'статьи',
  '_articles_entry_single' => 'статья',
  '_articles_featured' => 'избранные',
  '_articles_featured_top_menu_sitem' => 'Избранные',
  '_articles_get_rss' => 'RSS',
  '_articles_home_top_menu_sitem' => 'Главная',
  '_articles_lcaption_categories' => 'Статьи',
  '_articles_lcaption_delete' => 'Удалить',
  '_articles_lcaption_edit' => 'Изменить',
  '_articles_lcaption_featured' => 'В избранное',
  '_articles_lcaption_publish' => 'Публикация',
  '_articles_lcaption_search_object' => 'Статьи',
  '_articles_lcaption_tags' => 'Статьи',
  '_articles_lcaption_unfeatured' => 'Не избранное',
  '_articles_lcaption_unpublish' => 'Отменить публикацию',
  '_articles_msg_failed_delete' => 'Невозможно удалить статью. Проверьте, есть ли у Вас соответствующее разрешение.',
  '_articles_msg_no_results' => 'Пусто',
  '_articles_msg_success_delete' => 'Статья была удалена.',
  '_articles_pcaption_admin' => 'Статьи',
  '_articles_pcaption_archive' => 'Архив статей',
  '_articles_pcaption_calendar' => 'Календарь',
  '_articles_pcaption_categories' => 'Категории',
  '_articles_pcaption_category' => 'Категория: {0}',
  '_articles_pcaption_featured' => 'Избранные статьи',
  '_articles_pcaption_home' => 'Главная',
  '_articles_pcaption_popular' => 'Популярные статьи',
  '_articles_pcaption_tag' => 'Тег: {0}',
  '_articles_pcaption_tags' => 'Теги',
  '_articles_pcaption_top_rated' => 'Лучшие статьи',
  '_articles_popular_top_menu_sitem' => 'Популярные',
  '_articles_rss_caption' => 'Статьи',
  '_articles_sbs_commentPost' => '{0} (новых комментариев к статье)',
  '_articles_sbs_main' => '{0}',
  '_articles_search_top_menu_sitem' => 'Поиск',
  '_articles_sitemap' => 'Статьи',
  '_articles_ss' => 'Статей',
  '_articles_ss_adm_stats' => 'Ожидающие статьи',
  '_articles_status_0' => 'архив',
  '_articles_status_1' => 'неактивные',
  '_articles_status_2' => 'ожидающие',
  '_articles_tags_top_menu_sitem' => 'Теги',
  '_articles_top_menu_item' => 'Статьи',
  '_articles_top_top_menu_sitem' => 'Лучшие',
  '_articles_view_top_menu_sitem' => 'Статьи',
  '_sbs_txt_title_bx_articles' => 'Статьи',
  '_mma_Articles_Delete' => 'Статьи: удалять',
);
