<?php
/**
 * Copyright (c) BoonEx Pty Limited - http://www.boonex.com/
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
  '_sys_module_sites' => 'Сайты',
  '_bx_site_caption_edit' => 'Редактировать сайты',
  '_bx_sites' => 'Сайты',
  '_bx_sites_action_add_site' => 'Добавить сайт',
  '_bx_sites_action_add_to_featured' => 'В избранное',
  '_bx_sites_action_my_sites' => 'Мои сайты',
  '_bx_sites_action_remove_from_featured' => 'Не избранное',
  '_bx_sites_action_title_delete' => 'Удалить',
  '_bx_sites_action_title_edit' => 'Изменить',
  '_bx_sites_adm_stats' => 'Ожидающие сайты',
  '_bx_sites_admin' => 'Администратор',
  '_bx_sites_admin_activate' => 'Активировать',
  '_bx_sites_admin_clear_cache' => 'Если вы изменили параметры ниже, <a href="javascript:void(0)" onclick="javascript:clearThumbCache();">Очистите Кэш Скриншотов</a> для создания новых.',
  '_bx_sites_admin_delete' => 'Удалить',
  '_bx_sites_admin_refresh_thumb' => 'Обновить миниатюру',
  '_bx_sites_admin_settings_info' => 'Вы можете получить "Ключ доступа" и "Секретный ключ", подписавшись на автоматические скриншоты по адресу: <a target="_blank" href="http://www.shrinktheweb.com/">ShrinkTheWeb</a>',
  '_bx_sites_admin_stw_note' => '<b>ВАЖНО:</b> По умолчанию, вы должны <a href="http://www.shrinktheweb.com/content/how-do-i-lock-my-account.html" target="_blank">добавить IP адрес своего сервера в список "Allowed Referrers" на сайте ShrinkTheWeb</a>.',
  '_bx_sites_admin_top_menu_sitem' => 'От администратора',
  '_bx_sites_administration' => 'Сайты',
  '_bx_sites_administration_add_site' => 'Добавить сайт',
  '_bx_sites_administration_admin_sites' => 'Администрирование',
  '_bx_sites_administration_settings' => 'Настройки',
  '_bx_sites_administration_stw_acc_failed' => 'Невозможно получить информацию об аккаунте',
  '_bx_sites_administration_stw_acc_no_data' => 'Пожалуйста, введите Ваши реквизиты у ShrinkTheWeb',
  '_bx_sites_administration_stw_acc_success' => 'Успешно получена информация об аккаунте',
  '_bx_sites_all_top_menu_sitem' => 'Недавние',
  '_bx_sites_bcaption_actions' => 'Действия',
  '_bx_sites_bcaption_administration' => 'Администрирование',
  '_bx_sites_bcaption_all' => 'Все',
  '_bx_sites_bcaption_comments' => 'Комментарии',
  '_bx_sites_bcaption_description' => 'Описание',
  '_bx_sites_bcaption_image' => 'Изображение',
  '_bx_sites_bcaption_information' => 'Информация',
  '_bx_sites_bcaption_latest' => 'Недавно добавленные сайты',
  '_bx_sites_bcaption_owner_sites' => 'Мои сайты',
  '_bx_sites_bcaption_previously' => 'Ранее в рейтинге',
  '_bx_sites_bcaption_rate' => 'Оценить сайт',
  '_bx_sites_bcaption_site_add' => 'Добавить сайт',
  '_bx_sites_block_submenu_add_site' => 'Добавить',
  '_bx_sites_block_submenu_main' => 'Главная',
  '_bx_sites_block_submenu_manage_sites' => 'Управление',
  '_bx_sites_block_submenu_pending_sites' => 'Ожидающие решения',
  '_bx_sites_calendar_top_menu_sitem' => 'Календарь',
  '_bx_sites_caption_allow_comments' => 'Комментарии доступны',
  '_bx_sites_caption_allow_rate' => 'Голосование доступно',
  '_bx_sites_caption_allow_view' => 'Просмотр доступен',
  '_bx_sites_caption_browse_add' => 'Добавить сайт',
  '_bx_sites_caption_browse_admin' => 'От администратора',
  '_bx_sites_caption_browse_all' => 'Недавние',
  '_bx_sites_caption_browse_by_category' => 'Обзор сайтов по категориям: ',
  '_bx_sites_caption_browse_by_day' => 'Обзор сайтов по дням: ',
  '_bx_sites_caption_browse_by_tag' => 'Обзор сайтов по тегам: ',
  '_bx_sites_caption_browse_by_user' => 'Обзор сайтов по пользователям: ',
  '_bx_sites_caption_browse_calendar' => 'Календарь',
  '_bx_sites_caption_browse_categories' => 'Категории',
  '_bx_sites_caption_browse_featured' => 'Избранные',
  '_bx_sites_caption_browse_manage' => 'Управление сайтами',
  '_bx_sites_caption_browse_my' => 'Мои сайты',
  '_bx_sites_caption_browse_pending' => 'Ожидающие решения',
  '_bx_sites_caption_browse_popular' => 'Популярные',
  '_bx_sites_caption_browse_profile' => 'От пользователей',
  '_bx_sites_caption_browse_search' => 'Поиск',
  '_bx_sites_caption_browse_tags' => 'Теги',
  '_bx_sites_caption_browse_top_rated' => 'Лучшие',
  '_bx_sites_caption_categories' => 'Категории',
  '_bx_sites_caption_home' => 'Главная',
  '_bx_sites_caption_keyword' => 'Ключевое слово',
  '_bx_sites_caption_public_feature' => 'Избранные сайты',
  '_bx_sites_caption_public_last_featured' => 'Последние избранные сайты',
  '_bx_sites_caption_public_latest' => 'Недавно добавленные общедоступные сайты',
  '_bx_sites_caption_search_results' => 'Результаты поиска:',
  '_bx_sites_caption_share_site' => 'Поделиться',
  '_bx_sites_caption_tags' => 'Теги',
  '_bx_sites_categories_top_menu_sitem' => 'Категории',
  '_bx_sites_err_edit_site' => 'Ошибка при обновлении сайта',
  '_bx_sites_err_keyword' => 'Пожалуйста, укажите ключевое слово от 3 до 100 символов',
  '_bx_sites_error_occured' => 'Произошла ошибка',
  '_bx_sites_featured_top_menu_sitem' => 'Избранные',
  '_bx_sites_form_description' => 'Описание',
  '_bx_sites_form_field_err' => 'неверное значение',
  '_bx_sites_form_other_thumbnail' => 'Другая миниатюра',
  '_bx_sites_form_photo' => 'Фото',
  '_bx_sites_form_title' => 'Заголовок',
  '_bx_sites_form_url' => 'Адрес',
  '_bx_sites_home_top_menu_sitem' => 'Главная',
  '_bx_sites_hon' => 'Голосование',
  '_bx_sites_hon_top_menu_sitem' => 'Голосование',
  '_bx_sites_menu_my_sites_profile' => 'Сайты',
  '_bx_sites_msg_access_denied' => 'Доступ запрещен',
  '_bx_sites_msg_add_more_sites' => '<a href="%s">Нажмите здесь</a>, чтобы добавить еще.',
  '_bx_sites_msg_added_to_featured' => 'Сайт был добавлен в избранное',
  '_bx_sites_msg_no_sites' => 'Сайтов еще нет.',
  '_bx_sites_msg_page_not_found' => 'Страница не найдена',
  '_bx_sites_msg_pending_approval' => 'Этот сайт ожидает одобрения администратора. Пожалуйста, подождите.',
  '_bx_sites_msg_removed_from_featured' => 'Сайт был удален из избранного',
  '_bx_sites_msg_you_have_active_sites' => '<a href="%s">%d активных сайтов</a>',
  '_bx_sites_msg_you_have_pending_sites' => '<a href="%s">%d ожидающих решения сайтов</a>',
  '_bx_sites_msg_you_have_sites' => 'У Вас %s%s.',
  '_bx_sites_pending_approval' => 'Ожидающие решения',
  '_bx_sites_plural' => 'сайтов',
  '_bx_sites_poll_add' => '<a href="{profile_link}">{profile_nick}</a> добавил новый сайт <a href="{site_url}">{site_caption}</a>',
  '_bx_sites_poll_change' => '<a href="{profile_link}">{profile_nick}</a> изменил сайт <a href="{site_url}">{site_caption}</a>',
  '_bx_sites_poll_commentPost' => '<a href="{profile_link}">{profile_nick}</a> прокомментировал сайт <a href="{site_url}">{site_caption}</a>',
  '_bx_sites_poll_rate' => '<a href="{profile_link}">{profile_nick}</a> оценил сайт <a href="{site_url}">{site_caption}</a>',
  '_bx_sites_popular_top_menu_sitem' => 'Популярные',
  '_bx_sites_privacy_comment' => 'Комемнтарии',
  '_bx_sites_privacy_view' => 'Просматривать',
  '_bx_sites_privacy_vote' => 'Оценивать',
  '_bx_sites_profile_top_menu_sitem' => 'От пользователей',
  '_bx_sites_sbs_comment' => 'Новые комментарии сайта',
  '_bx_sites_search_top_menu_sitem' => 'Поиск',
  '_bx_sites_single' => 'сайт',
  '_bx_sites_site' => 'Сайт',
  '_bx_sites_site_link_error' => 'Эта ссылка кажется нерабочей. Пожалуйста, проверьте URL и попробуйте снова.',
  '_bx_sites_site_was_deleted' => 'Сайт был удален',
  '_bx_sites_tags_top_menu_sitem' => 'Теги',
  '_bx_sites_top_menu_item' => 'Сайты',
  '_bx_sites_top_top_menu_sitem' => 'Лучшие',
  '_bx_sites_unit_comments' => 'комментариев',
  '_bx_sites_unit_from' => 'От',
  '_bx_sites_wall_added_new' => 'добавлено новых',
  '_bx_sites_wall_added_new_comment' => 'прокомментировал',
  '_bx_sites_wall_added_new_items' => 'добавлено {0} новых сайтов',
  '_bx_sites_wall_object' => 'сайт',
  '_mma_sites_add' => 'Сайты: добавлять',
  '_mma_sites_approve' => 'Сайты: одобрять',
  '_mma_sites_browse' => 'Сайты: просматривать',
  '_mma_sites_delete_any_site' => 'Сайты: удалять любой',
  '_mma_sites_edit_any_site' => 'Сайты: редактировать любой',
  '_mma_sites_mark_as_featured' => 'Сайты: добавлять в Избранные',
  '_mma_sites_search' => 'Сайты: искать',
  '_mma_sites_view' => 'Сайты: смотреть',
  '_sbs_txt_title_bx_sites' => 'Сайты',
);
