<?php

$aLangContent = array(

  // ================ CHANGED KEYS ==================

  '_bx_sounds_Sound_block' => 'Аудио',
  '_bx_sounds_action_feature' => 'В избранное',
  '_bx_sounds_action_share' => 'Поделиться',
  '_bx_sounds_action_unfeature' => 'Не избранное',
  '_bx_sounds_add' => 'Добавить аудио',
  '_bx_sounds_add_objects' => 'Добавить аудио',
  '_bx_sounds_adm_stats' => 'Ожидающие аудио',
  '_bx_sounds_admin_feature' => 'В избранное',
  '_bx_sounds_admin_unfeature' => 'Не избранное',
  '_bx_sounds_album_add_objects' => 'Добавить аудио',
  '_bx_sounds_album_disapproved' => 'Ожидающее',
  '_bx_sounds_album_manage_objects' => 'Управление аудио',
  '_bx_sounds_album_manage_objects_disapproved' => 'ожидающее',
  '_bx_sounds_album_manage_objects_failed' => 'ошибочное',
  '_bx_sounds_album_manage_objects_not_processed' => 'необработанное',
  '_bx_sounds_album_objects' => 'аудио в этом альбоме',
  '_bx_sounds_album_sounds_rest' => 'Аудио из этого альбома',
  '_bx_sounds_album_view' => 'Просмотр доступен',
  '_bx_sounds_albums_disapproved' => 'Мои ожидающие альбомы',
  '_bx_sounds_albums_my' => 'Мои альбомы',
  '_bx_sounds_alert_commented' => '{0} прокомментировали Ваше аудио',
  '_bx_sounds_all' => 'Все аудио',
  '_bx_sounds_approved' => 'Активное',
  '_bx_sounds_browse_by_album' => 'Обзор аудио из альбома "{0}"',
  '_bx_sounds_browse_by_category' => 'Обзор аудио по категории "{0}"',
  '_bx_sounds_browse_by_owner' => 'Обзор аудио от {0}',
  '_bx_sounds_browse_by_tag' => 'Обзор аудио по тегу "{0}"',
  '_bx_sounds_browse_file' => 'Выбрать аудио',
  '_bx_sounds_count_info' => 'У Вас {0} <a href="{1}">аудио</a> в этом альбоме.',
  '_bx_sounds_count_status_info' => 'У Вас {0} <a href="{1}">{2} аудио</a> в этой папке.',
  '_bx_sounds_couple_Sound_block' => 'Парные аудио',
  '_bx_sounds_delete' => 'Аудио было удалено',
  '_bx_sounds_disapproved' => 'Ожидающее',
  '_bx_sounds_distribute' => 'Условия распространения аудио',
  '_bx_sounds_failed' => 'Ошибочное',
  '_bx_sounds_favorited' => 'Любимые аудио',
  '_bx_sounds_featured' => 'Избранные аудио',
  '_bx_sounds_file_not_found' => 'Аудио не найдено',
  '_bx_sounds_file_was_uploaded' => 'Ваше аудио было загружено (id:{0}) от {1}',
  '_bx_sounds_i_have_the_right_to_distribute' => 'У меня есть право на публикацию этого аудио',
  '_bx_sounds_info_main' => 'Информация об аудио',
  '_bx_sounds_latest' => 'Последнее аудио от этого пользователя',
  '_bx_sounds_latest_file' => 'Последнее избранное аудио',
  '_bx_sounds_menu_pending' => 'Необработанное',
  '_bx_sounds_my' => 'Мои аудио',
  '_bx_sounds_pending' => 'Необработанное',
  '_bx_sounds_plural' => 'Аудио',
  '_bx_sounds_processing' => 'Обрабатываемое',
  '_bx_sounds_profile_album_name' => '{0} аудио',
  '_bx_sounds_profile_sounds' => 'Аудио',
  '_bx_sounds_public' => 'Аудио',
  '_bx_sounds_related' => 'Похожие аудио',
  '_bx_sounds_sbs_comments' => 'Новые комментарии к аудио',
  '_bx_sounds_single' => 'Аудио',
  '_bx_sounds_special' => 'Избранные аудио',
  '_bx_sounds_spy_added' => '<a href="{profile_link}">{profile_nick}</a> добавил новое аудио <a href="{entry_url}">{entry_caption}</a>',
  '_bx_sounds_spy_comment_posted' => '<a href="{recipient_p_link}">{recipient_p_nick}</a> <a href="{entry_url}">аудио</a> было прокомментировано <a href="{profile_link}">{profile_nick}</a>',
  '_bx_sounds_spy_rated' => '<a href="{recipient_p_link}">{recipient_p_nick}</a> <a href="{entry_url}">аудио</a> было оценено <a href="{profile_link}">{profile_nick}</a>',
  '_bx_sounds_top' => 'Лучшие аудио',
  '_bx_sounds_top_menu_album' => 'Альбом',
  '_bx_sounds_top_menu_albums' => 'Альбомы',
  '_bx_sounds_top_menu_all' => 'Недавние',
  '_bx_sounds_top_menu_favorited' => 'Понравившиеся мне аудио',
  '_bx_sounds_top_menu_featured' => 'Избранные',
  '_bx_sounds_top_menu_item' => 'Аудио',
  '_bx_sounds_top_menu_popular' => 'Популярные',
  '_bx_sounds_top_menu_profile' => 'Аудио',
  '_bx_sounds_upload' => 'Аудио',
  '_bx_sounds_upload_instance' => 'Загрузить аудио',
  '_bx_sounds_view' => 'Проигрывание аудио',
  '_bx_sounds_wall_added_new_items' => 'добавил {0} новых аудио в альбом',
  '_bx_sounds_wall_music_private' => 'закрытое аудио',
  '_bx_sounds_wall_object' => 'аудио',

);
