<?php

$aLangContent = array(

  // ================ CHANGED KEYS ==================    

  '_bx_videos_action_feature' => 'В избранное',
  '_bx_videos_action_share' => 'Поделиться',
  '_bx_videos_action_unfeature' => 'Не избранное',
  '_bx_videos_add' => 'Добавить видео',
  '_bx_videos_add_objects' => 'Добавить видео',
  '_bx_videos_adm_stats' => 'Ожидающие видео',
  '_bx_videos_admin_feature' => 'В избранное',
  '_bx_videos_admin_unfeature' => 'Не избранное',
  '_bx_videos_album_add_objects' => 'Добавить видео',
  '_bx_videos_album_disapproved' => 'Ожидающее',
  '_bx_videos_album_manage_objects' => 'Управление видео',
  '_bx_videos_album_manage_objects_disapproved' => 'ожидающее',
  '_bx_videos_album_manage_objects_failed' => 'ошибочное',
  '_bx_videos_album_manage_objects_not_processed' => 'необработанное',
  '_bx_videos_album_objects' => 'видео в этом альбоме',
  '_bx_videos_album_videos_rest' => 'Видео из этого альбома',
  '_bx_videos_album_view' => 'Просмотр доступен',
  '_bx_videos_albums_disapproved' => 'Мои ожидающие альбомы',
  '_bx_videos_albums_my' => 'Мои альбомы',
  '_bx_videos_alert_commented' => '{0} прокомментировал Ваше видео',
  '_bx_videos_all' => 'Все видео',
  '_bx_videos_approved' => 'Активное',
  '_bx_videos_bcaption_all' => 'Все видео',
  '_bx_videos_browse_by_album' => 'Просмотр видео из альбома "{0}"',
  '_bx_videos_browse_by_category' => 'Просмотр видео по категории "{0}"',
  '_bx_videos_browse_by_owner' => 'Просмотр видео от {0}',
  '_bx_videos_browse_by_tag' => 'Просмотр видео по тегу "{0}"',
  '_bx_videos_count_info' => 'У Вас {0} <a href="{1}">видео</a> в этом альбоме.',
  '_bx_videos_count_status_info' => 'У Вас {0} <a href="{1}">{2} видео</a> в этом альбоме.',
  '_bx_videos_couple_Video_block' => 'Парные видео',
  '_bx_videos_delete' => 'Видео было удалена',
  '_bx_videos_disapproved' => 'Ожидающее',
  '_bx_videos_distribute' => 'Условия распространения видео',
  '_bx_videos_failed' => 'Ошибочное',
  '_bx_videos_favorited' => 'Избранные видео',
  '_bx_videos_featured' => 'Понравившиеся видео',
  '_bx_videos_file_not_found' => 'Видео не найдена',
  '_bx_videos_i_have_the_right_to_distribute' => 'У меня есть право выкладывать это видео',
  '_bx_videos_latest' => 'Последние видео от этого пользователя',
  '_bx_videos_latest_file' => 'Последние избранные видео',
  '_bx_videos_menu_profile' => 'Видео',
  '_bx_videos_my' => 'Мои видео',
  '_bx_videos_pending' => 'Необработанное',
  '_bx_videos_plural' => 'видео',
  '_bx_videos_processing' => 'Обрабатываемое',
  '_bx_videos_profile_album_name' => 'видео',
  '_bx_videos_public' => 'Видео',
  '_bx_videos_related' => 'Похожие видео',
  '_bx_videos_single' => 'видео',
  '_bx_videos_special' => 'Избранные видео',
  '_bx_videos_spy_added' => '<a href="{profile_link}">{profile_nick}</a> добавил новое видео <a href="{entry_url}">{entry_caption}</a>',
  '_bx_videos_spy_comment_posted' => '<a href="{recipient_p_link}">{recipient_p_nick}</a> <a href="{entry_url}">видео</a> было прокомментировано <a href="{profile_link}">{profile_nick}</a>',
  '_bx_videos_spy_rated' => '<a href="{recipient_p_link}">{recipient_p_nick}</a> <a href="{entry_url}">видео</a> было оценено <a href="{profile_link}">{profile_nick}</a>',
  '_bx_videos_top' => 'Лучшие видео',
  '_bx_videos_top_menu_album' => 'Альбом',
  '_bx_videos_top_menu_albums' => 'Альбомы',
  '_bx_videos_top_menu_all' => 'Недавние',
  '_bx_videos_upload' => 'Видео',
  '_bx_videos_upload_instance' => 'Загрузить видео',
  '_bx_videos_view' => 'Просмотр видео',
  '_bx_videos_wall_added_new_items' => 'добавил {0} новых видео в альбом',
  '_bx_videos_wall_object' => 'видео',
  '_bx_videos_wall_video_private' => 'закрытое видео',

);
