<?php

$aLangContent = array(

  // ================ CHANGED KEYS ==================

  '_bx_events_action_add_to_featured' => 'В избранное',
  '_bx_events_action_manage_fans' => 'Участники',
  '_bx_events_action_remove_from_featured' => 'Не избранное',
  '_bx_events_action_title_edit' => 'Изменить',
  '_bx_events_action_title_share' => 'Поделиться',
  '_bx_events_action_upload_files' => 'Файлы',
  '_bx_events_action_upload_photos' => 'Изображения',
  '_bx_events_action_upload_sounds' => 'Аудио',
  '_bx_events_action_upload_videos' => 'Видео',
  '_bx_events_administration_admin_events' => 'Администрирование',
  '_bx_events_block_calendar' => 'Календарь ',
  '_bx_events_block_submenu_pending' => 'Ожидающие',
  '_bx_events_caption_browse_by_author' => 'Обзор событий по автору: ',
  '_bx_events_caption_browse_by_author_joined_events' => 'Обзор событий по автору как участнику: ',
  '_bx_events_caption_browse_by_category' => 'Обзор событий по категории: ',
  '_bx_events_caption_browse_by_country' => 'Обзор событий по стране: ',
  '_bx_events_caption_browse_by_day' => 'Обзор событий по дню: ',
  '_bx_events_caption_browse_by_tag' => 'Обзор событий по тегу: ',
  '_bx_events_caption_event_end' => 'Конец',
  '_bx_events_caption_event_start' => 'Начало',
  '_bx_events_caption_membership_filter' => 'Регистрация доступна членствам',
  '_bx_events_caption_share_event' => 'Поделиться',
  '_bx_events_categories' => 'Категории',
  '_bx_events_form_header_files' => 'Файлы',
  '_bx_events_form_header_images' => 'Фото',
  '_bx_events_form_header_info' => 'Информация',
  '_bx_events_form_header_privacy' => 'Настройки конфиденциальности',
  '_bx_events_form_header_sounds' => 'Аудио',
  '_bx_events_form_header_videos' => 'Видео',
  '_bx_events_membership_filter_none' => 'Всем',
  '_bx_events_msg_added_to_featured' => 'Событие было добавлено в избранное',
  '_bx_events_msg_removed_from_featured' => 'Событие было удалено из избранного',
  '_bx_events_msg_you_have_no_events' => 'У Вас нет событий. <a href="%s">Нажмите сюда</a>, чтобы добавить событие.',
  '_bx_events_msg_you_have_pending_approval_events' => 'У Вас <a href="%s">%d ожидающих событий</a>',
  '_bx_events_pending_approval' => 'Ожидающие',
  '_bx_events_privacy_admins_only' => 'Администраторам',
  '_bx_events_privacy_comment' => 'Комментарии доступны',
  '_bx_events_privacy_join' => 'Регистрация доступна',
  '_bx_events_privacy_participants' => 'Участникам',
  '_bx_events_privacy_participants_only' => 'Участникам',
  '_bx_events_privacy_post_in_forum' => 'Форум доступен',
  '_bx_events_privacy_rate' => 'Голосование доступно',
  '_bx_events_privacy_upload_files' => 'Загрузка файлов доступна',
  '_bx_events_privacy_upload_photos' => 'Загрузка фото доступна',
  '_bx_events_privacy_upload_sounds' => 'Загрузка аудио доступна',
  '_bx_events_privacy_upload_videos' => 'Загрузка видео доступна',
  '_bx_events_privacy_view_event' => 'Просмотр доступен',
  '_bx_events_privacy_view_participants' => 'Просмотр участников доступен',
  '_bx_events_tags' => 'Теги',
  '_bx_events_wall_added_new_items' => 'добавил {0} новых событий',
  '_mma_events_mark_as_featured' => 'События: помещать в избранное',
  
);
