<?php
/**
 * Copyright (c) BoonEx Pty Limited - http://www.boonex.com/
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
    '_sys_module_wall' => 'Timeline',

    '_wall' => 'Timeline',
    '_wall_pc_view' => 'Timeline',
    '_wall_pc_view_index_tl' => 'Timeline',
    '_wall_pc_view_profile_tl' => 'Timeline',
    '_wall_pc_view_account_tl' => 'Friends Timeline',
    '_wall_pc_view_index_ol' => 'Outline',
	'_wall_pc_post' => 'Post to Timeline',
	'_wall_pc_post_index_tl' => 'Post to Timeline',
    '_wall_pc_post_profile_tl' => 'Post to Timeline',
    '_wall_pc_admin' => 'Timeline',
    '_wall_bc_settings' => 'Settings',
	'_wall_reposted' => 'reposted',
    '_wall_added_new' => 'added new',
    '_wall_edited_his_profile' => 'edited his profile',
    '_wall_edited_her_profile' => 'edited her profile',
    '_wall_edited_their_profile' => 'edited their profile',
    '_wall_edited_his_profile_status_message' => 'changed his profile status message',
    '_wall_edited_her_profile_status_message' => 'changed her profile status message',
    '_wall_edited_their_profile_status_message' => 'changed their profile status message',
    '_wall_added_new_comment_profile' => 'commented on a',
	'_wall_added_new_title_comment_profile' => '{0} commented on a {1}',
    '_wall_object_profile' => 'profile',
    '_wall_info' => 'info',
    '_wall_friends_with' => 'is now friends with',
    '_wall_today' => 'Today',
    '_wall_1_days_ago' => 'Yesterday',
    '_wall_n_days_ago' => '{0} days ago',
    '_wall_write' => 'Text',
    '_wall_share_link' => 'Link',
    '_wall_add_photo' => 'Photo',
    '_wall_add_video' => 'Video',
    '_wall_add_sound' => 'Audio',
    '_wall_post' => 'Submit',
	'_wall_select_file' => 'Select File',
    '_wall_link_url' => 'URL',
	'_wall_n_comments_long' => '<i>{0}</i> comments',
    '_wall_n_comments' => '<i>{0}</i>',
    '_wall_no_comments' => '',
    '_wall_show_comments' => 'Show comments',
    '_wall_hide_comments' => 'Hide comments',
    '_wall_comment' => 'Comment',
	'_wall_added_text' => 'wrote',
	'_wall_added_title_text' => '{0} wrote',
    '_wall_added_link' => 'shared a link',
	'_wall_added_title_link' => '{0} shared a link',
    '_wall_added_photos' => 'added a photo',
	'_wall_added_title_photos' => '{0} added a photo',
    '_wall_added_videos' => 'added a video',
	'_wall_added_title_videos' => '{0} added a video',
    '_wall_added_sounds' => 'added a sound',
	'_wall_added_title_sounds' => '{0} added a sound',
    '_wall_photo_album' => '{0}\'s timeline photos',
    '_wall_sound_album' => '{0}\'s timeline sounds',
    '_wall_video_album' => '{0}\'s timeline videos',
    '_wall_view_all' => 'All posts',
    '_wall_view_owner' => 'Posts by {0}',
    '_wall_view_other' => 'Posts by others',
    '_wall_top_smenu_item_wall' => 'Timeline',
    '_wall_top_smenu_item_my_wall' => 'Timeline',
    '_wall_page_caption' => '{0}\'s Timeline',
    '_wall_page_caption_my' => 'My Timeline',
    '_wall_anonymous' => 'Guest',
    '_wall_post_delete' => 'Delete',
    '_wall_msg_no_results' => 'Empty',
    '_wall_msg_page_not_found' => 'Page not found',
    '_wall_get_rss' => 'RSS',
    '_wall_rss_caption' => 'timeline',
    '_wall_msg_failed_post' => 'Wrong input data',
    '_wall_msg_not_allowed_post' => 'Your membership level does not allow you to post here',
    '_wall_msg_text_empty_message' => 'The message to be posted is empty',
    '_wall_msg_link_empty_link' => 'The link to be posted is empty',
    '_wall_admin_menu_sitem' => 'Timeline',
 	'_mma_timeline_repost' => 'timeline repost',
    '_mma_timeline_post_comment' => 'timeline post comment',
    '_mma_timeline_delete_comment' => 'timeline delete comment',
    '_sbs_txt_title_bx_wall' => 'Timeline',
    '_wall_sbs_main' => '{0}\'s timeline',
    '_wall_sbs_update' => '{0}\'s Timeline (new events)',
    '_wall_time_range' => 'Time range (days ago):',
    '_wall_load_more' => 'Load More',
	'_wall_see_more' => 'see more',
    '_wall_spy_post' => '<a href="{profile_link}">{profile_nick}</a> posted on <a href="{recipient_p_link}">{recipient_p_nick}</a>\'s timeline',
	'_wall_spy_repost' => '<a href="{profile_link}">{profile_nick}</a> reposted <a href="{recipient_p_link}">{recipient_p_nick}</a>\'s timeline post',
	'_wall_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated <a href="{recipient_p_link}">{recipient_p_nick}</a>\'s timeline post',
    '_wall_spy_post_comment' => '<a href="{profile_link}">{profile_nick}</a> commented on <a href="{recipient_p_link}">{recipient_p_nick}</a>\'s timeline',
	'_wall_do_vote' => 'Like',
	'_wall_n_votes_long' => '<i>{0}</i> likes',
	'_wall_n_votes' => '<i>{0}</i>',
    '_bx_wall_chart' => 'Wall Events',
    '_wall_alert_module_profile' => 'Profile',
    '_wall_alert_module_friend' => 'Friend',
    '_wall_alert_action_add' => '{0} (add item)',
    '_wall_alert_action_create' => '{0} (add item)',
    '_wall_alert_action_change' => '{0} (change item)',
    '_wall_alert_action_edit' => '{0} (change item)',
    '_wall_alert_action_delete' => '{0} (delete item)',
	'_wall_alert_action_comment_add' => '{0} (add comment)',
    '_wall_alert_action_commentPost' => '{0} (add comment) - old comments',
    '_wall_alert_action_edit_status_message' => '{0} (change status message)',
    '_wall_alert_action_accept' => '{0} (accept)',

	'_wall_n_reposts_long' => '<i>{0}</i> reposts',
    '_wall_n_reposts' => '<i>{0}</i>',
	'_wall_no_reposts_long' => '<i>{0}</i> reposts',
	'_wall_no_reposts' => '<i>{0}</i>',
	'_wall_txt_do_repost' => 'Repost',
	'_wall_txt_reposted_by' => 'Reposted by',
	'_wall_txt_err_cannot_repost' => 'Cannot repost. Please report.',
	'_wall_txt_err_already_reposted' => 'You already reposted the item.',
	'_wall_txt_msg_success_repost' => '',
	'_wall_reposted_text' => 'reposted a text',
	'_wall_reposted_title_text' => '{0} reposted a text',
    '_wall_reposted_link' => 'reposted a link',
	'_wall_reposted_title_link' => '{0} reposted a link',
    '_wall_reposted_photos' => 'reposted a photo',
	'_wall_reposted_title_photos' => '{0} reposted a photo',
    '_wall_reposted_videos' => 'reposted a video',
	'_wall_reposted_title_videos' => '{0} reposted a video',
    '_wall_reposted_sounds' => 'reposted a sound',
	'_wall_reposted_title_sounds' => '{0} reposted a sound',
	'_wall_reposted_profile_comment_add' => 'reposted a profile comment',
	'_wall_reposted_title_profile_comment_add' => '{0} reposted a profile comment',
	'_wall_reposted_profile_edit' => 'reposted a profile changed',
	'_wall_reposted_title_profile_edit' => '{0} reposted a profile changed',
	'_wall_reposted_profile_edit_status_message' => 'reposted a profile status changed',
	'_wall_reposted_title_profile_edit_status_message' => '{0} reposted a profile status changed',
	'_wall_reposted_friend_accept' => 'reposted a profile friend accept',
	'_wall_reposted_title_friend_accept' => '{0} reposted a profile friend accept'
);
