<?php
/**
 * Copyright (c) BoonEx Pty Limited - http://www.boonex.com/
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
    '_sys_module_wall' => 'Линейка',

    '_wall' => 'Линейка',
    '_wall_pc_view' => 'Линейка',
    '_wall_pc_view_index_tl' => 'Линейка',
    '_wall_pc_view_profile_tl' => 'Линейка',
    '_wall_pc_view_account_tl' => 'Друзья',
    '_wall_pc_view_index_ol' => 'Обзор',
	'_wall_pc_post' => 'Добавить на линейку',
	'_wall_pc_post_index_tl' => 'Добавить на линейку',
    '_wall_pc_post_profile_tl' => 'Добавить на линейку',
    '_wall_pc_admin' => 'Линейка',
    '_wall_bc_settings' => 'Настройки',
    '_wall_reposted' => 'Зарепостили',
    '_wall_added_new' => 'добавил новый',
    '_wall_edited_his_profile' => 'отредактировал свой профиль',
    '_wall_edited_her_profile' => 'отредактировала свой профиль',
    '_wall_edited_their_profile' => 'отредактировали свой профиль',
    '_wall_edited_his_profile_status_message' => 'изменил статус-сообщение своего профиля',
    '_wall_edited_her_profile_status_message' => 'изменила статус-сообщение своего профиля',
    '_wall_edited_their_profile_status_message' => 'изменили статус-сообщение своего профиля',
    '_wall_added_new_comment_profile' => 'прокомментировал',
	'_wall_added_new_title_comment_profile' => '{0} прокомментировал {1}',
    '_wall_object_profile' => 'профиль',
    '_wall_info' => 'информация',
    '_wall_friends_with' => 'теперь дружит с',
    '_wall_today' => 'Сегодня',
    '_wall_1_days_ago' => 'Вчера',
    '_wall_n_days_ago' => '{0} дней назад',
    '_wall_write' => 'Текст',
    '_wall_share_link' => 'Ссылка',
    '_wall_add_photo' => 'Фото',
    '_wall_add_video' => 'Видео',
    '_wall_add_sound' => 'Аудио',
    '_wall_post' => 'Послать',
	'_wall_select_file' => 'Выбрать файл',
    '_wall_link_url' => 'URL',
	'_wall_n_comments_long' => '<i>{0}</i> комментариев',
	'_wall_n_comments' => '<i>{0}</i>',
    '_wall_no_comments' => '',
	'_wall_show_comments' => 'Показать комментарии',
    '_wall_hide_comments' => 'Скрыть комментарии',
    '_wall_comment' => 'Комментировать',
	'_wall_added_text' => 'написал',
	'_wall_added_title_text' => '{0} написал',
    '_wall_added_link' => 'посоветовал ссылку',
	'_wall_added_title_link' => '{0} посоветовал ссылку',
    '_wall_added_photos' => 'добавил фото',
	'_wall_added_title_photos' => '{0} добавил фото',
    '_wall_added_videos' => 'добавил видео',
	'_wall_added_title_videos' => '{0} добавил видео',
    '_wall_added_sounds' => 'добавил аудио',
	'_wall_added_title_sounds' => '{0} добавил аудио',
    '_wall_photo_album' => '{0} фото на Линейке',
    '_wall_sound_album' => '{0} аудио на Линейке',
    '_wall_video_album' => '{0} видео на Линейке',
    '_wall_view_all' => 'Все сообщения',
    '_wall_view_owner' => 'Сообщения от {0}',
    '_wall_view_other' => 'Сообщения от других',
    '_wall_top_smenu_item_wall' => 'Линейка',
    '_wall_top_smenu_item_my_wall' => 'Линейка',
    '_wall_page_caption' => '{0}\'s линейка',
    '_wall_page_caption_my' => 'Моя линейка',
    '_wall_anonymous' => 'Гость',
    '_wall_post_delete' => 'Удалить',
    '_wall_msg_no_results' => 'Пусто',
    '_wall_msg_page_not_found' => 'Страница не найдена',
    '_wall_get_rss' => 'RSS',
    '_wall_rss_caption' => 'линейка',
    '_wall_msg_failed_post' => 'Неправильные входные данные',
    '_wall_msg_not_allowed_post' => 'Ваше членство не позволяет оставлять здесь сообщения',
    '_wall_msg_text_empty_message' => 'Сообщение для отправки пустое',
    '_wall_msg_link_empty_link' => 'Ссылка для отправки пустая',
    '_wall_admin_menu_sitem' => 'Линейка',
    '_mma_timeline_repost' => 'Линейка: репост',
    '_mma_timeline_post_comment' => 'Линейка: комментировать',
    '_mma_timeline_delete_comment' => 'Линейка: удалять комментарии',
    '_sbs_txt_title_bx_wall' => 'Линейка',
    '_wall_sbs_main' => '{0} Линейка',
    '_wall_sbs_update' => '{0} Линейка (новые события)',
    '_wall_time_range' => 'Дата (дней назад):',
    '_wall_load_more' => 'Загрузить еще',
	'_wall_see_more' => 'еще',
    '_wall_spy_post' => '<a href="{profile_link}">{profile_nick}</a> оставил сообщение на <a href="{recipient_p_link}">{recipient_p_nick}</a> линейке',
	'_wall_spy_repost' => '<a href="{profile_link}">{profile_nick}</a> зарепостил сообщение с <a href="{recipient_p_link}">{recipient_p_nick}</a> линейки',
	'_wall_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> оценил сообщение на <a href="{recipient_p_link}">{recipient_p_nick}</a> линейке',
    '_wall_spy_post_comment' => '<a href="{profile_link}">{profile_nick}</a> прокомментировал сообщение на <a href="{recipient_p_link}">{recipient_p_nick}</a> линейке',
    '_wall_do_vote' => 'Нравиться',
	'_wall_n_votes_long' => '<i>{0}</i> голосов',
	'_wall_n_votes' => '<i>{0}</i>',
    '_bx_wall_chart' => 'События линейки',
    '_wall_alert_module_profile' => 'Профиль',
    '_wall_alert_module_friend' => 'Друг',
    '_wall_alert_action_add' => '{0} (добавить элемент)',
    '_wall_alert_action_create' => '{0} (добавить элемент)',
    '_wall_alert_action_change' => '{0} (изменить элемент)',
    '_wall_alert_action_edit' => '{0} (изменить элемент)',
    '_wall_alert_action_delete' => '{0} (удалить элемент)',
	'_wall_alert_action_comment_add' => '{0} (добавить комментарий)',
    '_wall_alert_action_commentPost' => '{0} (добавить комментарий) - старые комментарии',
    '_wall_alert_action_edit_status_message' => '{0} (изменить статус-сообщение)',
    '_wall_alert_action_accept' => '{0} (принять)',

	'_wall_n_reposts_long' => '<i>{0}</i> репостов',
    '_wall_n_reposts' => '<i>{0}</i>',
	'_wall_no_reposts_long' => '<i>{0}</i> репостов',
	'_wall_no_reposts' => '<i>{0}</i>',
	'_wall_txt_do_repost' => 'Зарепостить',
	'_wall_txt_reposted_by' => 'Зарепостили',
	'_wall_txt_err_cannot_repost' => 'Не возможно зарепостить. Пожалуйста свяжитесь с администратором.',
	'_wall_txt_err_already_reposted' => 'Вы уже зарепостили данное сообщение.',
	'_wall_txt_msg_success_repost' => '',
	'_wall_reposted_text' => 'зарепостил текст',
	'_wall_reposted_title_text' => '{0} зарепостил текст',
    '_wall_reposted_link' => 'зарепостил ссылку',
	'_wall_reposted_title_link' => '{0} зарепостил ссылку',
    '_wall_reposted_photos' => 'зарепостил фото',
	'_wall_reposted_title_photos' => '{0} зарепостил фото',
    '_wall_reposted_videos' => 'зарепостил видео',
	'_wall_reposted_title_videos' => '{0} зарепостил видео',
    '_wall_reposted_sounds' => 'зарепостил аудио',
	'_wall_reposted_title_sounds' => '{0} зарепостил аудио',
	'_wall_reposted_profile_comment_add' => 'зарепостил комментарий к профилю',
	'_wall_reposted_title_profile_comment_add' => '{0} зарепостил комментарий к профилю',
	'_wall_reposted_profile_edit' => 'зарепостил изменение провиля',
	'_wall_reposted_title_profile_edit' => '{0} зарепостил изменение провиля',
	'_wall_reposted_profile_edit_status_message' => 'зарепостил изменение статуса профиля',
	'_wall_reposted_title_profile_edit_status_message' => '{0} зарепостил изменение статуса профиля',
	'_wall_reposted_friend_accept' => 'зарепостил принятие профилем запроса на дружбу',
	'_wall_reposted_title_friend_accept' => '{0} зарепостил принятие профилем запроса на дружбу'
);
