<?php

$aLangContent = array(

  // ================ ADDED KEYS ==================

  '_CategoriesSettings' => 'Categories Settings',
  '_Edit_profile_and_settings' => 'Edit profile info and settings',
  '_Enter what you see' => 'Enter what you see',
  '_Map' => 'Map',
  '_Member Friends Mutual' => 'Mutual Friends',
  '_Member Friends Requests' => 'Friend Requests',
  '_Members_adm_stats' => 'Pending Members',
  '_Message' => 'Message',
  '_Period_hours' => 'Period (hours)',
  '_RSS' => 'RSS',
  '_Remove Fave' => 'Unfave',
  '_Search...' => 'Search...',
  '_Subscribe_block_caption' => 'Newsletter',
  '_Subscribers' => 'Subscribers',
  '_Template' => 'Template',
  '_User was added to favourites' => 'User was added to favourites',
  '_User was removed from favourites' => 'User was removed from favourites',
  '__Burma' => 'Burma',
  '_adm_admtools_phpinfo' => 'PHP Info',
  '_adm_bann_clicks_chart' => 'Banner Clicks',
  '_adm_bmbuilder_box_title' => 'Bottom Menu Builder',
  '_adm_bmbuilder_page_title' => 'Bottom Menu Builder',
  '_adm_box_cpt_charts' => 'Growth Charts',
  '_adm_box_cpt_content' => 'Content',
  '_adm_box_cpt_help' => 'Initial Steps',
  '_adm_box_cpt_license' => 'Current License',
  '_adm_box_cpt_mlevel_memberships' => 'Memberships',
  '_adm_box_cpt_splash' => 'Splash',
  '_adm_charts_date_from' => 'from',
  '_adm_charts_date_to' => 'to',
  '_adm_charts_select' => 'Display new',
  '_adm_dsc_settings_splash_editor' => 'HTML Editor may break some code',
  '_adm_ipbl_manage' => 'Manage',
  '_adm_license_continue' => 'or <a href="{0}">continue trial</a>',
  '_adm_license_note_permanent' => 'Commercial License',
  '_adm_license_note_unregistered' => '<a href="http://www.boonex.com/paymentprovider/payment"><b>Buy a license</b></a> to remove BoonEx links and trial alerts.',
  '_adm_license_popup_continue' => 'continue trial',
  '_adm_license_popup_license' => 'License:',
  '_adm_license_popup_note' => 'Trial copy! <b><a href="http://www.boonex.com/paymentprovider/payment">Get a license</a></b> and register it:',
  '_adm_license_popup_or' => 'or',
  '_adm_license_popup_register' => 'Register',
  '_adm_license_register' => 'Register',
  '_adm_license_register_new' => 'Register a new license',
  '_adm_license_trial_copy_login_text' => 'This is a trial copy of Dolphin software. <a href="http://www.boonex.com/paymentprovider/payment" target="_blank">Get a license from BoonEx.</a>',
  '_adm_license_unregistered' => 'Trial',
  '_adm_license_warning' => 'Are you sure you want to register a new license? The old license will be deleted!',
  '_adm_mmi_bottom_menu' => 'Bottom Menu',
  '_adm_mmi_cache' => 'Cache',
  '_adm_mmi_dashboard' => 'Dashboard',
  '_adm_mmi_license' => 'License',
  '_adm_mmi_manage_modules' => 'Add & Manage',
  '_adm_mmi_service_menu' => 'Service Menu',
  '_adm_mmi_sitemap' => 'Sitemap',
  '_adm_mmi_templates' => 'Templates',
  '_adm_mobile_page_search' => 'Search',
  '_adm_page_cpt_license' => 'License',
  '_adm_page_cpt_settings_advanced' => 'Advanced Settings',
  '_adm_page_cpt_settings_basic' => 'Basic Settings',
  '_adm_pbuilder_Info_Cache' => 'In seconds, 0 - disable cache',
  '_adm_smbuilder_box_title' => 'Service Menu Builder',
  '_adm_smbuilder_page_title' => 'Service Menu Builder',
  '_adm_tmi_info' => 'Documentation',
  '_adm_txt_cache' => 'Cache',
  '_adm_txt_clear_cache' => 'Clear Cache',
  '_adm_txt_dashboard_cache_css' => 'CSS',
  '_adm_txt_dashboard_cache_js' => 'JavaScript',
  '_adm_txt_dashboard_cache_member_menu' => 'Member Menu',
  '_adm_txt_dashboard_help' => '
<ol class="adm-ds-help bx-def-font-large">
    <li>
        Change the site logo to your own
        <a href="{0}basic_settings.php">here</a>
        <a target="_blank" href="http://www.boonex.com/trac/dolphin/wiki/TutorialHowToPersonalizeYourDolphinSite#point2"><i class="sys-icon question-sign"></i></a>
    </li>
    <li>
        <a target="_blank" href="http://www.google.com/recaptcha">Generate your own Captcha keys</a> and fill them in
        <a href="{0}advanced_settings.php?c=Security">here</a>
    </li>
    <li>
        Write your own copyright notice text
        <a href="{0}lang_file.php">here</a>
        <a target="_blank" href="http://www.boonex.com/trac/dolphin/wiki/TutorialHowToPersonalizeYourDolphinSite#point5"><i class="sys-icon question-sign"></i></a>
    </li>
    <li>
        Change \'about\' and other information pages text
        <a href="{0}lang_file.php">here</a>
        <a target="_blank" href="http://www.boonex.com/trac/dolphin/wiki/TutorialHowToPersonalizeYourDolphinSite#point12"><i class="sys-icon question-sign"></i></a>
    </li>
    <li>
        Install modules of your choice
        <a href="{0}modules.php">here</a>
        <a target="_blank" href="http://www.boonex.com/trac/dolphin/wiki/DolphinAdminModules"><i class="sys-icon question-sign"></i></a>
    </li>
    <li>
        If using Facebook Connect, Generate your own Facebook keys and fill them in
        <a href="{1}modules/?r=facebook_connect/administration/">here</a>
    </li>
    <li>
        Build your site homepage blocks
        <a href="{0}pageBuilder.php?Page=index">here</a>
        <a target="_blank" href="http://www.boonex.com/trac/dolphin/wiki/DolphinAdminPagesBlocks"><i class="sys-icon question-sign"></i></a>
    </li>
    <li>
        Setup site permissions settings
        <a href="{0}memb_levels.php">here</a>
        <a target="_blank" href="http://www.boonex.com/trac/dolphin/wiki/DolphinAdminMembershipLevels"><i class="sys-icon question-sign"></i></a>
    </li>
    <li>
        When ready to buy a full license, order it
        <a target="_blank" href="http://www.boonex.com/paymentprovider/payment">here</a>
    </li>
    <li>
        Register your license <a href="{0}license.php">here</a>
    </li>
</ol>',
  '_adm_txt_dashboard_help_dont_show' => 'Don\'t show it anymore',
  '_adm_txt_dashboard_update_now' => 'now!',
  '_adm_txt_default' => 'Default',
  '_adm_txt_email_list' => 'Templates',
  '_adm_txt_email_settings' => 'Settings',
  '_adm_txt_langs_keys' => 'Keys',
  '_adm_txt_langs_languages' => 'Languages',
  '_adm_txt_langs_languages_add' => 'Add Language',
  '_adm_txt_langs_languages_import' => 'Import Language',
  '_adm_txt_langs_settings' => 'Settings',
  '_adm_txt_list' => 'List',
  '_adm_txt_make_default' => 'Make Default',
  '_adm_txt_manage' => 'Manage',
  '_adm_txt_mlevels_levels' => 'Levels',
  '_adm_txt_mlevels_levels_add' => 'Add Level',
  '_adm_txt_mlevels_price_exists' => 'Similar pricing option already exists',
  '_adm_txt_mlevels_settings' => 'Settings',
  '_adm_txt_modules_destination_not_valid' => 'Destination FTP folder doesn\'t look like valid Dolphin root folder',
  '_adm_txt_modules_ftp_copy_failed' => 'FTP transfer failed, please check write permission for this FTP user',
  '_adm_txt_modules_params_used' => 'A module with similar unique parameters is already installed.',
  '_adm_txt_modules_zip_not_available' => 'ZIP functions aren\'t available, please check server requirements',
  '_adm_txt_settings_splash_editor' => 'Enable HTML Editor',
  '_adm_txt_settings_splash_logged' => 'Hide for logged in users',
  '_adm_txt_settings_splash_visibility' => 'Visibility',
  '_adm_txt_settings_splash_visibility_all' => 'show on all pages',
  '_adm_txt_settings_splash_visibility_disable' => 'disable',
  '_adm_txt_settings_splash_visibility_index' => 'show on homepage',
  '_adm_txt_settings_splash_warning' => 'Note, that improper use of HTML may break the site layout.',
  '_adm_txt_templ_alt_desc' => 'Alternative template with slightly different color scheme and background image. ALT is an example of how only a few basic changes to UNI template can create different "feel".',
  '_adm_txt_templ_uni_desc' => 'The default template for Dolphin, universally suitable for variety of social networking website niches. UNI is optimized for large screen resolutions and features minimalistic layout with vector-based icons (good for "retina" screens).',
  '_adm_txt_template_preview_na' => 'Preview Not Available',
  '_adm_txt_templates' => 'Templates',
  '_edit_available_for_N_seconds' => 'Edit available for <span><b>{0}</b></span> seconds',
  '_month_next_mini' => 'Next Mon ›',
  '_month_prev_mini' => '‹ Prev Mon',
  '_sys_add_content' => 'Add New ...',
  '_sys_album_caption_new' => '{0} ({1})',
  '_sys_album_create_new' => 'Create New Album...',
  '_sys_album_edit_info' => '<a href="{0}">Edit album</a> to change privacy.',
  '_sys_album_privacy_me_info' => 'This album privacy is set to "Me Only".',
  '_sys_album_private' => 'Private Album',
  '_sys_am_account_profile_page' => 'My Profile',
  '_sys_am_mailbox_compose' => 'New Message',
  '_sys_am_profile_account_page' => 'My Account',
  '_sys_am_profile_friend_accept' => 'Accept Friend Request',
  '_sys_am_profile_friend_add' => 'Add Friend',
  '_sys_am_profile_friend_cancel' => 'Unfriend',
  '_sys_am_profile_message' => 'Message',
  '_sys_bcpt_member_account_control' => 'Account Control',
  '_sys_bcpt_member_friend_requests' => 'Friend Requests',
  '_sys_bcpt_member_new_messages' => 'New Messages',
  '_sys_block_title_social_sharing' => 'Recommend',
  '_sys_bm_design' => 'Design ({0})',
  '_sys_bm_language' => 'Language ({0})',
  '_sys_bm_popup_cpt_design' => 'Select Design',
  '_sys_bm_popup_cpt_language' => 'Select Language',
  '_sys_calendar' => 'Calendar',
  '_sys_city_country_format' => '{0}, {1}',
  '_sys_cnts_bcpt_connections' => 'Connections',
  '_sys_cnts_bcpt_fave' => 'Favourites',
  '_sys_cnts_bcpt_fave_remove' => 'Remove from Favourites',
  '_sys_cnts_bcpt_friend_requests' => 'Friend Requests',
  '_sys_cnts_btn_fave' => 'Fave',
  '_sys_cnts_btn_fr_accept' => 'Accept',
  '_sys_cnts_btn_fr_reject' => 'Reject',
  '_sys_cnts_msg_fr_empty' => 'No friend requests. Get pro-active and <a href="browse.php">look for new friends</a>.',
  '_sys_cnts_txt_blocked' => 'Blocked',
  '_sys_cnts_txt_favorites' => 'Favorites',
  '_sys_cnts_txt_frients' => 'Friends',
  '_sys_cnts_txt_mf_no' => 'No',
  '_sys_cnts_txt_mutual_friends' => '{0} Mutual Friends',
  '_sys_email_footer_info' => 'To unsubscribe - login to your account, edit your profile and uncheck \'Receive site notifications\'.',
  '_sys_member_info_age_sex' => 'Age + Sex',
  '_sys_member_info_first_name' => 'First Name',
  '_sys_member_info_first_name_last_name' => 'First Name + Last Name',
  '_sys_member_info_headline' => 'Headline',
  '_sys_member_info_last_name_firs_name' => 'Last Name + First Name',
  '_sys_member_info_location' => 'Location',
  '_sys_member_info_status_message' => 'Status Message',
  '_sys_member_info_username' => 'Username',
  '_sys_member_thumb_avatar' => 'Avatar',
  '_sys_member_thumb_icon_avatar' => 'Avatar Icon',
  '_sys_mobile_search_by_keyword' => 'Search By Keyword',
  '_sys_mobile_search_by_location' => 'Location Search',
  '_sys_save_nothing' => 'Nothing was changed',
  '_sys_sitemap' => 'Sitemap',
  '_sys_sitemap_desc' => '<p>Sitemaps are an easy way to inform search engines about pages on you site that are available for crawling.
Once you activated sitemap and it was generated, you need to inform the search engines that your site supports sitemaps.
</p>
<p>
You can do this by:
</p>
<ul>
    <li>
        <b>submiting it via the search engine\'s submission interface:</b>
        please refer to particular search engine\'s documentation on how to do this.
    </li>
    <li>
        <b>specifying it in robots.txt file:</b>
        simply add the following line to <b>robots.txt</b> file:
        <pre class="code">Sitemap: {0}</pre>
    </li>
</ul>',
  '_sys_sitemap_form_caption' => 'Enable sitemap generation',
  '_sys_sitemap_form_caption_sitemap_generated' => 'Sitemap file is generated',
  '_sys_sitemap_list' => 'The following content pages are included in sitemap:',
  '_sys_sitemap_profiles' => 'Profiles',
  '_sys_sitemap_profiles_info' => 'Profile Info Pages',
  '_sys_sitemap_system' => 'System Pages',
  '_sys_sm_account' => 'Account',
  '_sys_sm_join' => 'Join',
  '_sys_sm_login' => 'Login',
  '_sys_sm_logout' => 'Logout',
  '_sys_sm_profile' => 'Profile',
  '_sys_status_default' => 'Your status message is here',
  '_sys_status_update' => 'update status',
  '_sys_top_menu_more' => 'More',
  '_sys_txt_ac_manage_subscriptions' => '<a href="member_subscriptions.php">Manage Subscriptions</a>',
  '_sys_txt_btn_loading' => 'Loading...',
  '_sys_txt_captcha_not_available' => 'Security image is not available',
  '_sys_txt_form_toggle_html_editor' => 'Toggle HTML Editor',
  '_sys_upload' => 'Upload',
  '_sys_media_disapproved' => 'File not approved yet',
  '_sys_media_processing' => 'File not processed yet',
  '_sys_media_not_found' => 'File not found',
  '_sys_x_byte' => '{0} bytes',
  '_sys_x_gigabyte' => '{0} Gb',
  '_sys_x_kilobyte' => '{0} Kb',
  '_sys_x_megabyte' => '{0} Mb',
  '_sys_x_terabyte' => '{0} Tb',
  '_tomorrow' => 'Tomorrow',
  '_week_fri_mini' => 'Fr',
  '_week_mon_mini' => 'Mo',
  '_week_sat_mini' => 'Sa',
  '_week_sun_mini' => 'Su',
  '_week_thu_mini' => 'Th',
  '_week_tue_mini' => 'Tu',
  '_week_wed_mini' => 'We',
  '_yesterday' => 'Yesterday',

  // ================ CHANGED KEYS ==================

  '_ACTION_LIMIT_REACHED' => 'Limit reached. Your current membership (<b>{2}</b>) allows you to {1} no more than {3} times',
  '_ACTION_NOT_ACTIVE' => '<div style="width: 80%">Your account is inactive. <a href="mailto:{7}">Contact us</a> to request account activation to access this feature.</div>',
  '_ADM_PROFILE_SEND_MSG' => 'Your message has been sent.',
  '_ADVICE' => '
<p>"My advice to people today is as follows: if you take the game of life seriously, if you take your nervous system seriously, if you take your sense organs seriously, if you take the energy process seriously, you must turn on, tune in, and drop out."</p>
<p class="bx-def-font-grayed"><i>Timothy Leary</i></p>',
  '_ALREADY_ACTIVATED' => 'Your account is already active..',
  '_ATT_ACTIVE' => '<a href="pedit.php?ID={0}">Edit Profile</a><span class="bullet">·</span><a href="javascript:void(0);" onclick="javascript:loadHtmlInPopup(\'explanation_popup\', \'explanation.php?explain=Active\');">Explanation</a><span class="bullet">·</span><a href="change_status.php">Suspend</a>',
  '_ATT_ACTIVE_E' => 'You are an active member. You can suspend your profile to hide it from others, if needed.',
  '_ATT_APPROVAL' => '<a href="javascript:void(0);" onclick="javascript:loadHtmlInPopup(\'explanation_popup\', \'explanation.php?explain=Approval\');">Info</a>',
  '_ATT_REJECTED' => '<a href="javascript:void(0);" onclick="javascript:loadHtmlInPopup(\'explanation_popup\', \'explanation.php?explain=Rejected\');">Info</a>',
  '_ATT_REJECTED_E' => 'Your profile was rejected by site administrator due to inacceptable or missing information. If you have any questions, please, <a target=_blank href="contact.php">contact us</a>.',
  '_ATT_SUSPENDED' => '<a href="javascript:void(0);" onclick="javascript:loadHtmlInPopup(\'explanation_popup\', \'explanation.php?explain=Suspended\');">Info</a>',
  '_ATT_SUSPENDED_E' => 'Your profile is suspended and is not visible to others. You can activate it <a target=_blank href="change_status.php">here</a>. If you have any questions, please <a target=_blank href="contact.php">contact us</a>.',
  '_ATT_UNCONFIRMED' => '<a href="javascript:void(0);" onclick="javascript:loadHtmlInPopup(\'explanation_popup\', \'explanation.php?explain=Unconfirmed\');">Info</a>',
  '_ATT_UNCONFIRMED_E' => 'Follow the activation link in e-mail we\'ve sent you. <br /><a target=_blank href="activation_email.php">Re-send me the confirmation e-mail</a>.',
  '_Activity' => 'Connections',
  '_CHANGE_STATUS_H1' => 'Suspend/Activate your account',
  '_COMPOSE_H' => 'Write a new message',
  '_COMPOSE_H1' => 'Write and send a message',
  '_CONTACT_H1' => 'Feedback section - questions and comments.',
  '_Can not delete comments with replies' => 'Comments with replies cannot be deleted.',
  '_Captcha check failed' => 'Security image check failed',
  '_Compose new letter' => 'Compose',
  '_Couple profile not found' => 'Couple profile was not found',
  '_Dashboard' => 'Account',
  '_De-Feature it' => 'UnFeature',
  '_EMAIL_CONF_FAILED_EX' => 'This could happen because your web mail service displays web links improperly. If you see this message, please try to <u>exactly</u> copy the link from the confirmation e-mail and paste it into your browser\'s address bar <b>or</b> just enter the confirmation code below:',
  '_EMAIL_CONF_NOT_SENT' => '<b>E-mail has NOT been sent.</b><br />Unfortunately we could not send the confirmation e-mail.e. Please, try again later. We appologize for any inconvenience. <a href="contact.php">Please report this issue to us</a>.',
  '_EMAIL_CONF_SENT' => '<b>E-mail has been successfully sent.</b><br />You should receive it within a minute.',
  '_EMAIL_CONF_SUCCEEDED' => 'Congratulations! Your e-mail is now confirmed.<br /><br />Your profile is created and is awaiting review. Thank you for your patience.',
  '_FAQ_INFO' => '
<h2>How can I upload a primary photo</h2>
<p>Go to Account then click on Avatar.
You will be able to select an Avatar as your primary photo or you can upload a photo from your computer.
If the Photos module is installed, from the View photo page you can set a photo as your Default Avatar.</p>

<h2>How can I edit my profile?</h2>
<p>Go to Account then click Edit Profile.
You will be able to edit your profile details such as Headline, Description, Gender etc.
</p>

<h2>How can I send a private message to a user?</h2>
<p>There are 2 ways you can send a private message to a user
1) Click on the Mail icon in member menu and select Compose.
In the Recipient field, type in the username of the user you want to send a message to.
If the username exists, it will populate as you\'re typing in the Username.
This will help to ensure you type in the correct username.
2) From the users profile you can click Send Letter.</p>

<h2>Can I view messages I have sent?</h2>
<p>Click on the Mail icon in member menu and click Outbox.
This will take you to your Outbox which contains Messages and Greetings you have sent.
You can have just messages display or just Greetings by placing a check mark beside what you want to see.
Removing a check mark beside Messages for example will display everything but Messages and vise versa.</p>

<h2>I accidentally removed the wrong message, can I retrieve it?</h2>
<p>Click on the Mail icon in member menu then click on Trash.
This will display all Messages and Greetings you deleted.
Choose what you want to retrieve and click Restore
The message(s) selected will now be back in your Inbox.</p>

<h2>Are my messages on here permanently unless I delete them?</h2>
<p>To save space on our server and to ensure the site is not running what it doesn\'t need to run, old messages maybe removed periodically.</p>

<h2>How does Subscriptions work?</h2>
<p>When you subscribe to another user, that user\'s profile will be listed in your subscriptions page.
This also applies to subscribing to other users activities such as blogs etc.</p>

<h2>A member keeps harassing me, what can I do?</h2>
<p>If a member of the site is harassing you, Ignore or block that user.
If the problem progresses you should contact the site administrator.</p>

<h2>Why was my account terminated?</h2>
<p>We strictly enforce our Terms Of Service and make every effort possible to make sure all users are following them.
Your account may have been terminated due to a breach in the Terms Of Service (aka TOS).
If you felt that your account was terminated for no probable reason, we ask that you contact the site administrator.</p>

<h2>Why does my profile status say Approval?</h2>
<p>The administrator may have chosen to have profiles approved first before joining the site.</p>

<h2>Why can\'t I log in to my account?</h2>
<p>Chances are you may have misspelled your password or had your CAPS LOCK on while typing your password.
Try typing your password with CAPS LOCK off.
If this fails, you can request a password that will be sent to the email address you provided when you registered.</p>

',
  '_FORGOT' => 'Forgot your ID and/or password? Please, write your e-mail address below and we will send you your account ID and password.',
  '_FREEMAIL_ALREADY_SENT' => 'You have already requested this member\'s contact information for free. You can see it in <a href="profile.php?ID={0}">their profile</a>, or in <a href="communicator.php">your Connections</a>.',
  '_FREEMAIL_ERROR' => 'Sorry, contact information could not be sent to you at this time. Make sure that you are logged in and  your profile is in active mode.',
  '_FREEMAIL_H' => 'Get contact information for free!',
  '_FREEMAIL_NOT_KISSED' => 'You haven\\t recevied greetings from this member.',
  '_FieldCaption_TermsOfUse_Join' => 'I have read and agreed with <a href="terms_of_use.php" target="_blank">Terms of Use</a> and <a href="privacy.php" target="_blank">Privacy Policy</a>.',
  '_FieldDesc_Captcha_Join' => 'Let us check that you are not a robot. Just enter the text you see on the picture.',
  '_FieldDesc_DateOfBirth_Join' => 'Please specify your birth date: Year-Month-Day',
  '_FieldDesc_Password_Join' => 'Choose a password.',
  '_FieldDesc_Tags_Join' => 'Enter a few words separeted by commas that describe your character',
  '_FieldError_DateOfBirth_Max' => 'You cannot join the site if you are older than {0} years',
  '_FieldError_DescriptionMe_Min' => 'Your description should be at least 20 letters long',
  '_FieldError_Email_Check' => 'Please enter correct e-mail',
  '_FieldError_Email_Mandatory' => 'E-mail address is required',
  '_FieldError_Email_Min' => 'Your email is too short',
  '_FieldError_Email_Unique' => 'Accoutn with this email already exists.',
  '_FieldError_Password_Mandatory' => 'Password is required',
  '_FieldError_Sex_Mandatory' => 'Please, specify your gender',
  '_FieldError_zip_Mandatory' => 'Please, specify your ZIP code',
  '_HELP' => '
<p>"If you can dream it, then you can achieve it. You will get all you want in life if you help enough other people get what they want."</p>
<p class="bx-def-font-grayed"><i>Zig Ziglar</i></p>',
  '_Incorrect Captcha' => 'Incorrect Security Image Entry',
  '_Join complete' => 'Joining process has been completed.',
  '_LOGIN_OBSOLETE' => 'Your login information has expired, please re-login.',
  '_LOGIN_REQUIRED_AE2' => 'If you are not registered at {2} you can join right now.<br />',
  '_MEMBERSHIP_EXPIRES_IN_DAYS' => 'expires in {0} day(s)',
  '_MEMBERSHIP_EXPIRES_NEVER' => 'expires never',
  '_MEMBERSHIP_EXPIRES_TODAY' => 'expires today at {0}. (Server time: {1})',
  '_MEMBERSHIP_UPGRADE_FROM_STANDARD' => '<a href="{0}">Upgrade Options</a>',
  '_MEMBER_NOT_RECOGNIZED' => 'Sorry, we could not recognize you. Please, make sure that you entered the e-mail address used when creating your account.',
  '_MEMBER_RECOGNIZED_MAIL_NOT_SENT' => 'You have been recognized as a {0} member, but it was impossible to send you an e-mail with your account details right now. Please, try again later.',
  '_MEMBER_RECOGNIZED_MAIL_SENT' => 'You have been recognized as a {1} member and your account details have just been sent to you. Once you receive the letter from us, <a href="{0}member.php">log-in here</a>.',
  '_Mailbox description empty' => 'Please enter the description',
  '_Mailbox recipient empty' => 'Please enter the recipient\'s nickname',
  '_Mailbox title empty' => 'Please enter the title',
  '_Mark as New' => 'Mark as Unread',
  '_Mark as old' => 'Mark as Read',
  '_Member Friends' => 'Friends',
  '_Membership_starts' => 'Starts<br />immediately',
  '_NO_NEED_TO_CONFIRM_EMAIL' => 'There is no need to confirm your account e-mail because it\'s already confirmed.',
  '_PROFILE_CANT_ACTIVATE/SUSPEND' => 'You can not change your account status.',
  '_PROFILE_CAN_ACTIVATE' => 'You can activate your account to make it visible again.',
  '_PROFILE_CAN_SUSPEND' => 'You can suspend your account, making it temporarily invisible. You can reactivate it later.',
  '_PROFILE_CONFIRM' => 'Congratulations! Your e-mail confirmation succeeded and your profile has been activated.<br />',
  '_RESULT-1_D' => 'We think that what you\'ve done is bad.',
  '_RESULT-1_H' => 'Security breach suspected',
  '_RESULT0' => '<b>The transaction could not proceed.</b> Make sure you have entered your credit card information correctly and try again.',
  '_RESULT0_H' => 'Order failed',
  '_RESULT1_THANK' => 'Thank you! We appreciate your purchase. You should receive an email at {1}',
  '_RESULT2DESC' => 'You have successfully made a purchase, however the e-mail with contact information could not be sent to you right now. Your purchase has been recorded and you can see all the information in <a href="communicator.php">your Connections</a>.',
  '_Remove friend' => 'Unfriend',
  '_Report about spam failed to sent' => 'Spam report could not be sent',
  '_Send virtual kiss' => 'Send a greeting',
  '_USER_CONF_SUCCEEDED' => 'Congratulations! Your account has been successfully confirmed.<br /><br />Your profile has been successfully created, but it is awaiting review. Thank you for your patience.',
  '_VIEW_MEMBERSHIP_ACTIONS' => 'Allowed Actions',
  '_adm_admtools_Bad_files' => 'The following files and directories have inappropriate permissions',
  '_adm_admtools_Only_bad_files' => 'Show only files and directories with inappropriate permissions',
  '_adm_box_cpt_email_templates' => 'Email Templates',
  '_adm_box_cpt_mp_controls' => 'Overview',
  '_adm_box_cpt_pvalues_manage' => 'Predefined Values',
  '_adm_dbtools_Data_succefully_restored_from_PC' => 'Data successfully restored',
  '_adm_dbtools_Data_succefully_restored_from_dump' => 'Data successfully restored from server',
  '_adm_fields_maximum_exceed_error_message' => 'Maximum exceeded error message',
  '_adm_mmail_Cupid_mails_status' => 'Cupid mail status',
  '_adm_mmail_title' => 'Massmailer',
  '_adm_mmi_pages_blocks' => 'Pages Builder',
  '_adm_page_cpt_lang_file' => 'Language Settings',
  '_adm_page_cpt_memb_levels' => 'Membership Levels',
  '_adm_page_cpt_pvalues_manage' => 'Predefined Values',
  '_adm_pbuilder_Caption_Cache' => 'Cache',
  '_adm_tmi_extensions' => 'Add Modules',
  '_adm_txt_hosting_text' => '90% of configuration and installation issues result from incorrect hosting setup. BoonEx constantly works with a number of quality hosts and we recommend the best ones. Moreover, BoonEx customers generally receive better deals and accounts tailored specifically for Dolphin.',
  '_adm_txt_modules_already_installed' => 'The module is already installed.',
  '_adm_txt_modules_already_uninstalled' => 'The module is already uninstalled.',
  '_adm_txt_modules_process_action_failed' => 'An error occurred. Contact with module\'s vendor.',
  '_adm_txt_modules_success_delete' => 'The package(s) was successfully deleted',
  '_allow_view_to' => 'Who can<br />see you',
  '_in_x_day' => 'In {0} Days',
  '_pending_friend_request' => 'Your friend request is awaiting confirmation',
  '_pending_friend_request_answer' => '<a href="{0}">Click here</a> to respond to the friend request.',
  '_powered_by_Dolphin' => 'Our website is powered by <a href="http://www.boonex.com/dolphin">BoonEx Dolphin</a>. Anyone can create their own niche social network using BoonEx software.',
  '_ps_bcpt_create_group' => 'Create a New Privacy Group',
  '_ps_pcpt_privacy_settings' => 'Privacy Groups',
  '_ps_tmenu_privacy_settings' => 'Privacy Groups',
  '_sbd_Android_desc' => 'Have an Android device?\\r\\nAccess our site on your handset!',
  '_sbd_iPhone_desc' => 'Have an iPhone, iPod or iPad?\\r\\nAccess our site on your iOS device!',
  '_sbd_iPhone_title' => 'iOS App',
  '_sbs_txt_sbs_profile' => '{0}',
  '_sbs_txt_sbs_profile_comments' => '{0} (New Profile Comments)',
  '_sbs_txt_sbs_profile_edit' => '{0} (New Profile Updates)',
  '_sbs_txt_title_profile' => 'Profile',
  '_sbs_txt_title_system' => 'System',
  '_sbs_wrn_email_notify_disabled' => 'You will not receive any subscription emails because you have chosen to not receive any site notifications. You can change this setting <a href="{0}">here</a>.',
  '_sys_mobile_info' => 'My Info',
  '_sys_profile_private_text' => 'Information availability is limited by member privacy.',
  '_sys_txt_sbs_already_subscribed' => 'You are already subscribed to this content.',
  '_sys_txt_sbs_already_unsubscribed' => 'You are not subscribed to this content.',
  '_sys_txt_sbs_empty_name_email' => 'Enter your name and correct email address.',
  '_tags_err_keyword' => 'Specify keywords, 1 to 100 letters',
  '_x_day_ago' => '{0} Days Ago',

  // ================ DELETED KEYS (commented because processed via SQL file) ==================

  /*
  '_(available for <span>N</span> seconds)' => '(available for <span>{0}</span> seconds)',
  '_<- Remove' => '<- Remove',
  '_AFFILIATES' => '<div class="affiliates_cont">
<div class="affiliates_snippet">
We offer commissions for webmasters who refer visitors to our site. Go to <a href="{0}join_aff.php">sign up page</a> to become an affiliate.
</div>
</div>',
  '_AFFILIATES_H' => 'Affiliates',
  '_AFFILIATES_H1' => 'Affiliates',
  '_ATT_FRIEND' => 'A <b><a href="{0}communicator.php?communicator_mode=friends_list">New Friend</a></b> is waiting for you!',
  '_ATT_FRIEND_NONE' => 'No new friends (<a href="{0}communicator.php?communicator_mode=friends_list">go to my friends</a>)',
  '_ATT_MESSAGE' => 'A <b><a href="{1}mail.php?mode=inbox">New message</a></b> is waiting for you!',
  '_ATT_MESSAGE_NONE' => 'No new messages (<a href="{0}mail.php?mode=inbox">go to inbox</a>)',
  '_ATT_VKISS' => 'A <b><a href="{0}communicator.php?communicator_mode=greeting_requests&person_switcher=to">New greeting</a></b> is waiting for you!',
  '_ATT_VKISS_NONE' => 'No new greetings (<a href="{0}communicator.php?communicator_mode=greeting_requests&person_switcher=from">go to my greetings</a>)',
  '_About is required' => 'Group title is required',
  '_Accept' => 'Accept',
  '_Account Control' => 'Account Control',
  '_Account settings' => 'Account settings',
  '_Ad of the Day' => 'Ad of the Day',
  '_Add ->' => 'Add ->',
  '_Add comment' => 'Add comment',
  '_Add member' => 'Add member',
  '_Add record' => 'Add record',
  '_Add story' => 'Add feedback',
  '_Add to Friend List' => 'Accept Invite',
  '_Add to Hot List' => 'Add to Hot List',
  '_Admin_Links' => 'Admin Links',
  '_Advanced Search' => 'Advanced Search',
  '_Advanced search' => 'Advanced search',
  '_Affiliate' => 'Affiliate',
  '_Affiliate Program' => 'Affiliate Program',
  '_Affiliates' => 'Affiliates',
  '_Aged from' => 'Aged from',
  '_Alerts' => 'Alerts',
  '_Alerts settings' => 'Alerts settings',
  '_All Videos' => 'All Videos',
  '_All friends' => 'All friends',
  '_All members' => 'All members',
  '_All_Cards' => 'All Cards',
  '_All_Sites' => 'All Sites',
  '_All_Users' => 'All Users',
  '_AllowAlbumView' => 'allow view album',
  '_Approval' => 'Approval',
  '_Are you sure want to delete this image?' => 'Are you sure you want to delete this image?',
  '_Background color' => 'Background color',
  '_Background picture' => 'Background picture',
  '_Blocked Me' => 'Blocked Me',
  '_Blocked, Viewed, etc' => 'Blocked, Viewed, etc',
  '_BoonEx Community Software Experts' => 'BoonEx Community Software Experts',
  '_By Author' => 'Author: <b><a href="{0}">{0}</a></b>',
  '_CHECKOUT_H' => 'Check out',
  '_COMPOSE_REJECT_MEMBER_NOT_FOUND' => 'Recipient not found',
  '_COMPOSE_STORY_H' => 'Feedback',
  '_COMPOSE_STORY_H1' => 'Feedback',
  '_COMPOSE_STORY_VIEW_H' => 'View Feedback',
  '_COMPOSE_STORY_VIEW_H1' => 'View Feedback',
  '_Cards' => 'Cards',
  '_Cards_Calendar' => 'Calendar',
  '_Cards_Categories' => 'Categories',
  '_Cards_Home' => 'Cards Home',
  '_Cast my vote' => 'Cast my vote',
  '_Category Caption' => 'Category Caption',
  '_Category Deleted Successfully' => 'Category Deleted Successfully',
  '_Category are not deleted' => 'Category not deleted',
  '_Category is required' => 'Category is required',
  '_Change Password' => 'Change Password',
  '_Charges number' => 'Charges number',
  '_ChatNow' => 'Chat Now',
  '_Check Out' => 'Check Out',
  '_Check all' => 'Check all',
  '_Choose forum' => 'Choose forum',
  '_Choose module type' => 'Choose module type',
  '_Choose_membership' => ' You may choose your membership status',
  '_City is required' => 'City is required',
  '_Clear' => 'Clear',
  '_Click to Play/Pause' => 'Click to Play/Pause',
  '_Click_here_to_update_your_status' => 'Click here to update your status message',
  '_Communicator' => 'Communicator',
  '_Compose new message' => 'Compose new message',
  '_Confirm E-mail' => 'Confirm E-mail',
  '_Confirm your e-mail' => 'Confirm your e-mail',
  '_Confirm your password' => 'Confirm your password',
  '_Congratulation' => '<font color=red>Congratulations!!!</font><br />',
  '_Contacts' => 'Contacts',
  '_Country is required' => 'Country is required',
  '_Created' => 'Founded',
  '_Credit card number' => 'Credit card number',
  '_Custom' => 'Custom',
  '_Customize Profile' => 'Customize Profile',
  '_DateOfBirth' => 'Age',
  '_DateOfBirth_err_msg' => 'Your age doesn\'t allow access to this site',
  '_DateOfBirth_lbl' => 'Date of birth',
  '_Day' => 'Day',
  '_Delete from Friend List' => 'Delete from Friend List',
  '_DescriptionMedia' => 'Description',
  '_Disabled' => 'Disabled',
  '_Dolphin Smart Community Builder' => 'Dolphin Smart Community Builder',
  '_EMAIL_INVALID_AFF' => 'E-mail address doesn\'t seem to be valid.',
  '_Edit members' => 'Edit members',
  '_Edit profile info' => 'Edit profile info',
  '_Enter member NickName or ID' => 'Enter member Username or ID',
  '_Enter profile ID' => 'Enter profile ID',
  '_Enter search parameters' => 'Enter search parameters',
  '_Enter what you see:' => 'Enter what you see:',
  '_Existed_RSS' => 'Existing RSS',
  '_Explanation' => 'Explanation',
  '_FAILED_TO_DELETE_PIC' => 'Failed to delete picture.<br /><div class=small>(Error code: {0})</div>',
  '_FAILED_TO_UPLOAD_PIC' => 'Failed to upload file <b>{0}</b>! Make sure it\'s a picture in <b>jpg</b>, <b>gif</b>, or <b>png</b> format.<br /><div class=small>(Error code: {1})</div><br /><br />',
  '_Fail to sent subscription cancellation request' => 'Failed to send subscription cancellation request',
  '_Favorited' => 'Favorited',
  '_Featured Posts' => 'Featured Posts',
  '_Feedback' => 'Feedback',
  '_Fetch' => 'Search',
  '_File already is favorite' => 'File already is a favorite',
  '_File upload error' => 'File upload error',
  '_File was added to favorite' => 'File was added to favorite',
  '_File was deleted' => 'File was deleted',
  '_File was uploaded' => 'File was uploaded successfully',
  '_Find' => 'Find',
  '_Find more...' => 'Find more...',
  '_Flag' => 'Flag',
  '_Font color' => 'Font color',
  '_Font family' => 'Font family',
  '_Font size' => 'Font size',
  '_Friends tracker' => 'Friends tracker',
  '_GETMEM_H' => 'Get membership',
  '_GETMEM_H1' => 'Get new membership',
  '_Gallery upload_desc' => 'You must choose a file with .jpeg, .gif, .png extensions.',
  '_General self-description' => 'General self-description',
  '_Get BoonEx ID' => 'Get BoonEx ID',
  '_Go to Mailbox' => 'Go to Mailbox',
  '_Google_Site_Search' => 'Google Site Search',
  '_Got_members_part_1' => 'You\'ve got ',
  '_Got_members_part_2' => ' member(s) engaged. ',
  '_Got_new_membership_part_1' => '<center>Congratulations!!!<br />You\'re a <font color=red>',
  '_Got_new_membership_part_2' => ' </font>member now. Your membership will expire in ',
  '_Got_new_membership_part_3' => ' days.</center>',
  '_Greeted me' => 'Greeted me',
  '_Hacker String' => 'This may be a hacker string',
  '_Hot list' => 'Hot list',
  '_Hot lists' => 'Hot lists',
  '_I Blocked' => 'I Blocked',
  '_I agree' => 'I agree',
  '_I am a' => 'I am a',
  '_ICQ' => 'ICQ',
  '_IM now' => 'IM {0} now!',
  '_INBOX_H' => 'My Inbox',
  '_INBOX_H1' => 'Inbox',
  '_INCORRECT_EMAIL' => 'The e-mail you entered doesn\'t seem to be valid. Please try again.',
  '_Import' => 'Import',
  '_Import BoonEx ID' => 'Import BoonEx ID',
  '_Invalid module type selected.' => 'Invalid module type selected',
  '_Invite list' => 'Invite list',
  '_Invite others' => 'Invite others',
  '_Invites succesfully sent' => 'Invites successfully sent',
  '_JOIN1_AFF' => 'Go here to become an affiliate of this site for free.<br /><br />',
  '_JOIN_AFF2' => 'Congratulations! You are an affiliate of {1} now. You can login <a href="{0}">here</a>',
  '_JOIN_AFF_H' => 'Affiliate sign up',
  '_JOIN_AFF_ID' => 'Use <font color=red><b>{0}</b></font> ID number for login, please do not forget your ID number',
  '_Join Now Top' => 'Join Now',
  '_Kisses' => 'Greetings',
  '_LINKS_H' => '{0} Links',
  '_LINKS_H1' => '{0} Links',
  '_LOGIN_ERROR' => 'Login error. Try again:',
  '_Latest files from this user' => 'Latest files from this user',
  '_Leaders' => 'Leaders',
  '_License Agreement' => 'The terms of the Agreement in a nutshell:
1. You have permission to upload the material, or you have obtained permission from the relevant rights holder(s).
2. {0} may use your material for its content and you have the right to provide this material for free downloads.
3. The list of PROHIBITED actions.

1. LICENSED MATERIAL
When uploading licensed material you confirm that you have the right or permission to upload it. You confirm that your material can be used by you and has not been stolen. You are only responsible for the uploaded material and, in case someone declares that the material has been stolen and will provide us with all the license documents, {0} has the right to remove your files and provide the material owner with your contact information.

2. GRANTING OF LICENSE

When uploading the material, you provide {0} and its members with the right to use it. You understand that our site is an open site, therefore you agree that the material uploaded by you can be downloaded and used by other site members. {0} isn’t responsible for the usage of your material on third party sites.

3. STRONGLY PROHIBITED

- Media files having negative or any other psychological or mental influence.
- Media files containing children\'s porno.
- Media containing naked views of you or your children.
If you do not agree with these stipulations, you may not upload any media files.',
  '_Lifetime' => 'Lifetime',
  '_Links' => 'Links',
  '_Log Out2' => 'Logout',
  '_MEDIA_GALLERY_H' => 'profile media gallery',
  '_MEMBERSHIP_BUY_MORE_DAYS' => 'extend membership period',
  '_MEMBERSHIP_H' => 'Membership',
  '_MEMBERSHIP_H1' => 'View status/upgrade your membership',
  '_MEMBERSHIP_STANDARD' => 'You are a standard member.',
  '_MEMBERS_YOU_VIEWED' => 'Members you have viewed',
  '_MEMBERS_YOU_VIEWED_BY' => 'Members who viewed you',
  '_Member menu settings' => 'Member menu settings',
  '_Member succesfully approved' => 'Member has been successfully approved',
  '_Member succesfully rejected' => 'Member has been rejected',
  '_Members count' => 'Members',
  '_Membership NEW' => 'Available Membership Types',
  '_Membership Status' => 'Membership Status',
  '_Membership purchase' => 'Membership purchase',
  '_Message successfully deleted' => 'Message successfully deleted',
  '_Moderator' => 'Moderator',
  '_Module directory was not set. Module must be re-configurated' => 'Module directory was not set. Module must be re-configured.',
  '_Module selection' => 'Module selection',
  '_Module type selection' => 'Module type selection',
  '_Module_access_error' => 'Module access error',
  '_Month' => 'Month',
  '_Must be valid' => 'Must be valid',
  '_My Contacts' => 'My Contacts',
  '_My Mail' => 'My Mail',
  '_My Membership' => 'My Membership',
  '_My Profile' => 'My Profile',
  '_My Settings' => 'My Settings',
  '_My Videos' => 'My Videos',
  '_My account' => 'My account',
  '_My info' => 'My Info',
  '_NEWS_H' => 'News',
  '_NICK_LEAST2' => 'Username must be from {0} to {1} characters long.',
  '_NOT_RECOGNIZED' => 'You are NOT recognized as a {0} member',
  '_NO_LINKS' => 'No links available',
  '_NO_RESULTS' => '<b>No results found.</b> <br /> <a href="search.php">Start again</a> and try to broaden your search.',
  '_NO_STORIES' => 'No feedback available',
  '_Need_more_members' => '(Need more members engaged to get new membership status )',
  '_New Message' => 'New message',
  '_New Today' => 'New Today',
  '_Nickname' => 'Username',
  '_No actions allowed for this membership' => 'No actions allowed for this membership',
  '_No file' => 'Requested File Doesn\'t Exist',
  '_No members found here' => 'No members found here',
  '_No messages in Inbox' => 'No messages in Inbox',
  '_No messages in Outbox' => 'No messages in Outbox',
  '_No modules found' => 'No modules found',
  '_No modules of this type installed' => 'No modules of this type installed',
  '_No news available' => 'No news available',
  '_No success story available.' => 'No feedback available',
  '_No tags found here' => 'No tags found here',
  '_Not Recognized' => 'Not Recognized',
  '_Notification' => 'Notification',
  '_Notification send failed' => 'Notification email send failed',
  '_Notifications' => 'Notifications',
  '_Notifications settings' => 'Notifications settings',
  '_OUTBOX_H' => 'Outbox',
  '_OUTBOX_H1' => 'Outbox',
  '_Open join' => 'Open join',
  '_PWD_INVALID2' => 'Password confirmation failed, make sure that your password is between 5 and 8 characters long.',
  '_PWD_INVALID3' => 'Password confirmation failed',
  '_Pages' => 'Pages',
  '_Payment amount' => 'Payment amount',
  '_Payment description' => 'Payment description',
  '_Payment info' => 'Payment info',
  '_Payment methods' => 'Payment methods',
  '_Period' => 'Period',
  '_Period (hours)' => 'Period (hours)',
  '_Personal information' => 'Personal information',
  '_Playbacks' => 'Playbacks',
  '_Please fill up all fields' => 'Please fill out all fields',
  '_Please login before using Ray chat' => 'Please login before using Ray chat',
  '_Please select at least one search parameter' => 'Please select at least one search parameter',
  '_Possible subscription period' => 'Possible subscription period',
  '_Post a new topic' => 'Post a new topic',
  '_Post topic' => 'Post topic',
  '_Prev' => 'Prev',
  '_Previous rated' => 'Previously rated',
  '_Print As' => 'Print As',
  '_Privacy settings' => 'Privacy settings',
  '_Profile Videos' => 'Profile Videos',
  '_Profile tags' => 'Profile tags',
  '_Profile_Sites' => 'Profile Sites',
  '_Profiles purchase' => 'Profiles purchase',
  '_Profiles tags' => 'Profiles tags',
  '_Quick Search Members' => 'Quick Search Members',
  '_Quick search results' => 'Quick search results',
  '_RESULT-1' => '<b>Transaction verification failed.</b> You seem to have tried to cheat our security system. Your IP has been logged and reported. If you are persistent in your attempts, you will be banned from our system.',
  '_Ray is not enabled. Select <link> another module' => 'Ray is not enabled. Please <a href="{0}">select another module</a>',
  '_Read news in archive' => 'Read news in archive',
  '_Readed' => 'Read',
  '_Reject' => 'Reject',
  '_Reject Invite' => 'Reject Invite',
  '_Related Files' => 'Related Files',
  '_Reload Security Image' => 'Reload Captcha',
  '_Reply to Someone comment' => 'Reply to {0}\'s comment',
  '_Reported' => 'Reported',
  '_SIMG_ERR' => 'Code from security image is incorrect',
  '_STORY_ADDED' => 'Feedback was added',
  '_STORY_ADDED_FAILED' => 'Feedback was not added',
  '_STORY_EMPTY_HEADER' => 'Feedback header is empty',
  '_STORY_UPDATED' => 'Feedback was updated',
  '_STORY_UPDATED_FAILED' => 'Feedback was not updated',
  '_STORY_VIEW_H' => 'Feedback',
  '_STORY_VIEW_H1' => 'Feedback',
  '_Search by' => 'Search by',
  '_Search by ID' => 'Search by ID',
  '_Search by Nickname' => 'Search by Username',
  '_Search by Tag' => 'Search by Tag',
  '_See all music of this user' => 'See all music files of this user',
  '_See all videos of this user' => 'See all videos of this user',
  '_Seeking for a' => 'Seeking a',
  '_Select Category' => 'Select Category',
  '_Select it' => 'Select it',
  '_Select module type' => 'Select module type',
  '_Selected messages' => 'Selected messages',
  '_Send Kiss' => 'greeting',
  '_Send eCard' => 'Send eCard',
  '_Send invites' => 'Send invites',
  '_Send kiss' => 'Greeting',
  '_Send to communicator' => 'to site e-mail',
  '_Send to e-mail' => 'to personal e-mail',
  '_Send virtual kiss2' => 'Greeting sent',
  '_Send virtual kiss3' => 'Greeting NOT sent',
  '_Sender' => 'Sender',
  '_Services' => 'Services',
  '_Set as thumbnail' => 'Set as thumbnail',
  '_Set up your status' => 'Set up your status',
  '_Sex' => 'Sex',
  '_Shoutbox' => 'Shoutbox',
  '_Show <b>N</b>-<u>N</u> of N discussions' => 'Show <b>{0}</b>-<u>{1}</u> of {2} discussions',
  '_Show me' => 'Show me',
  '_Showing results:' => 'Showing results: <b>{0}</b> - <b>{1}</b> of <b>{2}</b>',
  '_Simple Search' => 'Simple Search',
  '_Sites' => 'Sites',
  '_Sites_Calendar' => 'Calendar',
  '_Sites_Categories' => 'Categories',
  '_Sites_Home' => 'Sites Home',
  '_Sorry, no members found' => 'Sorry, no members found',
  '_Sorry, user is OFFLINE' => 'Sorry, but user is OFFLINE at the moment.\\nPlease try later...',
  '_Sorry, you\'re already joined' => 'Sorry, you\'ve already joined',
  '_Sort by' => 'Sort by',
  '_Spy' => 'Spy',
  '_Stories2' => 'Feedback',
  '_Submitted by' => 'Submitted by {0}',
  '_Subscription cancellation request was successfully sent' => 'Subscription cancellation request was successfully sent',
  '_Subscriptions' => 'Subscriptions',
  '_Successfully uploaded' => 'Successfully uploaded!',
  '_Suspended' => 'Suspended',
  '_Tags_Home' => 'Tags Home',
  '_Tags_caption' => 'Tags',
  '_Tags_err_msg' => 'You must enter your Tags',
  '_This Month' => 'This Month',
  '_This Week' => 'This Week',
  '_This Year' => 'This Year',
  '_Total' => 'Total',
  '_Tracker' => 'Tracker',
  '_UPLOAD_MEDIA' => 'UPLOAD MEDIA',
  '_Uncategorized' => 'Uncategorized',
  '_Uncheck all' => 'Uncheck all',
  '_Unopened' => 'Unopened',
  '_Unsubscribe' => 'Unsubscribe',
  '_Untitled' => 'Untitled',
  '_Update story' => 'Update feedback',
  '_Upload File' => 'Upload File',
  '_Upload error' => 'Upload error',
  '_Upload image' => 'Upload image',
  '_Upload succesfull' => 'Image has been successfully uploaded!',
  '_Upload successful' => 'Upload successful',
  '_Uploaded by' => 'Uploaded by',
  '_Uploading' => 'Uploading',
  '_User was added to hot list' => 'User was added to hot list',
  '_User was added to im' => 'User was added to instant messenger',
  '_Users Other Listing' => 'Other listings of this user',
  '_Video' => 'Videos',
  '_Video Info' => 'Video Info',
  '_Videos' => 'Videos',
  '_View Comments' => 'View Comments',
  '_View Profile' => 'view profile',
  '_View all members' => 'View all members',
  '_View all topics' => 'View all topics',
  '_View my profile' => 'View my profile',
  '_View profile' => 'view profile',
  '_Viewed me' => 'Viewed me',
  '_Vote' => 'Vote',
  '_Vote accepted' => 'Vote accepted',
  '_Week' => 'Week',
  '_Welcome_to_the_community' => 'Welcome to the community!',
  '_Where' => 'Where',
  '_Write' => 'Write',
  '_Write new Message' => 'Send once more',
  '_XML Block' => 'XML Block',
  '_Year' => 'Year',
  '_You already voted' => 'You already voted',
  '_You should select correct image file' => 'You should select correct image file',
  '_You should specify at least one member' => 'You should specify at least one member',
  '_You should specify file' => 'You should specify file',
  '_You were approved' => 'You were approved',
  '_You were rejected' => 'You were rejected',
  '_You\'re not creator' => 'You\'re not the creator',
  '_Your friends' => 'Your friends',
  '__Aland Islands' => 'Aland Islands',
  '__Isle of Man' => 'Isle of Man',
  '__Myanmar' => 'Myanmar',
  '__Saint Barthelemy' => 'Saint Barthelemy',
  '__Saint Martin (French part)' => 'Saint Martin (French part)',
  '_about_BoonEx' => 'BoonEx - Community Software;  Dating And Social Networking Scripts; Video Chat And More.',
  '_active_story' => 'Active Story',
  '_add answer' => 'add answer',
  '_add_category' => 'add category',
  '_add_new' => 'add new {0}',
  '_adm-mmi_css_styles' => 'CSS Styles',
  '_adm_admtools_Show_all_files' => 'Show all files and directories',
  '_adm_bann_default' => 'default',
  '_adm_box_cpt_css_edit' => 'Edit CSS File',
  '_adm_box_cpt_email_settings' => 'Settings',
  '_adm_box_cpt_lang_keys' => 'Manage Keys',
  '_adm_box_cpt_lang_settings' => 'Settings',
  '_adm_box_cpt_mlevel_create' => 'Create',
  '_adm_box_cpt_mlevel_edit' => 'Edit',
  '_adm_box_cpt_mlevel_levels' => 'Levels',
  '_adm_box_cpt_mlevel_settings' => 'Settings',
  '_adm_box_cpt_overview' => 'Quick Overview',
  '_adm_box_cpt_promo' => 'Promo',
  '_adm_box_cpt_watermark' => 'Watermark',
  '_adm_btn_css_save' => 'Save',
  '_adm_btn_reset_page' => 'Reset Page',
  '_adm_fields_moderator' => 'Moderator',
  '_adm_mbuilder_Visible_In_Quick_Link' => 'Visible in Quick Links',
  '_adm_mmail_Email_already_in_queue_X' => 'Email({0}) <b><u>{1}</u></b> already exists in queue.<br>',
  '_adm_mmail_notify' => 'notify',
  '_adm_mmi_database_pruning' => 'Database Pruning',
  '_adm_mmi_extensions' => 'Modules',
  '_adm_mmi_manage_subscribers' => 'Manage Subscribers',
  '_adm_mmi_meta_tags' => 'Meta Tags',
  '_adm_mmi_moderation_settings' => 'Moderation Settings',
  '_adm_mmi_permalinks' => 'Permalinks',
  '_adm_mmi_privacy_settings' => 'Privacy Settings',
  '_adm_mmi_tags_settings' => 'Tags Settings',
  '_adm_page_cpt_css_edit' => 'Edit CSS File',
  '_adm_pbuilder_HTML_content' => 'HTML-content',
  '_adm_tmi_boonex_news' => 'Boonex News',
  '_adm_tmi_dashboard' => 'Admin Home',
  '_adm_tmi_docs' => 'Help & Docs',
  '_adm_tmi_menu_builder' => 'Menu Builder',
  '_adm_txt_boonex_promo_text' => 'to remove BoonEx ads from your site and support Dolphin development.',
  '_adm_txt_boonex_promo_title' => 'Purchase a Dolphin license',
  '_adm_txt_css_cannot_write' => 'File {0} is not writable',
  '_adm_txt_css_content' => 'Editing file {0}',
  '_adm_txt_css_failed_save' => 'Fail to save file {0}',
  '_adm_txt_css_file' => 'Select CSS file you want edit',
  '_adm_txt_css_success_save' => 'File {0} was successfully saved',
  '_adm_txt_dashboard_alerts' => 'Alerts',
  '_adm_txt_dashboard_cache_js_css' => 'JS/CSS',
  '_adm_txt_dashboard_change_password' => 'Change Password',
  '_adm_txt_dashboard_extensions' => 'Extensions',
  '_adm_txt_dashboard_last_login' => 'Last login',
  '_adm_txt_dashboard_license' => 'License({0} days left)',
  '_adm_txt_dashboard_license_unlimit' => 'License never expires',
  '_adm_txt_dashboard_mails' => 'My Mails',
  '_adm_txt_dashboard_mails_compose' => 'Compose',
  '_adm_txt_dashboard_mails_inbox' => 'Inbox',
  '_adm_txt_dashboard_mails_sent' => 'Sent letters',
  '_adm_txt_dashboard_mails_trash' => 'Trash',
  '_adm_txt_dashboard_users' => 'Users',
  '_adm_txt_dashboard_users_all' => 'All members',
  '_adm_txt_dashboard_users_unapproved' => 'Unapproved',
  '_adm_txt_dashboard_users_unconfirmed' => 'Unconfirmed',
  '_adm_txt_email_default' => 'default',
  '_adm_txt_go_to_boonex_feed' => 'Go to Boonex Blog',
  '_adm_txt_hot_from_unity_market' => 'Hot Deals from Unity Market',
  '_adm_txt_keys_parameters' => 'String parameters',
  '_adm_txt_langs_available' => 'Languages',
  '_adm_txt_langs_create' => 'Create',
  '_adm_txt_langs_files' => 'List',
  '_adm_txt_langs_import' => 'Import',
  '_adm_txt_mlevels_disabled' => 'disabled',
  '_adm_txt_mlevels_enabled' => 'enabled',
  '_adm_txt_modules_recompile_browse' => 'Recompiling browse:',
  '_adm_txt_modules_recompile_member_stats' => 'Recompiling member statistics:',
  '_adm_txt_pb_enter_name_of_new_page' => 'Enter name of new page',
  '_adm_txt_settings_delete' => 'Delete',
  '_adm_txt_settings_file_cannot_delete' => 'Could not delete file',
  '_adm_txt_settings_promo_browse' => 'Browse',
  '_adm_txt_settings_promo_image' => 'Use image reloader',
  '_adm_txt_settings_promo_text' => 'Use custom HTML block',
  '_adm_txt_settings_promo_uploaded' => 'Uploaded images',
  '_affiliate_system_was_disabled' => 'Affiliate system was disabled',
  '_aged' => 'aged',
  '_answer variants' => 'Answer variants',
  '_block member' => 'block member',
  '_blocked' => 'blocked',
  '_both2' => 'both',
  '_buried' => 'buried',
  '_by keyword' => 'keyword',
  '_by newest' => 'newest',
  '_by popular' => 'popular',
  '_categ_calendar' => 'Calendar',
  '_categ_common' => 'Common Categories',
  '_categ_search' => 'Search',
  '_category_delete_failed' => 'failed to delete the category',
  '_category_deleted' => 'category deleted',
  '_category_successfully_added' => 'category successfully added',
  '_changes_successfully_applied' => 'changes successfully applied',
  '_characters_left' => 'characters left',
  '_chat now' => 'chat now',
  '_children' => 'children',
  '_close window' => 'close window',
  '_comment_added_successfully' => 'comment added successfully',
  '_comments N' => '<img src="{0}" />{1} comments',
  '_contacts' => 'contacts',
  '_controls' => 'controls',
  '_day(s)' => '{0} day(s)',
  '_day_of_1' => '{0} January, {1}',
  '_day_of_10' => '{0} October, {1}',
  '_day_of_11' => '{0} November, {1}',
  '_day_of_12' => '{0} December, {1}',
  '_day_of_2' => '{0} February, {1}',
  '_day_of_3' => '{0} March, {1}',
  '_day_of_4' => '{0} April, {1}',
  '_day_of_5' => '{0} May, {1}',
  '_day_of_6' => '{0} June, {1}',
  '_day_of_7' => '{0} July, {1}',
  '_day_of_8' => '{0} August, {1}',
  '_day_of_9' => '{0} September, {1}',
  '_days ago' => 'days ago',
  '_disable able to rate' => 'Disable rate',
  '_edit_category' => 'edit category',
  '_enable able to rate' => 'Enable rate',
  '_failed_to_add_category' => 'failed to add category',
  '_failed_to_add_comment' => 'failed to add comment',
  '_failed_to_add_post' => 'failed to add post',
  '_faves' => 'faves',
  '_for' => 'for',
  '_free' => 'free',
  '_friend member' => 'friend member',
  '_friends only' => 'friends only',
  '_from ZIP' => 'from ZIP',
  '_from user favorite list' => 'From {0} Favorite List',
  '_get other members emails' => 'get other members\' emails',
  '_greeted' => 'greeted',
  '_hot member' => 'hot member',
  '_hour(s)' => '{0} hour(s)',
  '_hours ago' => 'hours ago',
  '_im_textLogin' => 'Please login first',
  '_im_textNoCurrUser' => 'Please select a user first',
  '_in Category' => '<img src="{0}" alt="" /><a href="{1}">{2}</a>',
  '_in country' => 'in country',
  '_joined' => 'joined',
  '_km' => 'km',
  '_latest news' => 'latest news',
  '_letters' => 'letters',
  '_make it' => 'make it',
  '_make search' => 'make search',
  '_media actions' => 'Media Actions',
  '_member info' => 'member info',
  '_membership' => 'Membership',
  '_messages_from' => 'Messages from {0} to you',
  '_messages_to' => 'Your messages to {0}',
  '_minute(s)' => '{0} minute(s)',
  '_minutes ago' => 'minutes ago',
  '_never' => 'never',
  '_no subject' => 'no subject',
  '_no_info' => 'No info',
  '_no_messages_from' => 'You did not receive any messages from {0}',
  '_no_messages_to' => 'You did not write any messages to {0}',
  '_not_active_story' => 'Inactive Story',
  '_please_select' => 'please select',
  '_post my feedback' => 'post my feedback',
  '_post_successfully_added' => 'post successfully added',
  '_powered_by' => 'Powered by',
  '_question' => 'Question',
  '_ratio' => 'ratio',
  '_read' => 'read',
  '_recurring not allowed' => 'recurring not allowed',
  '_recurring not supported' => 'recurring not supported',
  '_recurring payment' => 'recurring payment',
  '_refresh' => 'refresh',
  '_requires_N_members' => 'requires {0} members',
  '_sbs_txt_sbs_profile_rates' => 'New votes for <b>{0}</b> profile',
  '_seconds ago' => 'seconds ago',
  '_seeking a' => 'seeking a',
  '_send eCards' => 'send eCards',
  '_send greetings' => 'send greetings',
  '_send messages' => 'send messages',
  '_sorry, i can not define you ip adress. IT\'S TIME TO COME OUT !' => 'Sorry, I can\'t define your IP address. IT\'S TIME TO COME OUT!',
  '_sys_adm_btn_dnsbl_settings' => 'Settings',
  '_sys_album_caption_err_capt' => 'Incorrect album name',
  '_sys_album_edit' => 'Edit album',
  '_sys_album_reverse' => 'Reverse',
  '_sys_breadcrumb_account' => 'Account',
  '_sys_breadcrumb_guest' => 'Guest',
  '_sys_breadcrumb_join' => 'Join',
  '_sys_breadcrumb_login' => 'Login',
  '_sys_breadcrumb_logout' => 'Logout',
  '_sys_from_album' => 'from album',
  '_sys_invitation_no_users_selected' => 'Please check at least one user or write at least one email',
  '_tags_date' => 'Empty',
  '_tags_empty' => 'Empty',
  '_tags_home' => 'Tags Home',
  '_tags_not_found' => 'Tags Not Found',
  '_tags_search' => 'Search',
  '_td_allow_comment' => 'Allow commenting on my feedback',
  '_td_allow_vote' => 'Allow voting on my feedback',
  '_td_categories' => 'Categories',
  '_this_member' => 'this member',
  '_to_compose_new_message' => 'To compose new message for <strong>{0}</strong> click <a href="{2}compose.php?ID={1}">here</a>.',
  '_toggle' => 'toggle',
  '_too_many_files' => 'You have reached allowed file limit',
  '_unread' => 'unread',
  '_use Orca private forums' => 'use Orca private forums',
  '_use Orca public forums' => 'use Orca public forums',
  '_use Ray chat' => 'use Ray chat',
  '_use Ray instant messenger' => 'use Ray instant messenger',
  '_use Ray video recorder' => 'use Ray video recorder',
  '_use chat' => 'use chat',
  '_use forum' => 'use forum',
  '_use gallery' => 'use gallery',
  '_view Video' => 'view Video',
  '_view as photo gallery' => 'view as photo gallery',
  '_view as profile details' => 'view as profile details',
  '_view other members\' galleries' => 'view other member galleries',
  '_view profiles' => 'view profiles',
  '_viewed' => 'viewed',
  '_vote' => 'vote',
  '_why_join_desc' => '<div class="dbContentHtml"><p>There are plenty of reasons to join - chief among them is that you will receive the benefits presented to members of this site by the administrator, including any promotional benefits that may be offered to new members. This is your chance to use software that has been improved through many version releases and brings you the best in website design.</p></div>',
  '_within' => 'within',
  '_wrote' => 'wrote',
  '_{0} votes' => '{0} votes',
  */
);
