<?php

$aLangContent = array(
	'_Report about spam was sent' => 'Spam report was sent',
	'_Report about spam failed to sent' => 'Spam report failed to send',
	'_SIMG_ERR' => 'Code from security image is incorrect',
    '_Membership_name_err_empty' => 'You need to select a membership level',
	'_ATT_ACTIVE_E' => 'You are a full-featured member of our community. You can, however, suspend your profile so that it is temporarily unavailable for others.',
	'_ATT_MESSAGE' => 'A <b><a href="{1}mail.php?mode=inbox">New message</a></b> is waiting for you!',
	'_ATT_VKISS' => 'A <b><a href="{0}communicator.php?communicator_mode=greeting_requests&person_switcher=to">New greeting</a></b> is waiting for you!',
	'_ATT_FRIEND' => 'A <b><a href="{0}communicator.php?communicator_mode=friends_list">New Friend</a></b> is waiting for you!',
	'_CONTACT' => 'Your contact information is here',
	'_DELETE_SUCCESS' => 'Your account was successfully deleted',
	'_DELETE_TEXT' => 'All of your content will be deleted. Are you sure you want to delete your account?',
	'_PWD_INVALID2' => 'Password confirmation failed, make sure that your password is between 5 and 8 characters long.',
	'_EMAIL_CONF_FAILED_EX' => 'This could happen because your web mail service displays web links improperly. If you see this message, please try to <u>exactly</u> copy the link supplied with the confirmation e-mail and paste it into your browser\'s address bar <b>or</b> just enter the confirmation code (which also comes with the e-mail) below:',
	'_FAILED_TO_SEND_MESSAGE_BLOCK' => 'Failed to send message. This member has blocked you.',
	'_FAILED_TO_UPLOAD_PIC' => 'Failed to upload file <b>{0}</b>! Make sure it\'s a picture in <b>jpg</b>, <b>gif</b>, or <b>png</b> format.<br /><div class=small>(Error code: {1})</div><br /><br />',
	'_FREEMAIL_ALREADY_SENT' => 'You have already requested this member\'s contact information for free. You can see it in <a href="profile.php?ID={0}">their profile</a>, or in <a href="communicator.php">your communicator</a>.',
	'_FREEMAIL_BLOCK' => 'Sorry, contact information could not be sent to you. This member has blocked you.',
	'_INCORRECT_EMAIL' => 'The e-mail you entered doesn\'t seem to be valid. Please try again.',
	'_INVALID_PASSWD' => 'Sorry, invalid password! Please try again.',
	'_MEMBERS_YOU_KISSED_BY' => 'Members who greeted you',
	'_MEMBERS_YOU_VIEWED_BY' => 'Members who viewed you',
	'_MEMBERS_YOU_HOTLISTED_BY' => 'Members who hotlisted you',
	'_MEMBERS_YOU_INVITED_FRIENDLIST' => 'Members who invited you',
	'_MEMBERS_YOU_BLOCKLISTED_BY' => 'Members who blocked you',
	'_NO_NEED_TO_CONFIRM_EMAIL' => 'There is no need to confirm your account e-mail because it\'s already been confirmed.',
	'_PROFILE_CAN_SUSPEND' => 'You can suspend your account, making it temporarily unavailable for search and contact. You can always reactivate it later.',
	'_RESULT-1' => '<b>Transaction verification failed.</b> You seem to have tried to cheat our security system. Your IP has been logged and reported. If you are persistent in your attempts, you will be banned from our system.',
	'_RESULT-1_D' => 'You seem to have tried to cheat our security system. Your IP has been logged and reported. If you are persistent in your attempts, you will be banned from our system.',
	'_RESULT1_THANK' => 'Thank you for your participation in {0} We appreciate your purchase and you will receive an email at {1}',
	'_VKISS_BAD_COUSE_A3' => 'Profile authentication failed',
	'_VKISS_BAD_COUSE_Y' => 'Sorry, you have been blocked by this member',
	'__Gujrati' => 'Gujarati',
	'__Moldovian' => 'Moldavian',
	'_get other members emails' => 'get other members\' emails',
	'_no_messages_to' => 'You did not write any messages to {0}',
	'_Invites succesfully sent' => 'Invites successfully sent',
	'_FieldCaption_EmailNotify_Edit' => 'Receive site notifications',
	'_FieldCaption_EmailNotify_Join' => 'Receive site notifications',
	'_FieldDesc_NickName_Join' => 'Choose a Username which will be used for logging in to the site',
	'_FieldError_NickName_Unique' => 'This Username is already in use by another member. Please select another Username.',
	'_FieldError_Email_Unique' => 'Your email has already been used by another member',
	'_FieldCaption_DateOfBirth_Search' => 'Age',
	'_Save profile successful' => 'The profile was successfully saved',
	'_Thumb Up' => 'Thumbs Up',
	'_Thumb Down' => 'Thumbs Down',
	'_td_allow_comment' => 'Allow commenting on my feedback',
	'_td_allow_vote' => 'Allow voting on my feedback',
	'_ps_fnote_default_group' => 'When you post content you can choose "default" privacy group and then change the "default" value anytime. Thus, you can start posting for your friends only, and later, for example, open everything for all members or even go public. Define "default" value here and choose "default" when posting content to have this global control.',
    '_ps_ferr_incorrect_select' => 'You need to select some values',
    '_ps_group_1_title' => 'Default',
    '_ps_group_2_title' => 'Me Only',
    '_ps_group_3_title' => 'Public',
    '_ps_group_4_title' => 'Members',
    '_ps_group_5_title' => 'Friends',
    '_ps_group_6_title' => 'Faves',
    '_ps_group_7_title' => 'Contacts',
    '_sys_album_caption_err_capt' => 'Incorrect album name',
    '_adm_txt_dashboard_license_unlimit' => 'License never expires',
    '_adm_txt_dashboard_users_unconfirmed' => 'Unconfirmed',
    '_adm_txt_mlevels_actions_avail_desc' => 'Leave it blank if the action is available every time',
    '_adm_txt_modules_process_action_failed' => 'An error occurred. Contact with module\'s vendor',
    '_adm_txt_modules_recompile_global_paramaters' => 'Recompiling global parameters:',
    '_sys_txt_sbs_error_occured' => 'Unknown error occurred. Please report.',
    '_sbs_wrn_email_notify_disabled' => 'You will not receive any subscription emails because you set to not receive any site notifications, you can change this setting <a href="{0}">here</a>.',
    '_adm_mmail_X_emails_was_succ_added_to_queue' => '{0} emails were successfully added to queue.',
    '_adm_dbtools_succ_dumped_into_file' => 'Data successfully dumped into file',
    '_adm_dbtools_Dump_file_succefully_deleted' => 'Dump file successfully deleted',
    '_adm_dbtools_Data_succefully_restored_from_dump' => 'Data successfully restored from server dump',
    '_adm_dbtools_Data_succefully_restored_from_PC' => 'Data successfully restored from your PC',
    '_adm_fields_error_you_entered_incorrect_link' => 'You entered an incorrect link',
    '_adm_admtools_Not_Exists' => 'Does Not Exists',
	'_FieldCaption_Religious_Edit' => 'Religion',
	'_FieldDesc_Religious_Edit' => 'Your religion',
    '_sbd_iPhone_desc' => "Have an iPhone?\r\nAccess our site on your iPhone while you're on the go!",
    '_sbd_Android_desc' => "Have an Android device?\r\nAccess our site on your handset while you're on the go!",
    '_mma_get_other_members_emails' => 'get other members\' emails',
	'_You have blocked by this profile' => 'You have been blocked by this profile',
    '_FAILED_TO_SEND_MESSAGE_MEMBERSHIP_DISALLOW' => 'Your membership level doesn\'t allow you to send messages',
    '_sys_adm_form_err_required_field' => 'This is a required field',
    '_sys_sucess_result' => 'Data has been successfully submitted.',
    '_sys_spam_detected' => 'Sorry, it looks like you are trying to submit spam. If you believe that this is a mistake, please submit a false positive report here: %s',
    '_Error Occured' => 'Error Occurred',
);

?>
