<?php

$aLangContent = array(

  // ================ CHANGED KEYS ==================

  '_bx_groups_action_add_to_featured' => 'В избранное',
  '_bx_groups_action_manage_fans' => 'Фанаты',
  '_bx_groups_action_remove_from_featured' => 'Не избранное',
  '_bx_groups_action_title_edit' => 'Изменить',
  '_bx_groups_action_title_share' => 'Поделиться',
  '_bx_groups_action_upload_files' => 'Файлы',
  '_bx_groups_action_upload_photos' => 'Изображения',
  '_bx_groups_action_upload_sounds' => 'Аудио',
  '_bx_groups_action_upload_videos' => 'Видео',
  '_bx_groups_admin_delete' => 'Удалить',
  '_bx_groups_block_my_groups' => 'Мои группы',
  '_bx_groups_block_submenu_pending_groups' => 'Ожидающие',
  '_bx_groups_caption_share_group' => 'Поделиться',
  '_bx_groups_form_header_files' => 'Файлы',
  '_bx_groups_form_header_images' => 'Фото',
  '_bx_groups_form_header_info' => 'Информация',
  '_bx_groups_form_header_sounds' => 'Аудио',
  '_bx_groups_form_header_videos' => 'Видео',
  '_bx_groups_menu_admin_entries' => 'Администрирование',
  '_bx_groups_menu_admin_pending_approval' => 'Ожидающие',
  '_bx_groups_msg_added_to_featured' => 'Группа была добавлена в избранное',
  '_bx_groups_msg_pending_approval' => 'Эта группа ожиданет модерации. Пожалуйста, подождите, пока она не будет активна.',
  '_bx_groups_msg_removed_from_featured' => 'Группа была удалена из избранного',
  '_bx_groups_msg_you_have_pending_approval_groups' => 'У Вас <a href="%s">%d ожидающих групп.</a>',
  '_bx_groups_page_title_browse_by_author' => ' автор групп',
  '_bx_groups_page_title_browse_by_author_joined_groups' => ' состоит в группах',
  '_bx_groups_page_title_browse_by_category' => 'Обзор групп по категоиям: ',
  '_bx_groups_page_title_browse_by_day' => 'Обзор групп по дням: ',
  '_bx_groups_page_title_browse_by_tag' => 'Обзор групп по тегам: ',
  '_bx_groups_page_title_calendar' => 'Календарь ',
  '_bx_groups_page_title_categories' => 'Категории',
  '_bx_groups_page_title_fans' => 'Группа фанаты',
  '_bx_groups_page_title_my_groups' => 'Мои группы',
  '_bx_groups_page_title_pending_approval' => 'Ожидающие группы',
  '_bx_groups_page_title_search' => 'Группы поиск',
  '_bx_groups_page_title_search_results' => 'Группы результаты поиска',
  '_bx_groups_page_title_tags' => 'Теги',
  '_bx_groups_privacy_admins_only' => 'Администраторам',
  '_bx_groups_privacy_comment' => 'Комментарии доступны',
  '_bx_groups_privacy_fans' => 'Фанатам',
  '_bx_groups_privacy_fans_only' => 'Фанатам',
  '_bx_groups_privacy_join' => 'Вступление доступно',
  '_bx_groups_privacy_post_in_forum' => 'Форум доступен',
  '_bx_groups_privacy_rate' => 'Голосование доступно',
  '_bx_groups_privacy_upload_files' => 'Загрузка файлов доступна',
  '_bx_groups_privacy_upload_photos' => 'Загрузка фото доступна',
  '_bx_groups_privacy_upload_sounds' => 'Загрузка аудио доступна',
  '_bx_groups_privacy_upload_videos' => 'Загрузка видео доступна',
  '_bx_groups_privacy_view_fans' => 'Просмотр фанатов доступен',
  '_bx_groups_privacy_view_group' => 'Просмотр доступен',
  '_mma_groups_mark_as_featured' => 'Группы: отправлять в избранное',

);
