<?php
/**
 * Copyright (c) BoonEx Pty Limited - http://www.boonex.com/
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
  '_sys_module_news' => 'News',

  '_news' => 'News',
  '_news_actions_delete' => 'Delete',
  '_news_admin_menu_sitem' => 'News',
  '_news_archive_top_menu_sitem' => 'News Archive',
  '_news_bcaption_all' => 'News',
  '_news_bcaption_all_tags' => 'All Tags',
  '_news_bcaption_archive' => 'News Archive',
  '_news_bcaption_calendar' => 'Calendar',
  '_news_bcaption_calendar_browse' => 'Browse news by day',
  '_news_bcaption_categories' => 'Categories',
  '_news_bcaption_category' => 'Category: {0}',
  '_news_bcaption_featured' => 'Featured News',
  '_news_bcaption_latest' => 'Latest News',
  '_news_bcaption_member' => 'Latest News',
  '_news_bcaption_popular' => 'Popular News',
  '_news_bcaption_post' => 'Post News',
  '_news_bcaption_settings' => 'Settings',
  '_news_bcaption_tag' => 'Tag: {0}',
  '_news_bcaption_tags' => 'Tags',
  '_news_bcaption_top_rated' => 'Top Rated News',
  '_news_bcaption_view_action' => 'Actions',
  '_news_bcaption_view_comment' => 'Comments',
  '_news_bcaption_view_info' => 'Info',
  '_news_bcaption_view_main' => 'News',
  '_news_bcaption_view_vote' => 'Rating',
  '_news_calendar_top_menu_sitem' => 'Calendar',
  '_news_categories_top_menu_sitem' => 'Categories',
  '_news_chart' => 'News',
  '_news_entry_plural' => 'news',
  '_news_entry_single' => 'news',
  '_news_featured' => 'featured',
  '_news_featured_top_menu_sitem' => 'Featured',
  '_news_get_rss' => 'RSS',
  '_news_home_top_menu_sitem' => 'News Home',
  '_news_lcaption_categories' => 'News',
  '_news_lcaption_delete' => 'Delete',
  '_news_lcaption_edit' => 'Edit',
  '_news_lcaption_featured' => 'Featured',
  '_news_lcaption_publish' => 'Publish',
  '_news_lcaption_search_object' => 'News',
  '_news_lcaption_tags' => 'News',
  '_news_lcaption_unfeatured' => 'Unfeatured',
  '_news_lcaption_unpublish' => 'Unpublish',
  '_news_msg_failed_delete' => 'Cannot delete the news. Check whether you have the necessary permissions.',
  '_news_msg_no_results' => 'Empty',
  '_news_msg_success_delete' => 'News was deleted.',
  '_news_pcaption_admin' => 'News',
  '_news_pcaption_archive' => 'News Archive',
  '_news_pcaption_calendar' => 'Calendar',
  '_news_pcaption_categories' => 'Categories',
  '_news_pcaption_category' => 'Category: {0}',
  '_news_pcaption_featured' => 'Featured News',
  '_news_pcaption_home' => 'News Home',
  '_news_pcaption_popular' => 'Popular News',
  '_news_pcaption_tag' => 'Tag: {0}',
  '_news_pcaption_tags' => 'Tags',
  '_news_pcaption_top_rated' => 'Top Rated News',
  '_news_popular_top_menu_sitem' => 'Popular',
  '_news_rss_caption' => 'News',
  '_news_sbs_commentPost' => '{0} (New News Comments)',
  '_news_sbs_main' => '{0}',
  '_news_search_top_menu_sitem' => 'Search',
  '_news_sitemap' => 'News',
  '_news_ss' => 'News Posts',
  '_news_ss_adm_stats' => 'Pending News Posts',
  '_news_status_0' => 'active',
  '_news_status_1' => 'inactive',
  '_news_status_2' => 'pending',
  '_news_tags_top_menu_sitem' => 'Tags',
  '_news_top_menu_item' => 'News',
  '_news_top_top_menu_sitem' => 'Top Rated',
  '_news_view_top_menu_sitem' => 'News',
  '_sbs_txt_title_bx_news' => 'News',
  '_mma_News_Delete' => 'news delete',
);
