<?php
/**
 * Copyright (c) BoonEx Pty Limited - http://www.boonex.com/
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
  '_sys_module_news' => 'Новости',

  '_news' => 'Новости',
  '_news_actions_delete' => 'Удалить',
  '_news_admin_menu_sitem' => 'Новости',
  '_news_archive_top_menu_sitem' => 'Архив',
  '_news_bcaption_all' => 'Новости',
  '_news_bcaption_all_tags' => 'Все теги',
  '_news_bcaption_archive' => 'Архив новостей',
  '_news_bcaption_calendar' => 'Календарь',
  '_news_bcaption_calendar_browse' => 'Просматривать новости по дням',
  '_news_bcaption_categories' => 'Категории',
  '_news_bcaption_category' => 'Категория: {0}',
  '_news_bcaption_featured' => 'Избранные новости',
  '_news_bcaption_latest' => 'Последние новости',
  '_news_bcaption_member' => 'Последние новости',
  '_news_bcaption_popular' => 'Популярные новости',
  '_news_bcaption_post' => 'Создание новости',
  '_news_bcaption_settings' => 'Настройки',
  '_news_bcaption_tag' => 'Тег: {0}',
  '_news_bcaption_tags' => 'Теги',
  '_news_bcaption_top_rated' => 'Лучшие новости',
  '_news_bcaption_view_action' => 'Действия',
  '_news_bcaption_view_comment' => 'Комментарии',
  '_news_bcaption_view_info' => 'Информация',
  '_news_bcaption_view_main' => 'Новости',
  '_news_bcaption_view_vote' => 'Рейтинг',
  '_news_calendar_top_menu_sitem' => 'Календарь',
  '_news_categories_top_menu_sitem' => 'Категории',
  '_news_chart' => 'Новости',
  '_news_entry_plural' => 'новости',
  '_news_entry_single' => 'новости',
  '_news_featured' => 'избранные',
  '_news_featured_top_menu_sitem' => 'Избранные',
  '_news_get_rss' => 'RSS',
  '_news_home_top_menu_sitem' => 'Главная',
  '_news_lcaption_categories' => 'Новости',
  '_news_lcaption_delete' => 'Удалить',
  '_news_lcaption_edit' => 'Изменить',
  '_news_lcaption_featured' => 'В избранное',
  '_news_lcaption_publish' => 'Публикация',
  '_news_lcaption_search_object' => 'Новости',
  '_news_lcaption_tags' => 'Новости',
  '_news_lcaption_unfeatured' => 'Не избранное',
  '_news_lcaption_unpublish' => 'Отменить публикацию',
  '_news_msg_failed_delete' => 'Невозможно удалить новости. Удостоверьтесь, что у Вас есть необходимые разрешения.',
  '_news_msg_no_results' => 'Пусто',
  '_news_msg_success_delete' => 'Новости были удалены.',
  '_news_pcaption_admin' => 'Новости',
  '_news_pcaption_archive' => 'Архив новостей',
  '_news_pcaption_calendar' => 'Календарь',
  '_news_pcaption_categories' => 'Категории',
  '_news_pcaption_category' => 'Категория: {0}',
  '_news_pcaption_featured' => 'Избранные новости',
  '_news_pcaption_home' => 'Главная',
  '_news_pcaption_popular' => 'Популярные новости',
  '_news_pcaption_tag' => 'Тег: {0}',
  '_news_pcaption_tags' => 'Теги',
  '_news_pcaption_top_rated' => 'Лучшие новости',
  '_news_popular_top_menu_sitem' => 'Популярные',
  '_news_rss_caption' => 'Новости',
  '_news_sbs_commentPost' => '{0} (новых комментариев к новости)',
  '_news_sbs_main' => '{0}',
  '_news_search_top_menu_sitem' => 'Поиск',
  '_news_sitemap' => 'Новости',
  '_news_ss' => 'Новостей',
  '_news_ss_adm_stats' => 'Новостные сообщения на модерации',
  '_news_status_0' => 'активные',
  '_news_status_1' => 'неактивные',
  '_news_status_2' => 'на модерации',
  '_news_tags_top_menu_sitem' => 'Теги',
  '_news_top_menu_item' => 'Новости',
  '_news_top_top_menu_sitem' => 'Лучшие',
  '_news_view_top_menu_sitem' => 'Новости',
  '_sbs_txt_title_bx_news' => 'Новости',
  '_mma_News_Delete' => 'Новости: удалять',
);
